#pragma warning disable CS1591

using System.Text.Json;
using Microsoft.AspNetCore.Antiforgery;
using MiniErp.App.BuildingBlocks.Rest;
using MiniErp.App.Modules.Finance;
using MiniErp.App.Modules.Inventory;
using MiniErp.App.Modules.Procurement;
using MiniErp.App.Modules.Sales;
using MiniErp.Contracts.Modules.Foundation;
using MiniErp.Contracts.Modules.Finance;
using MiniErp.Contracts.Modules.Inventory;
using MiniErp.Contracts.Modules.Sales;

namespace MiniErp.Api;

public static class CustomerReturnEndpoints
{
    public static IEndpointRouteBuilder MapCustomerReturnEndpoints(this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapGet("/api/v1/sales/customer-return-sources", async (HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, SalesCustomerReturnService service) =>
            await SalesRead<IReadOnlyList<SalesCustomerReturnSourceResponse>>(http, resolver, tenant, "sales.customer-return.eligible-source.list", context => service.ListEligibleSourcesAsync(context, http.RequestAborted), value => value)).WithName("sales.customer-return.eligible-source.list").WithMetadata(Metadata("sales.customer-return.eligible-source.list"));
        endpoints.MapGet("/api/v1/sales/customer-return-sources/{deliveryId:guid}", async (Guid deliveryId, HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, SalesCustomerReturnService service) =>
            await SalesRead(http, resolver, tenant, "sales.customer-return.eligible-source.read", context => service.GetEligibleSourceAsync(context, deliveryId, http.RequestAborted), value => value)).WithName("sales.customer-return.eligible-source.read").WithMetadata(Metadata("sales.customer-return.eligible-source.read"));
        endpoints.MapPost("/api/v1/sales/customer-returns", async (SalesCustomerReturnCreateRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, SalesCustomerReturnService service) =>
        {
            if (request is null) return Problem(400, "validation_failed", "sales.customer-return.create");
            return await ExecuteMutationAsync(http, resolver, tenant, "sales.customer-return.create", null, (context, _, _) => service.CreateAsync(context, request, Key(http), http.RequestAborted));
        }).WithName("sales.customer-return.create").WithMetadata(Metadata("sales.customer-return.create"));
        endpoints.MapGet("/api/v1/sales/customer-returns/{returnId:guid}", async (Guid returnId, HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, SalesCustomerReturnService service) =>
            await SalesRead(http, resolver, tenant, "sales.customer-return.read", context => service.GetAsync(context, returnId, http.RequestAborted), value => value, true)).WithName("sales.customer-return.read").WithMetadata(Metadata("sales.customer-return.read"));
        endpoints.MapPost("/api/v1/sales/customer-returns/{returnId:guid}/submit", async (Guid returnId, SalesCustomerReturnActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, SalesCustomerReturnService service) => await ExecuteMutationAsync(http, resolver, tenant, "sales.customer-return.submit", returnId, (context, version, _) => service.MutateAsync(context, returnId, version!, SalesCustomerReturnMutation.Submit, request?.Reason, Key(http), http.RequestAborted))).WithName("sales.customer-return.submit").WithMetadata(Metadata("sales.customer-return.submit"));
        endpoints.MapPost("/api/v1/sales/customer-returns/{returnId:guid}/approve", async (Guid returnId, SalesCustomerReturnActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, SalesCustomerReturnService service) => await ExecuteMutationAsync(http, resolver, tenant, "sales.customer-return.approve", returnId, (context, version, _) => service.MutateAsync(context, returnId, version!, SalesCustomerReturnMutation.Approve, request?.Reason, Key(http), http.RequestAborted))).WithName("sales.customer-return.approve").WithMetadata(Metadata("sales.customer-return.approve"));
        endpoints.MapPost("/api/v1/sales/customer-returns/{returnId:guid}/reject", async (Guid returnId, SalesCustomerReturnActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, SalesCustomerReturnService service) => await ExecuteMutationAsync(http, resolver, tenant, "sales.customer-return.reject", returnId, (context, version, _) => service.MutateAsync(context, returnId, version!, SalesCustomerReturnMutation.Reject, request?.Reason, Key(http), http.RequestAborted))).WithName("sales.customer-return.reject").WithMetadata(Metadata("sales.customer-return.reject"));
        endpoints.MapPost("/api/v1/sales/customer-returns/{returnId:guid}/cancel", async (Guid returnId, SalesCustomerReturnActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, SalesCustomerReturnService service) => await ExecuteMutationAsync(http, resolver, tenant, "sales.customer-return.cancel", returnId, (context, version, _) => service.MutateAsync(context, returnId, version!, SalesCustomerReturnMutation.Cancel, request?.Reason, Key(http), http.RequestAborted))).WithName("sales.customer-return.cancel").WithMetadata(Metadata("sales.customer-return.cancel"));
        endpoints.MapPost("/api/v1/sales/customer-returns/{returnId:guid}/reverse", async (Guid returnId, SalesCustomerReturnActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, SalesCustomerReturnService service) => await ExecuteMutationAsync(http, resolver, tenant, "sales.customer-return.reverse", returnId, (context, version, _) => service.MutateAsync(context, returnId, version!, SalesCustomerReturnMutation.Reverse, request?.Reason, Key(http), http.RequestAborted))).WithName("sales.customer-return.reverse").WithMetadata(Metadata("sales.customer-return.reverse"));
        endpoints.MapGet("/api/v1/sales/customer-returns/{returnId:guid}/history", async (Guid returnId, HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, SalesCustomerReturnService service) =>
            await SalesRead(http, resolver, tenant, "sales.customer-return.history.read", context => service.ListHistoryAsync(context, returnId, http.RequestAborted), value => value)).WithName("sales.customer-return.history.read").WithMetadata(Metadata("sales.customer-return.history.read"));
        endpoints.MapGet("/api/v1/sales/customer-returns/{returnId:guid}/audit", async (Guid returnId, HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, SalesCustomerReturnService service) =>
            await SalesRead(http, resolver, tenant, "sales.customer-return.audit.read", context => service.ListAuditAsync(context, returnId, http.RequestAborted), value => value)).WithName("sales.customer-return.audit.read").WithMetadata(Metadata("sales.customer-return.audit.read"));

        endpoints.MapGet("/api/v1/inventory/customer-returns/{salesCustomerReturnId:guid}", async (Guid salesCustomerReturnId, HttpContext http, ITrustedRequestContextResolver resolver, InventoryTenantContextResolver tenant, InventoryCustomerReturnService service) =>
            await InventoryRead(http, resolver, tenant, "inventory.customer-return.read", context => service.GetAsync(context, salesCustomerReturnId, http.RequestAborted), true)).WithName("inventory.customer-return.read").WithMetadata(Metadata("inventory.customer-return.read"));
        endpoints.MapPost("/api/v1/inventory/customer-returns/{salesCustomerReturnId:guid}/receive", async (Guid salesCustomerReturnId, InventoryCustomerReturnReceiptRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, InventoryTenantContextResolver tenant, InventoryCustomerReturnService service) =>
            request is null ? Problem(400, "validation_failed", "inventory.customer-return.receive") : await ExecuteMutationAsync(http, resolver, tenant, "inventory.customer-return.receive", true, (context, version) => service.ReceiveAsync(context, salesCustomerReturnId, version!, request, Key(http), http.RequestAborted))).WithName("inventory.customer-return.receive").WithMetadata(Metadata("inventory.customer-return.receive"));
        endpoints.MapPost("/api/v1/inventory/customer-returns/{salesCustomerReturnId:guid}/inspect", async (Guid salesCustomerReturnId, InventoryCustomerReturnInspectionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, InventoryTenantContextResolver tenant, InventoryCustomerReturnService service) =>
            request is null ? Problem(400, "validation_failed", "inventory.customer-return.inspect") : await ExecuteMutationAsync(http, resolver, tenant, "inventory.customer-return.inspect", true, (context, version) => service.InspectAsync(context, salesCustomerReturnId, version!, request, Key(http), http.RequestAborted))).WithName("inventory.customer-return.inspect").WithMetadata(Metadata("inventory.customer-return.inspect"));

        endpoints.MapGet("/api/v1/finance/credit-notes/{creditNoteId:guid}", async (Guid creditNoteId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceCustomerReturnService service) =>
            await FinanceRead(http, resolver, "finance.credit-note.read", context => service.GetAsync(context, creditNoteId, http.RequestAborted), true)).WithName("finance.credit-note.read").WithMetadata(Metadata("finance.credit-note.read"));
        endpoints.MapPost("/api/v1/finance/credit-notes", async (FinanceCreditNoteCreateRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceCustomerReturnService service) =>
            request is null ? Problem(400, "validation_failed", "finance.credit-note.create") : await ExecuteMutationAsync(http, resolver, "finance.credit-note.create", false, (context, version) => service.CreateAsync(context, request, Key(http), http.RequestAborted))).WithName("finance.credit-note.create").WithMetadata(Metadata("finance.credit-note.create"));
        endpoints.MapPost("/api/v1/finance/credit-notes/{creditNoteId:guid}/submit", async (Guid creditNoteId, FinanceCreditNoteActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceCustomerReturnService service) => await ExecuteMutationAsync(http, resolver, "finance.credit-note.submit", true, (context, version) => service.MutateAsync(context, creditNoteId, version!, FinanceCreditNoteMutation.Submit, request?.Reason, Key(http), http.RequestAborted))).WithName("finance.credit-note.submit").WithMetadata(Metadata("finance.credit-note.submit"));
        endpoints.MapPost("/api/v1/finance/credit-notes/{creditNoteId:guid}/approve", async (Guid creditNoteId, FinanceCreditNoteActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceCustomerReturnService service) => await ExecuteMutationAsync(http, resolver, "finance.credit-note.approve", true, (context, version) => service.MutateAsync(context, creditNoteId, version!, FinanceCreditNoteMutation.Approve, request?.Reason, Key(http), http.RequestAborted))).WithName("finance.credit-note.approve").WithMetadata(Metadata("finance.credit-note.approve"));
        endpoints.MapPost("/api/v1/finance/credit-notes/{creditNoteId:guid}/reject", async (Guid creditNoteId, FinanceCreditNoteActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceCustomerReturnService service) => await ExecuteMutationAsync(http, resolver, "finance.credit-note.reject", true, (context, version) => service.MutateAsync(context, creditNoteId, version!, FinanceCreditNoteMutation.Reject, request?.Reason, Key(http), http.RequestAborted))).WithName("finance.credit-note.reject").WithMetadata(Metadata("finance.credit-note.reject"));
        endpoints.MapPost("/api/v1/finance/credit-notes/{creditNoteId:guid}/cancel", async (Guid creditNoteId, FinanceCreditNoteActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceCustomerReturnService service) => await ExecuteMutationAsync(http, resolver, "finance.credit-note.cancel", true, (context, version) => service.MutateAsync(context, creditNoteId, version!, FinanceCreditNoteMutation.Cancel, request?.Reason, Key(http), http.RequestAborted))).WithName("finance.credit-note.cancel").WithMetadata(Metadata("finance.credit-note.cancel"));
        endpoints.MapPost("/api/v1/finance/credit-notes/{creditNoteId:guid}/post", async (Guid creditNoteId, FinanceCreditNoteActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceCustomerReturnService service) => await ExecuteMutationAsync(http, resolver, "finance.credit-note.post", true, (context, version) => service.MutateAsync(context, creditNoteId, version!, FinanceCreditNoteMutation.Post, request?.Reason, Key(http), http.RequestAborted))).WithName("finance.credit-note.post").WithMetadata(Metadata("finance.credit-note.post"));
        endpoints.MapPost("/api/v1/finance/credit-notes/{creditNoteId:guid}/reverse", async (Guid creditNoteId, FinanceCreditNoteActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceCustomerReturnService service) => await ExecuteMutationAsync(http, resolver, "finance.credit-note.reverse", true, (context, version) => service.MutateAsync(context, creditNoteId, version!, FinanceCreditNoteMutation.Reverse, request?.Reason, Key(http), http.RequestAborted))).WithName("finance.credit-note.reverse").WithMetadata(Metadata("finance.credit-note.reverse"));
        return endpoints;
    }

    private static async Task<IResult> SalesRead<T>(HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, string operation, Func<ProcurementRequestContext, Task<SalesCustomerReturnOperationResult<T>>> action, Func<T, object?> map, bool etag = false)
    {
        var foundation = await resolver.ResolveAsync(http, http.RequestAborted); var resolved = tenant.Resolve(foundation);
        if (!resolved.Allowed || resolved.Context is null) return Problem(foundation.SecurityProfile == FoundationSecurityProfile.Anonymous ? 401 : 403, resolved.Code, operation);
        var result = await action(resolved.Context); if (!result.Succeeded || result.Value is null) return Problem(Status(result.Code), result.Code, operation);
        if (etag && result.Value is SalesCustomerReturnResponse value) SetEtag(http, value.Version);
        return Results.Ok(map(result.Value));
    }

    private static async Task<IResult> ExecuteMutationAsync<T>(HttpContext http, ITrustedRequestContextResolver resolver, ProcurementTenantContextResolver tenant, string operation, Guid? id, Func<ProcurementRequestContext, byte[]?, string?, Task<SalesCustomerReturnOperationResult<T>>> action)
    {
        if (!await Anti(http)) return Problem(403, "antiforgery_failed", operation); var key = Key(http); if (!FoundationCorrelation.IsValid(key)) return Problem(400, "idempotency_key_invalid", operation); var version = id is null ? null : ReadVersion(http); if (id is not null && version is null) return Problem(400, "version_required", operation);
        var foundation = await resolver.ResolveAsync(http, http.RequestAborted); var resolved = tenant.Resolve(foundation); if (!resolved.Allowed || resolved.Context is null) return Problem(foundation.SecurityProfile == FoundationSecurityProfile.Anonymous ? 401 : 403, resolved.Code, operation);
        var result = await action(resolved.Context, version, key); if (!result.Succeeded || result.Value is null) return Problem(Status(result.Code), result.Code, operation); if (result.Value is SalesCustomerReturnResponse value) SetEtag(http, value.Version); return Results.Ok(result.Value);
    }

    private static async Task<IResult> InventoryRead<T>(HttpContext http, ITrustedRequestContextResolver resolver, InventoryTenantContextResolver tenant, string operation, Func<InventoryRequestContext, Task<InventoryOperationResult<T>>> action, bool etag = false)
    {
        var foundation = await resolver.ResolveAsync(http, http.RequestAborted); var resolved = tenant.Resolve(foundation); if (!resolved.Allowed || resolved.Context is null) return Problem(foundation.SecurityProfile == FoundationSecurityProfile.Anonymous ? 401 : 403, resolved.Code, operation); var result = await action(resolved.Context); if (!result.Succeeded || result.Value is null) return Problem(Status(result.Code), result.Code, operation); if (etag && result.Value is InventoryCustomerReturnResponse value) SetEtag(http, value.Version); return Results.Ok(result.Value);
    }

    private static async Task<IResult> ExecuteMutationAsync(HttpContext http, ITrustedRequestContextResolver resolver, InventoryTenantContextResolver tenant, string operation, bool needsVersion, Func<InventoryRequestContext, byte[]?, Task<InventoryOperationResult<InventoryCustomerReturnResponse>>> action)
    {
        if (!await Anti(http)) return Problem(403, "antiforgery_failed", operation); var key = Key(http); if (!FoundationCorrelation.IsValid(key)) return Problem(400, "idempotency_key_invalid", operation); var version = needsVersion ? ReadVersion(http) : null; if (needsVersion && version is null) return Problem(400, "version_required", operation); var foundation = await resolver.ResolveAsync(http, http.RequestAborted); var resolved = tenant.Resolve(foundation); if (!resolved.Allowed || resolved.Context is null) return Problem(foundation.SecurityProfile == FoundationSecurityProfile.Anonymous ? 401 : 403, resolved.Code, operation); var result = await action(resolved.Context, version); if (!result.Succeeded || result.Value is null) return Problem(Status(result.Code), result.Code, operation); SetEtag(http, result.Value.Version); return Results.Ok(result.Value);
    }

    private static async Task<IResult> FinanceRead<T>(HttpContext http, ITrustedRequestContextResolver resolver, string operation, Func<FinanceRequestContext, Task<FinanceOperationResult<T>>> action, bool etag = false)
    {
        var foundation = await resolver.ResolveAsync(http, http.RequestAborted); if (!FinanceRequestContext.TryCreate(foundation, out var context) || context is null) return Problem(foundation.SecurityProfile == FoundationSecurityProfile.Anonymous ? 401 : 403, "finance_context_failed", operation); var result = await action(context); if (!result.Succeeded || result.Value is null) return Problem(Status(result.Code), result.Code, operation); if (etag && result.Value is FinanceCreditNoteResponse value) SetEtag(http, value.Version); return Results.Ok(result.Value);
    }

    private static async Task<IResult> ExecuteMutationAsync(HttpContext http, ITrustedRequestContextResolver resolver, string operation, bool needsVersion, Func<FinanceRequestContext, byte[]?, Task<FinanceOperationResult<FinanceCreditNoteResponse>>> action)
    {
        if (!await Anti(http)) return Problem(403, "antiforgery_failed", operation); var key = Key(http); if (!FoundationCorrelation.IsValid(key)) return Problem(400, "idempotency_key_invalid", operation); var version = needsVersion ? ReadVersion(http) : null; if (needsVersion && version is null) return Problem(400, "version_required", operation); var foundation = await resolver.ResolveAsync(http, http.RequestAborted); if (!FinanceRequestContext.TryCreate(foundation, out var context) || context is null) return Problem(foundation.SecurityProfile == FoundationSecurityProfile.Anonymous ? 401 : 403, "finance_context_failed", operation); var result = await action(context, version); if (!result.Succeeded || result.Value is null) return Problem(Status(result.Code), result.Code, operation); SetEtag(http, result.Value.Version); return Results.Ok(result.Value);
    }

    private static FoundationOperationMetadata Metadata(string operation) => new(FoundationOperationCatalog.GetRequired(operation));
    private static string? Key(HttpContext http) => http.Request.Headers["Idempotency-Key"].FirstOrDefault();
    private static byte[]? ReadVersion(HttpContext http) { var value = http.Request.Headers.IfMatch.FirstOrDefault(); if (string.IsNullOrWhiteSpace(value) || value.StartsWith("W/", StringComparison.OrdinalIgnoreCase)) return null; value = value.Trim(); if (value.Length > 1 && value[0] == '"' && value[^1] == '"') value = value[1..^1]; try { var version = Convert.FromBase64String(value); return version.Length is > 0 and <= 64 ? version : null; } catch (FormatException) { return null; } }
    private static void SetEtag(HttpContext http, byte[] version) => http.Response.Headers.ETag = $"\"{Convert.ToBase64String(version)}\"";
    private static async Task<bool> Anti(HttpContext http) { try { await http.RequestServices.GetRequiredService<IAntiforgery>().ValidateRequestAsync(http); return true; } catch (AntiforgeryValidationException) { return false; } }
    private static int Status(string code) => code switch { "permission_denied" => 403, "customer_return_not_found" or "return_source_not_found" or "inventory_customer_return_not_found" or "credit_note_not_found" or "sales_return_not_found" => 404, "concurrency_conflict" or "idempotency_conflict" or "return_quantity_conflict" or "customer_return_transition_invalid" or "sales_return_not_awaiting_receipt" or "inventory_customer_return_transition_invalid" or "disposition_quantity_conflict" or "delivery_cost_evidence_missing" or "credit_note_duplicate" or "credit_note_transition_invalid" or "finance_open_item_unavailable" => 409, "finance_customer_return_persistence_unavailable" or "inventory_customer_return_persistence_unavailable" => 503, _ => 400 };
    private static IResult Problem(int status, string code, string operation) => Results.Problem(statusCode: status, title: code, detail: "The customer return operation could not be completed.", extensions: new Dictionary<string, object?> { ["code"] = code, ["operationId"] = operation });
}

#pragma warning restore CS1591
