#pragma warning disable CS1591

using System.Text.Json;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Mvc;
using MiniErp.App.BuildingBlocks.Rest;
using MiniErp.App.Modules.Finance;
using MiniErp.Contracts.Modules.Finance;
using MiniErp.Contracts.Modules.Foundation;

namespace MiniErp.Api;

public static class FinanceMesp134Endpoints
{
    public static IEndpointRouteBuilder MapFinanceMesp134Endpoints(this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapGet("/api/v1/finance/monetary-policy", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await Read(http, resolver, auth, "finance.monetary-policy.list", companyId, context => persistence.ListMonetaryPoliciesAsync(context, companyId, http.RequestAborted))).WithName("finance.monetary-policy.list").WithTags("Finance / Monetary Policy").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.monetary-policy.list")));
        endpoints.MapPost("/api/v1/finance/monetary-policy", async (MonetaryPolicyRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.monetary-policy.create", request?.CompanyId, (context, key) => persistence.CreateMonetaryPolicyAsync(context, new FinanceMonetaryPolicyCommand(request!.CompanyId, request.ReportingCurrencyId, request.RoundingScale, request.RoundingMode, request.RevaluationEnabled, request.EffectiveFrom, request.EffectiveTo, Guid.NewGuid(), key, Fingerprint(request)), http.RequestAborted))).WithName("finance.monetary-policy.create").WithTags("Finance / Monetary Policy").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.monetary-policy.create")));

        endpoints.MapGet("/api/v1/finance/tax-accounting", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await Read(http, resolver, auth, "finance.tax-accounting.list", companyId, context => persistence.ListTaxEffectsAsync(context, companyId, http.RequestAborted))).WithName("finance.tax-accounting.list").WithTags("Finance / Tax Accounting").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.tax-accounting.list")));
        endpoints.MapPost("/api/v1/finance/tax-accounting/preview", async (TaxAccountingRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await Preview(http, resolver, auth, "finance.tax-accounting.preview", request?.CompanyId, context => persistence.PreviewTaxAsync(context, ToTaxCommand(request!), http.RequestAborted))).WithName("finance.tax-accounting.preview").WithTags("Finance / Tax Accounting").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.tax-accounting.preview")));
        endpoints.MapPost("/api/v1/finance/tax-accounting", async (TaxAccountingRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.tax-accounting.post", request?.CompanyId, (context, key) => persistence.PostTaxAsync(context, ToTaxCommand(request!, key), http.RequestAborted))).WithName("finance.tax-accounting.post").WithTags("Finance / Tax Accounting").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.tax-accounting.post")));
        endpoints.MapPost("/api/v1/finance/tax-accounting/{effectId:guid}/reverse", async (Guid effectId, ReverseRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, "finance.tax-accounting.reverse", null, (context, key) => persistence.ReverseTaxAsync(context, new FinanceTaxAccountingReversalCommand(effectId, version, request?.Reason ?? string.Empty, Guid.NewGuid(), key, Fingerprint(request) + Convert.ToBase64String(version)), http.RequestAborted)); }).WithName("finance.tax-accounting.reverse").WithTags("Finance / Tax Accounting").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.tax-accounting.reverse")));
        endpoints.MapGet("/api/v1/finance/tax-accounting/reconciliation", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await Read(http, resolver, auth, "finance.tax-accounting.reconciliation", companyId, context => persistence.ReconcileTaxAsync(context, companyId, http.RequestAborted))).WithName("finance.tax-accounting.reconciliation").WithTags("Finance / Tax Accounting").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.tax-accounting.reconciliation")));

        endpoints.MapGet("/api/v1/finance/revaluation", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await Read(http, resolver, auth, "finance.revaluation.list", companyId, context => persistence.ListRevaluationBatchesAsync(context, companyId, http.RequestAborted))).WithName("finance.revaluation.list").WithTags("Finance / Revaluation").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.revaluation.list")));
        endpoints.MapGet("/api/v1/finance/revaluation/{batchId:guid}", async (Guid batchId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await Read(http, resolver, auth, "finance.revaluation.detail", null, async context => await persistence.GetRevaluationBatchAsync(context, batchId, http.RequestAborted) ?? throw new FinanceResourceNotFoundException())).WithName("finance.revaluation.detail").WithTags("Finance / Revaluation").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.revaluation.detail")));
        endpoints.MapPost("/api/v1/finance/revaluation", async (RevaluationRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.revaluation.create", request?.CompanyId, (context, key) => persistence.CreateRevaluationBatchAsync(context, new FinanceRevaluationBatchCommand(request!.CompanyId, request.AsOfDate, request.Scope, Guid.NewGuid(), key, Fingerprint(request)), http.RequestAborted))).WithName("finance.revaluation.create").WithTags("Finance / Revaluation").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.revaluation.create")));
        endpoints.MapPost("/api/v1/finance/revaluation/{batchId:guid}/calculate", async (Guid batchId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.revaluation.calculate", batchId, (context, key, version) => persistence.CalculateRevaluationBatchAsync(context, new FinanceRevaluationActionCommand(batchId, version, null, Guid.NewGuid(), key, Fingerprint(batchId) + Convert.ToBase64String(version)), http.RequestAborted))).WithName("finance.revaluation.calculate").WithTags("Finance / Revaluation").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.revaluation.calculate")));
        endpoints.MapPost("/api/v1/finance/revaluation/{batchId:guid}/post", async (Guid batchId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.revaluation.post", batchId, (context, key, version) => persistence.PostRevaluationBatchAsync(context, new FinanceRevaluationActionCommand(batchId, version, null, Guid.NewGuid(), key, Fingerprint(batchId) + Convert.ToBase64String(version)), http.RequestAborted))).WithName("finance.revaluation.post").WithTags("Finance / Revaluation").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.revaluation.post")));
        endpoints.MapPost("/api/v1/finance/revaluation/{batchId:guid}/reverse", async (Guid batchId, ReverseRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.revaluation.reverse", batchId, (context, key, version) => persistence.ReverseRevaluationBatchAsync(context, new FinanceRevaluationActionCommand(batchId, version, request?.Reason, Guid.NewGuid(), key, Fingerprint(request) + Convert.ToBase64String(version)), http.RequestAborted))).WithName("finance.revaluation.reverse").WithTags("Finance / Revaluation").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.revaluation.reverse")));
        endpoints.MapGet("/api/v1/finance/fx-reconciliation", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await Read(http, resolver, auth, "finance.revaluation.reconciliation", companyId, context => persistence.ReconcileFxAsync(context, companyId, http.RequestAborted))).WithName("finance.revaluation.reconciliation").WithTags("Finance / Revaluation").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.revaluation.reconciliation")));
        endpoints.MapGet("/api/v1/finance/unrealized-fx-reconciliation", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await Read(http, resolver, auth, "finance.revaluation.unrealized-reconciliation", companyId, context => persistence.ReconcileUnrealizedFxAsync(context, companyId, http.RequestAborted))).WithName("finance.revaluation.unrealized-reconciliation").WithTags("Finance / Revaluation").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.revaluation.unrealized-reconciliation")));
        endpoints.MapGet("/api/v1/finance/reporting-currency-reconciliation", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp134Persistence persistence) => await Read(http, resolver, auth, "finance.reporting-currency.reconciliation", companyId, context => persistence.ReconcileReportingCurrencyAsync(context, companyId, http.RequestAborted))).WithName("finance.reporting-currency.reconciliation").WithTags("Finance / Reporting Currency").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.reporting-currency.reconciliation")));
        return endpoints;
    }

    private static async Task<IResult> Read<T>(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, string operation, Guid? companyId, Func<FinanceRequestContext, Task<T>> action)
    { var resolved = await Resolve(http, resolver, auth, operation, companyId); if (resolved.Error is not null) return resolved.Error; try { return Results.Ok(await action(resolved.Context!)); } catch (FinanceResourceNotFoundException) { return Problem(404, "finance_resource_not_found", "The requested Finance resource was not found."); } catch { return Problem(503, "finance_unavailable", "Finance data is temporarily unavailable."); } }

    private static async Task<IResult> Preview<T>(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, string operation, Guid? companyId, Func<FinanceRequestContext, Task<T?>> action)
    { try { await http.RequestServices.GetRequiredService<IAntiforgery>().ValidateRequestAsync(http); } catch (AntiforgeryValidationException) { return Problem(403, "antiforgery_failed", "The request could not be validated."); } var resolved = await Resolve(http, resolver, auth, operation, companyId); if (resolved.Error is not null) return resolved.Error; try { var result = await action(resolved.Context!); return result is null ? Problem(404, "tax_source_not_found", "The Finance source could not be evaluated.") : Results.Ok(result); } catch { return Problem(503, "finance_unavailable", "Finance data is temporarily unavailable."); } }

    private static async Task<IResult> ExecuteMutationAsync<T>(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, string operation, Guid? companyId, Func<FinanceRequestContext, string, Task<FinanceOperationResult<T>>> action)
    { try { await http.RequestServices.GetRequiredService<IAntiforgery>().ValidateRequestAsync(http); } catch (AntiforgeryValidationException) { return Problem(403, "antiforgery_failed", "The request could not be validated."); } var key = http.Request.Headers["Idempotency-Key"].FirstOrDefault(); if (!FoundationCorrelation.IsValid(key)) return Problem(400, "idempotency_key_invalid", "A valid Idempotency-Key is required."); var resolved = await Resolve(http, resolver, auth, operation, companyId); if (resolved.Error is not null) return resolved.Error; try { var result = await action(resolved.Context!, key!); return Result(http, result); } catch (Exception exception) when (IsConflict(exception)) { return Problem(409, "finance_conflict", "The Finance operation conflicted with another committed change."); } catch { return Problem(503, "finance_unavailable", "Finance is temporarily unavailable."); } }

    private static async Task<IResult> ExecuteMutationAsync<T>(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, string operation, Guid batchId, Func<FinanceRequestContext, string, byte[], Task<FinanceOperationResult<T>>> action)
    { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, operation, null, (context, key) => action(context, key, version)); }

    private static IResult Result<T>(HttpContext http, FinanceOperationResult<T> result) { if (!result.Succeeded || result.Value is null) return Problem(StatusFor(result.Code), result.Code, "The Finance operation was not completed."); if (result.Value is not null && typeof(T).GetProperty("Version")?.GetValue(result.Value) is byte[] version) http.Response.Headers.ETag = $"\"{Convert.ToBase64String(version)}\""; return Results.Ok(result.Value); }
    private static async Task<(FinanceRequestContext? Context, IResult? Error)> Resolve(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, string operation, Guid? companyId)
    { var foundation = await resolver.ResolveAsync(http, http.RequestAborted); if (!FinanceRequestContext.TryCreate(foundation, out var context) || context is null) return (null, Problem(foundation.SecurityProfile == FoundationSecurityProfile.Anonymous ? 401 : 403, "access_denied", "The operation is not available for this security context.")); var decision = auth.Authorize(context, operation, companyId); return decision.Allowed ? (context, null) : (null, Problem(403, decision.Code, "The requested Finance scope is not authorized.")); }
    private static FinanceTaxAccountingCommand ToTaxCommand(TaxAccountingRequest request, string? key = null) => new(request.CompanyId, request.OpenItemId, request.TaxId, request.TaxableBase, request.SourceLineage, Guid.NewGuid(), key ?? string.Empty, Fingerprint(request));
    private static bool TryIfMatch(HttpContext http, out byte[] version) { version = []; var value = http.Request.Headers.IfMatch.FirstOrDefault()?.Trim('"'); if (string.IsNullOrWhiteSpace(value)) return false; try { version = Convert.FromBase64String(value); return version.Length > 0; } catch (FormatException) { return false; } }
    private static string Fingerprint<T>(T value) => FinanceFingerprint.For(typeof(T).Name, JsonSerializer.Serialize(value));
    private static int StatusFor(string code) => code is "company_scope_denied" or "permission_denied" or "reporting_currency_not_configured" ? 403 : code.Contains("not_found", StringComparison.OrdinalIgnoreCase) ? 404 : code is "concurrency_conflict" or "idempotency_conflict" or "source_effect_exists" ? 409 : 422;
    private static bool IsConflict(Exception exception) => exception.GetType().Name is "DbUpdateException" or "DbUpdateConcurrencyException" || exception.InnerException is not null && IsConflict(exception.InnerException);
    private static IResult Problem(int status, string code, string detail) => Results.Problem(detail, statusCode: status, title: code, extensions: new Dictionary<string, object?> { ["code"] = code });

    public sealed record MonetaryPolicyRequest(Guid CompanyId, Guid? ReportingCurrencyId, int RoundingScale, string RoundingMode, bool RevaluationEnabled, DateOnly EffectiveFrom, DateOnly? EffectiveTo);
    public sealed record TaxAccountingRequest(Guid CompanyId, Guid OpenItemId, Guid TaxId, decimal TaxableBase, string? SourceLineage);
    public sealed record RevaluationRequest(Guid CompanyId, DateOnly AsOfDate, string Scope);
    public sealed record ReverseRequest(string? Reason);
    private sealed class FinanceResourceNotFoundException : Exception { }
}

#pragma warning restore CS1591
