#pragma warning disable CS1591

using System.Text.Json;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Mvc;
using MiniErp.App.BuildingBlocks.Rest;
using MiniErp.App.Modules.Finance;
using MiniErp.Contracts.Modules.Finance;
using MiniErp.Contracts.Modules.Foundation;

namespace MiniErp.Api;

public static class FinanceSettlementEndpoints
{
    public static IEndpointRouteBuilder MapFinanceSettlementEndpoints(this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapGet("/api/v1/finance/ap/open-items", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.ap.list", companyId, null, null, context => persistence.ListOpenItemsAsync(context, FinanceOpenItemKind.Payable, companyId, http.RequestAborted))).WithName("finance.ap.list").WithTags("Finance / Accounts Payable").WithMetadata(Metadata("finance.ap.list"));
        endpoints.MapGet("/api/v1/finance/ap/open-items/{itemId:guid}", async (Guid itemId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.ap.detail", null, "open-item", itemId, context => persistence.GetOpenItemAsync(context, itemId, FinanceOpenItemKind.Payable, http.RequestAborted))).WithName("finance.ap.detail").WithTags("Finance / Accounts Payable").WithMetadata(Metadata("finance.ap.detail"));
        endpoints.MapGet("/api/v1/finance/ap/source-ready", async ([FromQuery] Guid? companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.ap.source-ready", companyId, null, null, context => persistence.ListApSourceReadyAsync(context, companyId, http.RequestAborted))).WithName("finance.ap.source-ready").WithTags("Finance / Accounts Payable").WithMetadata(Metadata("finance.ap.source-ready"));
        endpoints.MapPost("/api/v1/finance/ap/recognize", async (FinanceApRecognizeRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, "finance.ap.recognize", null, "source-evidence", request?.SourceEvidenceId, (context, key) => persistence.RecognizeSupplierInvoiceAsync(context, new FinanceSupplierInvoiceRecognitionCommand(request!.SourceEvidenceId, key, Fingerprint(request)), http.RequestAborted))).WithName("finance.ap.recognize").WithTags("Finance / Accounts Payable").WithMetadata(Metadata("finance.ap.recognize"));
        endpoints.MapGet("/api/v1/finance/ap/aging", async ([FromQuery] Guid companyId, [FromQuery] DateOnly? asOfDate, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.ap.aging", companyId, null, null, context => persistence.GetAgingAsync(context, new FinanceAgingQuery(companyId, asOfDate ?? DateOnly.FromDateTime(DateTime.UtcNow), FinanceOpenItemKind.Payable), http.RequestAborted))).WithName("finance.ap.aging").WithTags("Finance / Accounts Payable").WithMetadata(Metadata("finance.ap.aging"));
        endpoints.MapGet("/api/v1/finance/ap/reconciliation", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.ap.reconciliation", companyId, null, null, context => persistence.GetReconciliationAsync(context, companyId, http.RequestAborted))).WithName("finance.ap.reconciliation").WithTags("Finance / Accounts Payable").WithMetadata(Metadata("finance.ap.reconciliation"));

        endpoints.MapGet("/api/v1/finance/ar/open-items", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.ar.list", companyId, null, null, context => persistence.ListOpenItemsAsync(context, FinanceOpenItemKind.Receivable, companyId, http.RequestAborted))).WithName("finance.ar.list").WithTags("Finance / Accounts Receivable").WithMetadata(Metadata("finance.ar.list"));
        endpoints.MapGet("/api/v1/finance/ar/open-items/{itemId:guid}", async (Guid itemId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.ar.detail", null, "open-item", itemId, context => persistence.GetOpenItemAsync(context, itemId, FinanceOpenItemKind.Receivable, http.RequestAborted))).WithName("finance.ar.detail").WithTags("Finance / Accounts Receivable").WithMetadata(Metadata("finance.ar.detail"));
        endpoints.MapPost("/api/v1/finance/ar/manual", async (FinanceManualReceivableRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, "finance.ar.create", request?.CompanyId, null, null, (context, key) => persistence.CreateManualReceivableAsync(context, new FinanceManualReceivableCommand(request!.CompanyId, request.CustomerId, request.DocumentDate, request.DueDate, request.PaymentTermId, request.CurrencyCode, request.Amount, null, request.ExchangeRate, request.ExchangeRateId, request.ExchangeRateVersionId, request.ExchangeRateVersionNumber, request.Reference, request.Description, Guid.NewGuid(), key, Fingerprint(request)), http.RequestAborted))).WithName("finance.ar.create").WithTags("Finance / Accounts Receivable").WithMetadata(Metadata("finance.ar.create"));
        endpoints.MapGet("/api/v1/finance/ar/aging", async ([FromQuery] Guid companyId, [FromQuery] Guid? customerId, [FromQuery] DateOnly? asOfDate, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.ar.aging", companyId, null, null, context => persistence.GetAgingAsync(context, new FinanceAgingQuery(companyId, asOfDate ?? DateOnly.FromDateTime(DateTime.UtcNow), FinanceOpenItemKind.Receivable, customerId), http.RequestAborted))).WithName("finance.ar.aging").WithTags("Finance / Accounts Receivable").WithMetadata(Metadata("finance.ar.aging"));
        endpoints.MapGet("/api/v1/finance/ar/exposure", async ([FromQuery] Guid companyId, [FromQuery] Guid customerId, [FromQuery] DateOnly? asOfDate, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.ar.exposure", companyId, null, null, context => persistence.GetExposureAsync(context, new FinanceExposureQuery(companyId, customerId, asOfDate ?? DateOnly.FromDateTime(DateTime.UtcNow)), http.RequestAborted))).WithName("finance.ar.exposure").WithTags("Finance / Accounts Receivable").WithMetadata(Metadata("finance.ar.exposure"));
        endpoints.MapGet("/api/v1/finance/ar/reconciliation", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.ar.reconciliation", companyId, null, null, context => persistence.GetReconciliationAsync(context, companyId, http.RequestAborted))).WithName("finance.ar.reconciliation").WithTags("Finance / Accounts Receivable").WithMetadata(Metadata("finance.ar.reconciliation"));

        endpoints.MapGet("/api/v1/finance/payment-methods", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.payment-method.list", companyId, null, null, context => persistence.ListPaymentMethodsAsync(context, companyId, http.RequestAborted))).WithName("finance.payment-method.list").WithTags("Finance / Settlement Configuration").WithMetadata(Metadata("finance.payment-method.list"));
        endpoints.MapPost("/api/v1/finance/payment-methods", async (FinancePaymentMethodRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, "finance.payment-method.create", request?.CompanyId, null, null, (context, key) => persistence.CreatePaymentMethodAsync(context, new FinancePaymentMethodCommand(request!.CompanyId, request.Code, request.EnglishName, request.ArabicName, request.Direction, request.IsManual, request.RequiresReference, request.EffectiveFrom, request.EffectiveTo, Guid.NewGuid(), null, key, Fingerprint(request)), http.RequestAborted))).WithName("finance.payment-method.create").WithTags("Finance / Settlement Configuration").WithMetadata(Metadata("finance.payment-method.create"));
        endpoints.MapPost("/api/v1/finance/payment-methods/{methodId:guid}/edit", async (Guid methodId, FinancePaymentMethodRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, persistence, "finance.payment-method.edit", null, "payment-method", methodId, (context, key) => persistence.EditPaymentMethodAsync(context, new FinancePaymentMethodCommand(request!.CompanyId, request.Code, request.EnglishName, request.ArabicName, request.Direction, request.IsManual, request.RequiresReference, request.EffectiveFrom, request.EffectiveTo, methodId, version, key, Fingerprint(request)), http.RequestAborted)); }).WithName("finance.payment-method.edit").WithTags("Finance / Settlement Configuration").WithMetadata(Metadata("finance.payment-method.edit"));
        endpoints.MapPost("/api/v1/finance/payment-methods/{methodId:guid}/lifecycle", async (Guid methodId, FinanceLifecycleRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, persistence, "finance.payment-method.lifecycle", null, "payment-method", methodId, (context, key) => persistence.SetPaymentMethodLifecycleAsync(context, methodId, request!.CompanyId, request.Lifecycle, version, key, Fingerprint(request), http.RequestAborted)); }).WithName("finance.payment-method.lifecycle").WithTags("Finance / Settlement Configuration").WithMetadata(Metadata("finance.payment-method.lifecycle"));
        endpoints.MapGet("/api/v1/finance/cash-accounts", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.cash-account.list", companyId, null, null, context => persistence.ListCashAccountsAsync(context, companyId, http.RequestAborted))).WithName("finance.cash-account.list").WithTags("Finance / Settlement Configuration").WithMetadata(Metadata("finance.cash-account.list"));
        endpoints.MapPost("/api/v1/finance/cash-accounts", async (FinanceCashAccountRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, "finance.cash-account.create", request?.CompanyId, null, null, (context, key) => persistence.CreateCashAccountAsync(context, new FinanceCashAccountCommand(request!.CompanyId, request.Code, request.EnglishName, request.ArabicName, request.Kind, request.CurrencyCode, request.LinkedAccountId, request.BankReference, request.EffectiveFrom, request.EffectiveTo, Guid.NewGuid(), null, key, Fingerprint(request)), http.RequestAborted))).WithName("finance.cash-account.create").WithTags("Finance / Settlement Configuration").WithMetadata(Metadata("finance.cash-account.create"));
        endpoints.MapPost("/api/v1/finance/cash-accounts/{accountId:guid}/edit", async (Guid accountId, FinanceCashAccountRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, persistence, "finance.cash-account.edit", null, "cash-account", accountId, (context, key) => persistence.EditCashAccountAsync(context, new FinanceCashAccountCommand(request!.CompanyId, request.Code, request.EnglishName, request.ArabicName, request.Kind, request.CurrencyCode, request.LinkedAccountId, request.BankReference, request.EffectiveFrom, request.EffectiveTo, accountId, version, key, Fingerprint(request)), version, http.RequestAborted)); }).WithName("finance.cash-account.edit").WithTags("Finance / Settlement Configuration").WithMetadata(Metadata("finance.cash-account.edit"));
        endpoints.MapPost("/api/v1/finance/cash-accounts/{accountId:guid}/lifecycle", async (Guid accountId, FinanceLifecycleRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence, IFinanceSettlementPersistence settlement) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, settlement, "finance.cash-account.lifecycle", null, "cash-account", accountId, (context, key) => settlement.SetCashAccountLifecycleAsync(context, accountId, request!.CompanyId, request.Lifecycle, version, key, Fingerprint(request), http.RequestAborted)); }).WithName("finance.cash-account.lifecycle").WithTags("Finance / Settlement Configuration").WithMetadata(Metadata("finance.cash-account.lifecycle"));

        MapDocuments(endpoints, FinancePaymentMethodDirection.Payment, "payment"); MapDocuments(endpoints, FinancePaymentMethodDirection.Receipt, "receipt");
        endpoints.MapGet("/api/v1/finance/allocations", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.allocation.list", companyId, null, null, context => persistence.ListAllocationsAsync(context, companyId, http.RequestAborted))).WithName("finance.allocation.list").WithTags("Finance / Settlement").WithMetadata(Metadata("finance.allocation.list"));
        endpoints.MapPost("/api/v1/finance/allocations", async (FinanceAllocationRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, "finance.allocation.create", null, "settlement", request?.SettlementDocumentId, (context, key) => persistence.CreateAllocationAsync(context, new FinanceAllocationCommand(request!.SettlementDocumentId, request.OpenItemId, request.Amount, request.AllocationDate, request.Reason, Guid.NewGuid(), key, Fingerprint(request)), http.RequestAborted))).WithName("finance.allocation.create").WithTags("Finance / Settlement").WithMetadata(Metadata("finance.allocation.create"));
        endpoints.MapPost("/api/v1/finance/allocations/{allocationId:guid}/reverse", async (Guid allocationId, FinanceAllocationReverseRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, persistence, "finance.allocation.reverse", null, "allocation", allocationId, (context, key) => persistence.ReverseAllocationAsync(context, new FinanceAllocationReversalCommand(allocationId, version, request!.Reason, Guid.NewGuid(), key, Fingerprint(request)), http.RequestAborted)); }).WithName("finance.allocation.reverse").WithTags("Finance / Settlement").WithMetadata(Metadata("finance.allocation.reverse"));
        endpoints.MapGet("/api/v1/finance/settlement/reconciliation", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, "finance.settlement.reconciliation", companyId, null, null, context => persistence.GetReconciliationAsync(context, companyId, http.RequestAborted))).WithName("finance.settlement.reconciliation").WithTags("Finance / Settlement").WithMetadata(Metadata("finance.settlement.reconciliation"));
        return endpoints;
    }

    private static void MapDocuments(IEndpointRouteBuilder endpoints, FinancePaymentMethodDirection direction, string segment)
    {
        var plural = segment == "payment" ? "payments" : "receipts"; var tag = segment == "payment" ? "Finance / Supplier Payments" : "Finance / Customer Receipts"; var listOp = $"finance.{segment}.list"; var detailOp = $"finance.{segment}.detail"; var createOp = $"finance.{segment}.create"; var editOp = $"finance.{segment}.edit"; var submitOp = $"finance.{segment}.submit"; var approveOp = $"finance.{segment}.approve"; var rejectOp = $"finance.{segment}.reject"; var postOp = $"finance.{segment}.post"; var reverseOp = $"finance.{segment}.reverse";
        endpoints.MapGet($"/api/v1/finance/{plural}", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, listOp, companyId, null, null, context => persistence.ListSettlementDocumentsAsync(context, new FinanceSettlementQuery(companyId, direction), http.RequestAborted))).WithName(listOp).WithTags(tag).WithMetadata(Metadata(listOp));
        endpoints.MapGet($"/api/v1/finance/{plural}/{{documentId:guid}}", async (Guid documentId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await Read(http, resolver, auth, persistence, detailOp, null, "settlement", documentId, context => persistence.GetSettlementDocumentAsync(context, documentId, direction, http.RequestAborted))).WithName(detailOp).WithTags(tag).WithMetadata(Metadata(detailOp));
        if (segment == "payment")
        {
        endpoints.MapPost("/api/v1/finance/payments", async (FinanceSettlementRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, createOp, request?.CompanyId, null, null, (context, key) => persistence.CreateSettlementDocumentAsync(context, ToCommand(request!, direction, Guid.NewGuid(), key), http.RequestAborted))).WithName(createOp).WithTags(tag).WithMetadata(Metadata(createOp));
        endpoints.MapPost("/api/v1/finance/payments/{documentId:guid}/edit", async (Guid documentId, FinanceSettlementRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, persistence, editOp, null, "settlement", documentId, (context, key) => persistence.EditSettlementDocumentAsync(context, ToCommand(request!, direction, documentId, key), version, http.RequestAborted)); }).WithName(editOp).WithTags(tag).WithMetadata(Metadata(editOp));
        endpoints.MapPost("/api/v1/finance/payments/{documentId:guid}/submit", async (Guid documentId, FinanceActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, submitOp, documentId, FinanceSettlementDocumentStatus.Submitted, request?.Reason, segment, direction)).WithName(submitOp).WithTags(tag).WithMetadata(Metadata(submitOp));
        endpoints.MapPost("/api/v1/finance/payments/{documentId:guid}/approve", async (Guid documentId, FinanceActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, approveOp, documentId, FinanceSettlementDocumentStatus.Approved, request?.Reason, segment, direction)).WithName(approveOp).WithTags(tag).WithMetadata(Metadata(approveOp));
        endpoints.MapPost("/api/v1/finance/payments/{documentId:guid}/reject", async (Guid documentId, FinanceActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, rejectOp, documentId, FinanceSettlementDocumentStatus.Rejected, request?.Reason, segment, direction)).WithName(rejectOp).WithTags(tag).WithMetadata(Metadata(rejectOp));
        endpoints.MapPost("/api/v1/finance/payments/{documentId:guid}/post", async (Guid documentId, FinanceActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, persistence, postOp, null, "settlement", documentId, (context, key) => persistence.PostSettlementDocumentAsync(context, new FinanceSettlementActionCommand(documentId, version, request?.Reason, key, Fingerprint(request), direction), http.RequestAborted)); }).WithName(postOp).WithTags(tag).WithMetadata(Metadata(postOp));
        endpoints.MapPost("/api/v1/finance/payments/{documentId:guid}/reverse", async (Guid documentId, FinanceReverseRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, reverseOp, null, "settlement", documentId, (context, key) => persistence.ReverseSettlementDocumentAsync(context, new FinanceSettlementReversalCommand(documentId, request?.PostingDate ?? DateOnly.FromDateTime(DateTime.UtcNow), request?.Reason ?? string.Empty, Guid.NewGuid(), key, Fingerprint(request), direction), http.RequestAborted))).WithName(reverseOp).WithTags(tag).WithMetadata(Metadata(reverseOp));
        }
        else
        {
        endpoints.MapPost("/api/v1/finance/receipts", async (FinanceSettlementRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, createOp, request?.CompanyId, null, null, (context, key) => persistence.CreateSettlementDocumentAsync(context, ToCommand(request!, direction, Guid.NewGuid(), key), http.RequestAborted))).WithName(createOp).WithTags(tag).WithMetadata(Metadata(createOp));
        endpoints.MapPost("/api/v1/finance/receipts/{documentId:guid}/edit", async (Guid documentId, FinanceSettlementRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, persistence, editOp, null, "settlement", documentId, (context, key) => persistence.EditSettlementDocumentAsync(context, ToCommand(request!, direction, documentId, key), version, http.RequestAborted)); }).WithName(editOp).WithTags(tag).WithMetadata(Metadata(editOp));
        endpoints.MapPost("/api/v1/finance/receipts/{documentId:guid}/submit", async (Guid documentId, FinanceActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, submitOp, documentId, FinanceSettlementDocumentStatus.Submitted, request?.Reason, segment, direction)).WithName(submitOp).WithTags(tag).WithMetadata(Metadata(submitOp));
        endpoints.MapPost("/api/v1/finance/receipts/{documentId:guid}/approve", async (Guid documentId, FinanceActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, approveOp, documentId, FinanceSettlementDocumentStatus.Approved, request?.Reason, segment, direction)).WithName(approveOp).WithTags(tag).WithMetadata(Metadata(approveOp));
        endpoints.MapPost("/api/v1/finance/receipts/{documentId:guid}/reject", async (Guid documentId, FinanceActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, rejectOp, documentId, FinanceSettlementDocumentStatus.Rejected, request?.Reason, segment, direction)).WithName(rejectOp).WithTags(tag).WithMetadata(Metadata(rejectOp));
        endpoints.MapPost("/api/v1/finance/receipts/{documentId:guid}/post", async (Guid documentId, FinanceActionRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, persistence, postOp, null, "settlement", documentId, (context, key) => persistence.PostSettlementDocumentAsync(context, new FinanceSettlementActionCommand(documentId, version, request?.Reason, key, Fingerprint(request), direction), http.RequestAborted)); }).WithName(postOp).WithTags(tag).WithMetadata(Metadata(postOp));
        endpoints.MapPost("/api/v1/finance/receipts/{documentId:guid}/reverse", async (Guid documentId, FinanceReverseRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, persistence, reverseOp, null, "settlement", documentId, (context, key) => persistence.ReverseSettlementDocumentAsync(context, new FinanceSettlementReversalCommand(documentId, request?.PostingDate ?? DateOnly.FromDateTime(DateTime.UtcNow), request?.Reason ?? string.Empty, Guid.NewGuid(), key, Fingerprint(request), direction), http.RequestAborted))).WithName(reverseOp).WithTags(tag).WithMetadata(Metadata(reverseOp));
        }
    }

    private static async Task<IResult> ExecuteMutationAsync(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence, string operation, Guid documentId, FinanceSettlementDocumentStatus target, string? reason, string segment, FinancePaymentMethodDirection direction)
    { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, persistence, operation, null, "settlement", documentId, (context, key) => persistence.TransitionSettlementDocumentAsync(context, new FinanceSettlementActionCommand(documentId, version, reason, key, Fingerprint(new { documentId, reason, segment }), direction), target, http.RequestAborted)); }
    private static FinanceSettlementDocumentCommand ToCommand(FinanceSettlementRequest request, FinancePaymentMethodDirection direction, Guid id, string key) => new(direction, request.CompanyId, direction == FinancePaymentMethodDirection.Payment ? request.PartyId : null, direction == FinancePaymentMethodDirection.Receipt ? request.PartyId : null, request.CashAccountId, request.PaymentMethodId, request.DocumentDate, request.CurrencyCode, request.Amount, null, request.ExchangeRate, request.ExchangeRateId, request.ExchangeRateVersionId, request.ExchangeRateVersionNumber, request.ExternalReference, request.Description, id, key, Fingerprint(request));
    private static FoundationOperationMetadata Metadata(string operation) => new(FoundationOperationCatalog.GetRequired(operation));
    private static async Task<IResult> Read<T>(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence, string operation, Guid? companyId, string? resource, Guid? resourceId, Func<FinanceRequestContext, Task<T>> action) { var resolved = await Resolve(http, resolver, auth, persistence, operation, companyId, resource, resourceId); if (resolved.Error is not null) return resolved.Error; try { var value = await action(resolved.Context!); return value is null ? Problem(404, "finance_resource_not_found", "The requested Finance resource was not found.") : Results.Ok(value); } catch { return Problem(503, "finance_unavailable", "Finance data is temporarily unavailable."); } }
    private static async Task<IResult> ExecuteMutationAsync<T>(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence, string operation, Guid? companyId, string? resource, Guid? resourceId, Func<FinanceRequestContext, string, Task<FinanceOperationResult<T>>> action) { try { await http.RequestServices.GetRequiredService<IAntiforgery>().ValidateRequestAsync(http); } catch (AntiforgeryValidationException) { return Problem(403, "antiforgery_failed", "The request could not be validated."); } var key = http.Request.Headers["Idempotency-Key"].FirstOrDefault(); if (!FoundationCorrelation.IsValid(key)) return Problem(400, "idempotency_key_invalid", "A valid Idempotency-Key is required."); var resolved = await Resolve(http, resolver, auth, persistence, operation, companyId, resource, resourceId); if (resolved.Error is not null) return resolved.Error; FinanceOperationResult<T> result; try { result = await action(resolved.Context!, key!); } catch (Exception exception) when (IsConflict(exception)) { return Problem(409, "finance_conflict", "The Finance operation conflicted with another committed change."); } catch { return Problem(503, "finance_unavailable", "Finance is temporarily unavailable."); } if (!result.Succeeded || result.Value is null) return Problem(StatusFor(result.Code), result.Code, "The Finance operation was not completed."); if (TryVersion(result.Value, out var version)) http.Response.Headers.ETag = $"\"{Convert.ToBase64String(version)}\""; return Results.Ok(result.Value); }
    private static async Task<(FinanceRequestContext? Context, IResult? Error)> Resolve(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceSettlementPersistence persistence, string operation, Guid? companyId, string? resource, Guid? resourceId) { var foundation = await resolver.ResolveAsync(http, http.RequestAborted); if (!FinanceRequestContext.TryCreate(foundation, out var context) || context is null) return (null, Problem(foundation.SecurityProfile == FoundationSecurityProfile.Anonymous ? 401 : 403, "access_denied", "The operation is not available for this security context.")); var resolvedCompany = companyId; if (resource is not null) { if (resourceId is not { } id || id == Guid.Empty) return (null, Problem(404, "finance_resource_not_found", "The requested Finance resource was not found.")); resolvedCompany = await persistence.ResolveCompanyIdAsync(context, resource, id, http.RequestAborted); if (resolvedCompany is null) return (null, Problem(404, "finance_resource_not_found", "The requested Finance resource was not found.")); } var decision = auth.Authorize(context, operation, resolvedCompany); return decision.Allowed ? (context, null) : (null, Problem(403, decision.Code, "The requested Finance scope is not authorized.")); }
    private static bool TryIfMatch(HttpContext http, out byte[] version) { version = []; var value = http.Request.Headers.IfMatch.FirstOrDefault()?.Trim('"'); if (string.IsNullOrWhiteSpace(value)) return false; try { version = Convert.FromBase64String(value); return version.Length > 0; } catch (FormatException) { return false; } }
    private static bool TryVersion<T>(T value, out byte[] version) { version = []; var property = typeof(T).GetProperty("Version"); if (property?.GetValue(value) is not byte[] candidate) return false; version = candidate; return true; }
    private static int StatusFor(string code) => code is "company_scope_denied" or "party_scope_denied" or "permission_denied" ? 403 : code.Contains("not_found", StringComparison.OrdinalIgnoreCase) ? 404 : code is "concurrency_conflict" or "idempotency_conflict" or "source_effect_exists" ? 409 : 422;
    private static bool IsConflict(Exception exception) => exception.GetType().Name is "DbUpdateException" or "DbUpdateConcurrencyException" || exception.InnerException is not null && IsConflict(exception.InnerException);
    private static string Fingerprint<T>(T value) => FinanceFingerprint.For(typeof(T).Name, JsonSerializer.Serialize(value));
    private static IResult Problem(int status, string code, string detail) => Results.Problem(detail, statusCode: status, title: code, extensions: new Dictionary<string, object?> { ["code"] = code });

    public sealed record FinanceApRecognizeRequest(Guid SourceEvidenceId);
    public sealed record FinanceManualReceivableRequest(Guid CompanyId, Guid CustomerId, DateOnly DocumentDate, DateOnly? DueDate, Guid? PaymentTermId, string CurrencyCode, decimal Amount, decimal? ExchangeRate, Guid? ExchangeRateId, Guid? ExchangeRateVersionId, int? ExchangeRateVersionNumber, string? Reference, string? Description);
    public sealed record FinancePaymentMethodRequest(Guid CompanyId, string Code, string EnglishName, string? ArabicName, FinancePaymentMethodDirection Direction, bool IsManual, bool RequiresReference, DateOnly EffectiveFrom, DateOnly? EffectiveTo);
    public sealed record FinanceCashAccountRequest(Guid CompanyId, string Code, string EnglishName, string? ArabicName, FinanceCashAccountKind Kind, string CurrencyCode, Guid LinkedAccountId, string? BankReference, DateOnly EffectiveFrom, DateOnly? EffectiveTo);
    public sealed record FinanceLifecycleRequest(Guid CompanyId, FinancePaymentMethodLifecycle Lifecycle);
    public sealed record FinanceSettlementRequest(Guid CompanyId, Guid PartyId, Guid CashAccountId, Guid PaymentMethodId, DateOnly DocumentDate, string CurrencyCode, decimal Amount, decimal? ExchangeRate, Guid? ExchangeRateId, Guid? ExchangeRateVersionId, int? ExchangeRateVersionNumber, string? ExternalReference, string? Description);
    public sealed record FinanceActionRequest(string? Reason);
    public sealed record FinanceReverseRequest(DateOnly? PostingDate, string? Reason);
    public sealed record FinanceAllocationRequest(Guid SettlementDocumentId, Guid OpenItemId, decimal Amount, DateOnly AllocationDate, string? Reason);
    public sealed record FinanceAllocationReverseRequest(string Reason);
}

#pragma warning restore CS1591
