#pragma warning disable CS1591

using System.Text.Json;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Mvc;
using MiniErp.App.BuildingBlocks.Rest;
using MiniErp.App.Modules.Finance;
using MiniErp.Contracts.Modules.Finance;
using MiniErp.Contracts.Modules.Foundation;

namespace MiniErp.Api;

public static class FinanceEndpoints
{
    public static IEndpointRouteBuilder MapFinanceEndpoints(this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapGet("/api/v1/finance/companies", async (HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceCompanyProvider companies) =>
            await Read(http, resolver, auth, "finance.company.list", null, context => Task.FromResult<object?>(companies.List(context.TenantId)))).WithName("finance.company.list").WithTags("Finance").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.company.list")));

        endpoints.MapGet("/api/v1/finance/accounts", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) =>
            await Read(http, resolver, auth, "finance.account.list", companyId, context => persistence.ListAccountsAsync(context, companyId, http.RequestAborted))).WithName("finance.account.list").WithTags("Finance / Chart of Accounts").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.account.list")));
        endpoints.MapPost("/api/v1/finance/accounts", async (FinanceAccountWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.account.create", request?.CompanyId, (context, key) => persistence.CreateAccountAsync(context, new FinanceAccountCommand(request!.CompanyId, request.Code, request.EnglishName, request.ArabicName, request.ParentAccountId, request.AccountType, request.IsPostingAccount, request.CurrencyBehavior, request.EffectiveFrom, request.EffectiveTo, Guid.NewGuid(), null, key, Fingerprint(request)), http.RequestAborted))).WithName("finance.account.create").WithTags("Finance / Chart of Accounts").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.account.create")));
        endpoints.MapPost("/api/v1/finance/accounts/{accountId:guid}/edit", async (Guid accountId, FinanceAccountWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, "finance.account.edit", null, (context, key) => persistence.EditAccountAsync(context, new FinanceAccountCommand(request!.CompanyId, request.Code, request.EnglishName, request.ArabicName, request.ParentAccountId, request.AccountType, request.IsPostingAccount, request.CurrencyBehavior, request.EffectiveFrom, request.EffectiveTo, accountId, version, key, Fingerprint(request) + Convert.ToBase64String(version)), http.RequestAborted), FinanceResourceType.Account, accountId); }).WithName("finance.account.edit").WithTags("Finance / Chart of Accounts").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.account.edit")));
        endpoints.MapPost("/api/v1/finance/accounts/{accountId:guid}/lifecycle", async (Guid accountId, FinanceAccountLifecycleWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, "finance.account.lifecycle", null, (context, key) => persistence.SetAccountLifecycleAsync(context, accountId, request!.CompanyId, request.Lifecycle, version, key, Fingerprint(request) + Convert.ToBase64String(version), http.RequestAborted), FinanceResourceType.Account, accountId); }).WithName("finance.account.lifecycle").WithTags("Finance / Chart of Accounts").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.account.lifecycle")));

        endpoints.MapGet("/api/v1/finance/calendars", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await Read(http, resolver, auth, "finance.calendar.list", companyId, context => persistence.ListCalendarsAsync(context, companyId, http.RequestAborted))).WithName("finance.calendar.list").WithTags("Finance / Fiscal Calendar").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.calendar.list")));
        endpoints.MapPost("/api/v1/finance/calendars", async (FinanceCalendarWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.calendar.create", request?.CompanyId, (context, key) => persistence.CreateCalendarAsync(context, new FinanceFiscalCalendarCommand(request!.CompanyId, request.Name, Guid.NewGuid(), key, Fingerprint(request)), http.RequestAborted))).WithName("finance.calendar.create").WithTags("Finance / Fiscal Calendar").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.calendar.create")));
        endpoints.MapGet("/api/v1/finance/calendars/{calendarId:guid}/years", async (Guid calendarId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await Read(http, resolver, auth, "finance.year.list", null, context => persistence.ListYearsAsync(context, calendarId, http.RequestAborted), FinanceResourceType.Calendar, calendarId)).WithName("finance.year.list").WithTags("Finance / Fiscal Calendar").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.year.list")));
        endpoints.MapPost("/api/v1/finance/years", async (FinanceYearWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.year.create", null, (context, key) => persistence.CreateYearAsync(context, new FinanceFiscalYearCommand(request!.CalendarId, request.YearNumber, request.StartDate, request.EndDate, Guid.NewGuid(), key, Fingerprint(request)), http.RequestAborted), FinanceResourceType.Calendar, request?.CalendarId)).WithName("finance.year.create").WithTags("Finance / Fiscal Calendar").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.year.create")));
        endpoints.MapGet("/api/v1/finance/years/{yearId:guid}/periods", async (Guid yearId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await Read(http, resolver, auth, "finance.period.list", null, context => persistence.ListPeriodsAsync(context, yearId, http.RequestAborted), FinanceResourceType.FiscalYear, yearId)).WithName("finance.period.list").WithTags("Finance / Fiscal Calendar").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.period.list")));
        endpoints.MapPost("/api/v1/finance/periods", async (FinancePeriodWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.period.create", null, (context, key) => persistence.CreatePeriodAsync(context, new FinanceFiscalPeriodCommand(request!.FiscalYearId, request.Sequence, request.Code, request.EnglishName, request.ArabicName, request.StartDate, request.EndDate, Guid.NewGuid(), key, Fingerprint(request)), http.RequestAborted), FinanceResourceType.FiscalYear, request?.FiscalYearId)).WithName("finance.period.create").WithTags("Finance / Fiscal Calendar").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.period.create")));
        endpoints.MapPost("/api/v1/finance/periods/{periodId:guid}/state", async (Guid periodId, FinancePeriodStateWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, "finance.period.state", null, (context, key) => persistence.SetPeriodStateAsync(context, new FinancePeriodStateCommand(periodId, request?.State ?? FinanceFiscalPeriodState.Draft, request?.Reason, version, key, Fingerprint(request) + Convert.ToBase64String(version)), http.RequestAborted), FinanceResourceType.FiscalPeriod, periodId); }).WithName("finance.period.state").WithTags("Finance / Fiscal Calendar").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.period.state")));

        endpoints.MapGet("/api/v1/finance/cost-centers", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await Read(http, resolver, auth, "finance.cost-center.list", companyId, context => persistence.ListCostCentersAsync(context, companyId, http.RequestAborted))).WithName("finance.cost-center.list").WithTags("Finance / Dimensions").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.cost-center.list")));
        endpoints.MapPost("/api/v1/finance/cost-centers", async (FinanceCostCenterWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.cost-center.create", request?.CompanyId, (context, key) => persistence.CreateCostCenterAsync(context, new FinanceCostCenterCommand(request!.CompanyId, request.Code, request.EnglishName, request.ArabicName, request.EffectiveFrom, request.EffectiveTo, Guid.NewGuid(), key, Fingerprint(request)), http.RequestAborted))).WithName("finance.cost-center.create").WithTags("Finance / Dimensions").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.cost-center.create")));
        endpoints.MapGet("/api/v1/finance/posting-rules", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await Read(http, resolver, auth, "finance.posting-rule.list", companyId, context => persistence.ListPostingRulesAsync(context, companyId, http.RequestAborted))).WithName("finance.posting-rule.list").WithTags("Finance / Posting Rules").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.posting-rule.list")));
        endpoints.MapPost("/api/v1/finance/posting-rules", async (FinancePostingRuleWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.posting-rule.create", request?.CompanyId, (context, key) => persistence.CreatePostingRuleAsync(context, new FinancePostingRuleCommand(request!.CompanyId, request.SourceContract, request.SourceEvent, request.DebitAccountId, request.CreditAccountId, request.CostCenterRequired, request.EffectiveFrom, request.EffectiveTo, Guid.NewGuid(), key, Fingerprint(request)), http.RequestAborted))).WithName("finance.posting-rule.create").WithTags("Finance / Posting Rules").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.posting-rule.create")));
        endpoints.MapPost("/api/v1/finance/posting-rules/{ruleId:guid}/lifecycle", async (Guid ruleId, FinancePostingRuleLifecycleWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => { if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, "finance.posting-rule.lifecycle", null, (context, key) => persistence.SetPostingRuleLifecycleAsync(context, ruleId, request!.CompanyId, request.Lifecycle, version, key, Fingerprint(request) + Convert.ToBase64String(version), http.RequestAborted), FinanceResourceType.PostingRule, ruleId); }).WithName("finance.posting-rule.lifecycle").WithTags("Finance / Posting Rules").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.posting-rule.lifecycle")));

        endpoints.MapGet("/api/v1/finance/journals", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await Read(http, resolver, auth, "finance.journal.list", companyId, context => persistence.ListJournalsAsync(context, companyId, http.RequestAborted))).WithName("finance.journal.list").WithTags("Finance / Journals").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.journal.list")));
        endpoints.MapPost("/api/v1/finance/journals", async (FinanceJournalWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.journal.create", request?.CompanyId, (context, key) => persistence.CreateJournalAsync(context, ToCommand(request!, key), http.RequestAborted))).WithName("finance.journal.create").WithTags("Finance / Journals").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.journal.create")));
        endpoints.MapPost("/api/v1/finance/journals/{journalId:guid}/submit", async (Guid journalId, FinanceActionWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, journalId, request, resolver, auth, persistence, "finance.journal.submit", FinanceJournalStatus.Submitted, FinanceResourceType.Journal)).WithName("finance.journal.submit").WithTags("Finance / Journals").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.journal.submit")));
        endpoints.MapPost("/api/v1/finance/journals/{journalId:guid}/approve", async (Guid journalId, FinanceActionWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, journalId, request, resolver, auth, persistence, "finance.journal.approve", FinanceJournalStatus.Approved, FinanceResourceType.Journal)).WithName("finance.journal.approve").WithTags("Finance / Journals").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.journal.approve")));
        endpoints.MapPost("/api/v1/finance/journals/{journalId:guid}/reject", async (Guid journalId, FinanceActionWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, journalId, request, resolver, auth, persistence, "finance.journal.reject", FinanceJournalStatus.Rejected, FinanceResourceType.Journal)).WithName("finance.journal.reject").WithTags("Finance / Journals").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.journal.reject")));
        endpoints.MapPost("/api/v1/finance/journals/{journalId:guid}/cancel", async (Guid journalId, FinanceActionWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, journalId, request, resolver, auth, persistence, "finance.journal.cancel", FinanceJournalStatus.Cancelled, FinanceResourceType.Journal)).WithName("finance.journal.cancel").WithTags("Finance / Journals").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.journal.cancel")));
        endpoints.MapPost("/api/v1/finance/journals/{journalId:guid}/post", async (Guid journalId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, journalId, resolver, auth, persistence, FinanceResourceType.Journal)).WithName("finance.journal.post").WithTags("Finance / Journals").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.journal.post")));
        endpoints.MapPost("/api/v1/finance/journals/{journalId:guid}/reverse", async (Guid journalId, FinanceReverseWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.journal.reverse", null, (context, key) => persistence.ReverseJournalAsync(context, new FinanceReversalCommand(journalId, request?.PostingDate ?? DateOnly.FromDateTime(DateTime.UtcNow), request?.Reason ?? string.Empty, Guid.NewGuid(), key, Fingerprint(request)), http.RequestAborted), FinanceResourceType.Journal, journalId)).WithName("finance.journal.reverse").WithTags("Finance / Journals").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.journal.reverse")));

        endpoints.MapGet("/api/v1/finance/gl", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await Read(http, resolver, auth, "finance.gl.inquiry", companyId, context => persistence.QueryGlAsync(context, new FinanceGlQuery(companyId), http.RequestAborted))).WithName("finance.gl.inquiry").WithTags("Finance / GL Inquiry").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.gl.inquiry")));
        endpoints.MapGet("/api/v1/finance/inventory-handoffs", async ([FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await Read(http, resolver, auth, "finance.handoff.list", companyId, context => persistence.ListHandoffsAsync(context, companyId, http.RequestAborted))).WithName("finance.handoff.list").WithTags("Finance / Inventory Handoff").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.handoff.list")));
        endpoints.MapPost("/api/v1/finance/inventory-handoffs/{handoffId:guid}/process", async (Guid handoffId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.handoff.process", null, (context, key) => persistence.ProcessHandoffAsync(context, new FinanceHandoffProcessCommand(handoffId, key, Fingerprint(handoffId)), http.RequestAborted), FinanceResourceType.InventoryHandoff, handoffId)).WithName("finance.handoff.process").WithTags("Finance / Inventory Handoff").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.handoff.process")));

        endpoints.MapFinanceSettlementEndpoints();
        endpoints.MapFinanceMesp134Endpoints();
        endpoints.MapFinanceMesp135Endpoints();
        return endpoints;
    }

    private static async Task<IResult> ExecuteMutationAsync(HttpContext http, Guid journalId, FinanceActionWriteRequest? request, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence, string operation, FinanceJournalStatus target, FinanceResourceType resourceType)
    {
        if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required.");
        return await ExecuteMutationAsync(http, resolver, auth, operation, null, (context, key) => persistence.TransitionJournalAsync(context, new FinanceJournalActionCommand(journalId, version, request?.Reason, key, Fingerprint(request) + Convert.ToBase64String(version)), target, http.RequestAborted), resourceType, journalId);
    }

    private static async Task<IResult> ExecuteMutationAsync(HttpContext http, Guid journalId, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinancePersistence persistence, FinanceResourceType resourceType)
    {
        if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required.");
        return await ExecuteMutationAsync(http, resolver, auth, "finance.journal.post", null, (context, key) => persistence.PostJournalAsync(context, new FinanceJournalActionCommand(journalId, version, null, key, Fingerprint(journalId) + Convert.ToBase64String(version)), http.RequestAborted), resourceType, journalId);
    }

    private static async Task<IResult> Read<T>(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService authorization, string operation, Guid? companyId, Func<FinanceRequestContext, Task<T>> action, FinanceResourceType? resourceType = null, Guid? resourceId = null)
    {
        var resolved = await Resolve(http, resolver, authorization, operation, companyId, resourceType, resourceId); if (resolved.Error is not null) return resolved.Error; try { return Results.Ok(await action(resolved.Context!)); } catch (Exception) { return Problem(503, "finance_unavailable", "Finance data is temporarily unavailable."); }
    }

    private static async Task<IResult> ExecuteMutationAsync<T>(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService authorization, string operation, Guid? companyId, Func<FinanceRequestContext, string, Task<FinanceOperationResult<T>>> action, FinanceResourceType? resourceType = null, Guid? resourceId = null)
    {
        try { await http.RequestServices.GetRequiredService<IAntiforgery>().ValidateRequestAsync(http); } catch (AntiforgeryValidationException) { return Problem(403, "antiforgery_failed", "The request could not be validated."); }
        var key = http.Request.Headers["Idempotency-Key"].FirstOrDefault(); if (!FoundationCorrelation.IsValid(key)) return Problem(400, "idempotency_key_invalid", "A valid Idempotency-Key is required.");
        var resolved = await Resolve(http, resolver, authorization, operation, companyId, resourceType, resourceId); if (resolved.Error is not null) return resolved.Error; FinanceOperationResult<T> result; try { result = await action(resolved.Context!, key!); } catch (Exception exception) when (IsFinanceConflict(exception)) { return Problem(409, "finance_conflict", "The Finance operation conflicted with another committed change."); } catch (Exception) { return Problem(503, "finance_unavailable", "Finance is temporarily unavailable."); }
        if (!result.Succeeded || result.Value is null) return Problem(StatusFor(result.Code), result.Code, "The Finance operation was not completed."); if (TryVersion(result.Value, out var version)) http.Response.Headers.ETag = $"\"{Convert.ToBase64String(version)}\""; return Results.Ok(result.Value);
    }

    private static async Task<(FinanceRequestContext? Context, IResult? Error)> Resolve(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService authorization, string operation, Guid? companyId, FinanceResourceType? resourceType, Guid? resourceId)
    {
        var foundation = await resolver.ResolveAsync(http, http.RequestAborted); if (!FinanceRequestContext.TryCreate(foundation, out var context) || context is null) return (null, Problem(foundation.SecurityProfile == FoundationSecurityProfile.Anonymous ? 401 : 403, "access_denied", "The operation is not available for this security context."));
        var resolvedCompanyId = companyId;
        if (resourceType is { } type)
        {
            if (resourceId is not { } id || id == Guid.Empty) return (null, Problem(404, "finance_resource_not_found", "The requested Finance resource was not found."));
            resolvedCompanyId = await http.RequestServices.GetRequiredService<IFinancePersistence>().ResolveCompanyIdAsync(context, type, id, http.RequestAborted);
            if (resolvedCompanyId is null) return (null, Problem(404, "finance_resource_not_found", "The requested Finance resource was not found."));
        }
        var decision = authorization.Authorize(context, operation, resolvedCompanyId); return decision.Allowed ? (context, null) : (null, Problem(403, decision.Code, "The requested Finance scope is not authorized."));
    }

    private static FinanceJournalCommand ToCommand(FinanceJournalWriteRequest request, string key) => new(request.CompanyId, request.JournalDate, request.PostingDate, request.TransactionCurrencyCode, request.ExchangeRate, request.ExchangeRateId, request.ExchangeRateVersionId, request.ExchangeRateVersionNumber, "manual-journal.v1", "manual", null, null, null, request.Description, request.Lines.Select(line => new FinanceJournalLineCommand(line.AccountId, line.Debit, line.Credit, null, null, line.CostCenterId, line.Description)).ToArray(), Guid.NewGuid(), key, Fingerprint(request), FinanceJournalAmountAuthority.ManualTransactionCurrency, FinanceApprovalRequirement.Required);
    private static bool TryIfMatch(HttpContext http, out byte[] version) { version = []; var value = http.Request.Headers.IfMatch.FirstOrDefault()?.Trim('"'); if (string.IsNullOrWhiteSpace(value)) return false; try { version = Convert.FromBase64String(value); return version.Length > 0; } catch (FormatException) { return false; } }
    private static bool TryVersion<T>(T value, out byte[] version) { version = []; var property = typeof(T).GetProperty("Version"); if (property?.GetValue(value) is not byte[] candidate) return false; version = candidate; return true; }
    private static int StatusFor(string code) => code is "company_scope_denied" or "permission_denied" or "approval_policy_not_configured" ? 403 : code.Contains("not_found", StringComparison.OrdinalIgnoreCase) ? 404 : code is "concurrency_conflict" or "idempotency_conflict" or "source_effect_exists" ? 409 : 422;
    private static bool IsFinanceConflict(Exception exception) => exception.GetType().Name is "DbUpdateException" or "DbUpdateConcurrencyException" || exception.InnerException is not null && IsFinanceConflict(exception.InnerException);
    private static string Fingerprint<T>(T value) => FinanceFingerprint.For(typeof(T).Name, JsonSerializer.Serialize(value));
    private static IResult Problem(int status, string code, string detail) => Results.Problem(detail, statusCode: status, title: code, extensions: new Dictionary<string, object?> { ["code"] = code });

    public sealed record FinanceAccountWriteRequest(Guid CompanyId, string Code, string EnglishName, string? ArabicName, Guid? ParentAccountId, FinanceAccountType AccountType, bool IsPostingAccount, FinanceCurrencyBehavior CurrencyBehavior, DateOnly EffectiveFrom, DateOnly? EffectiveTo);
    public sealed record FinanceAccountLifecycleWriteRequest(Guid CompanyId, FinanceAccountLifecycle Lifecycle);
    public sealed record FinanceCalendarWriteRequest(Guid CompanyId, string Name);
    public sealed record FinanceYearWriteRequest(Guid CalendarId, int YearNumber, DateOnly StartDate, DateOnly EndDate);
    public sealed record FinancePeriodWriteRequest(Guid FiscalYearId, int Sequence, string Code, string? EnglishName, string? ArabicName, DateOnly StartDate, DateOnly EndDate);
    public sealed record FinancePeriodStateWriteRequest(FinanceFiscalPeriodState State, string? Reason);
    public sealed record FinanceCostCenterWriteRequest(Guid CompanyId, string Code, string EnglishName, string? ArabicName, DateOnly EffectiveFrom, DateOnly? EffectiveTo);
    public sealed record FinancePostingRuleWriteRequest(Guid CompanyId, string SourceContract, string SourceEvent, Guid DebitAccountId, Guid CreditAccountId, bool CostCenterRequired, DateOnly EffectiveFrom, DateOnly? EffectiveTo);
    public sealed record FinancePostingRuleLifecycleWriteRequest(Guid CompanyId, FinancePostingRuleLifecycle Lifecycle);
    public sealed record FinanceJournalLineWriteRequest(Guid AccountId, decimal Debit, decimal Credit, Guid? CostCenterId, string? Description);
    public sealed record FinanceJournalWriteRequest(Guid CompanyId, DateOnly JournalDate, DateOnly PostingDate, string? TransactionCurrencyCode, decimal? ExchangeRate, Guid? ExchangeRateId, Guid? ExchangeRateVersionId, int? ExchangeRateVersionNumber, string Description, IReadOnlyList<FinanceJournalLineWriteRequest> Lines);
    public sealed record FinanceActionWriteRequest(string? Reason);
    public sealed record FinanceReverseWriteRequest(DateOnly? PostingDate, string? Reason);
}

#pragma warning restore CS1591
