#pragma warning disable CS1591

using System.Text;
using System.Text.Json;
using System.Globalization;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Mvc;
using MiniErp.App.BuildingBlocks.Rest;
using MiniErp.App.Modules.Finance;
using MiniErp.Contracts.Modules.Finance;
using MiniErp.Contracts.Modules.Foundation;

namespace MiniErp.Api;

public static class FinanceMesp135Endpoints
{
    public static IEndpointRouteBuilder MapFinanceMesp135Endpoints(this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapGet("/api/v1/finance/periods/{periodId:guid}/close-readiness", async (Guid periodId, [FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Read(http, resolver, auth, "finance.close.readiness", companyId, context => persistence.EvaluateCloseReadinessAsync(context, new FinanceCloseReadinessQuery(companyId, periodId), http.RequestAborted))).WithName("finance.close.readiness").WithTags("Finance / Close").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.close.readiness")));
        endpoints.MapGet("/api/v1/finance/period-close-runs", async ([FromQuery] Guid companyId, [FromQuery] Guid? periodId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Read(http, resolver, auth, "finance.close.runs", companyId, context => persistence.ListPeriodCloseRunsAsync(context, companyId, periodId, http.RequestAborted))).WithName("finance.close.runs").WithTags("Finance / Close").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.close.runs")));
        endpoints.MapGet("/api/v1/finance/periods/{periodId:guid}/close-history", async (Guid periodId, [FromQuery] Guid companyId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Read(http, resolver, auth, "finance.close.history", companyId, context => persistence.ListPeriodHistoryAsync(context, companyId, periodId, http.RequestAborted))).WithName("finance.close.history").WithTags("Finance / Close").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.close.history")));
        endpoints.MapPost("/api/v1/finance/periods/{periodId:guid}/close", async (Guid periodId, FinanceCloseWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.close.period", request?.CompanyId, request, periodId, persistence, false)).WithName("finance.close.period").WithTags("Finance / Close").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.close.period")));
        endpoints.MapPost("/api/v1/finance/periods/{periodId:guid}/reopen", async (Guid periodId, FinanceCloseWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.close.reopen", request?.CompanyId, request, periodId, persistence, true)).WithName("finance.close.reopen").WithTags("Finance / Close").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.close.reopen")));
        endpoints.MapGet("/api/v1/finance/year-end", async ([FromQuery] Guid companyId, [FromQuery] Guid? fiscalYearId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Read(http, resolver, auth, "finance.year-end.list", companyId, context => persistence.ListYearEndRunsAsync(context, companyId, fiscalYearId, http.RequestAborted))).WithName("finance.year-end.list").WithTags("Finance / Close").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.year-end.list")));
        endpoints.MapPost("/api/v1/finance/year-end/calculate", async (FinanceYearEndWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.year-end.calculate", request?.CompanyId, (context, key) => persistence.CalculateYearEndAsync(context, new FinanceYearEndCommand(request!.CompanyId, request.FiscalYearId, request.AsOfDate, request.Reason ?? string.Empty, Guid.NewGuid(), key, Fingerprint(request)), http.RequestAborted))).WithName("finance.year-end.calculate").WithTags("Finance / Close").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.year-end.calculate")));
        endpoints.MapPost("/api/v1/finance/year-end/{runId:guid}/post", async (Guid runId, FinanceActionWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.year-end.post", request?.CompanyId, (context, key, version) => persistence.PostYearEndAsync(context, new FinanceYearEndActionCommand(request!.CompanyId, runId, version, request.Reason ?? string.Empty, Guid.NewGuid(), key, Fingerprint(request) + Convert.ToBase64String(version)), http.RequestAborted))).WithName("finance.year-end.post").WithTags("Finance / Close").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.year-end.post")));
        endpoints.MapPost("/api/v1/finance/year-end/{runId:guid}/reverse", async (Guid runId, FinanceActionWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.year-end.reverse", request?.CompanyId, (context, key, version) => persistence.ReverseYearEndAsync(context, new FinanceYearEndActionCommand(request!.CompanyId, runId, version, request.Reason ?? string.Empty, Guid.NewGuid(), key, Fingerprint(request) + Convert.ToBase64String(version)), http.RequestAborted))).WithName("finance.year-end.reverse").WithTags("Finance / Close").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.year-end.reverse")));
        endpoints.MapPost("/api/v1/finance/journals/{journalId:guid}/correction", async (Guid journalId, FinanceCorrectionWriteRequest? request, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await ExecuteMutationAsync(http, resolver, auth, "finance.correction.create", request?.CompanyId, (context, key, version) => persistence.CorrectJournalAsync(context, new FinanceCorrectionCommand(request!.CompanyId, journalId, request.PostingDate, version, request.Reason ?? string.Empty, Guid.NewGuid(), key, Fingerprint(request) + Convert.ToBase64String(version)), http.RequestAborted))).WithName("finance.correction.create").WithTags("Finance / Corrections").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.correction.create")));
        endpoints.MapGet("/api/v1/finance/reconciliation/close", async ([FromQuery] Guid companyId, [FromQuery] DateOnly asOfDate, [FromQuery] Guid? periodId, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Read(http, resolver, auth, "finance.reconciliation.close", companyId, context => persistence.QueryReconciliationAsync(context, companyId, asOfDate == default ? DateOnly.FromDateTime(DateTime.UtcNow) : asOfDate, periodId, http.RequestAborted))).WithName("finance.reconciliation.close").WithTags("Finance / Reconciliation").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.reconciliation.close")));
        endpoints.MapGet("/api/v1/finance/reports/trial-balance", async ([FromQuery] Guid companyId, [FromQuery] DateOnly asOfDate, [FromQuery] Guid? fiscalPeriodId, [FromQuery] Guid? accountId, [FromQuery] Guid? costCenterId, [FromQuery] string? accountFrom, [FromQuery] string? accountTo, [FromQuery] string? presentationCurrencyCode, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Read(http, resolver, auth, "finance.report.trial-balance", companyId, context => persistence.QueryTrialBalanceAsync(context, new FinanceTrialBalanceQuery(companyId, asOfDate, fiscalPeriodId, accountId, costCenterId, accountFrom, accountTo, presentationCurrencyCode), http.RequestAborted))).WithName("finance.report.trial-balance").WithTags("Finance / Reports").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.report.trial-balance")));
        endpoints.MapGet("/api/v1/finance/reports/trial-balance/export", async ([FromQuery] Guid companyId, [FromQuery] DateOnly asOfDate, [FromQuery] Guid? fiscalPeriodId, [FromQuery] Guid? accountId, [FromQuery] Guid? costCenterId, [FromQuery] string? accountFrom, [FromQuery] string? accountTo, [FromQuery] string? presentationCurrencyCode, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Export(http, resolver, auth, "finance.report.trial-balance.export", companyId, async context => { var report = await persistence.QueryTrialBalanceAsync(context, new FinanceTrialBalanceQuery(companyId, asOfDate, fiscalPeriodId, accountId, costCenterId, accountFrom, accountTo, presentationCurrencyCode), http.RequestAborted); return Csv(report.Rows.Select(row => new[] { row.AccountCode, row.AccountName, row.AccountType.ToString(), Amount(row.OpeningBalance), Amount(row.PeriodDebit), Amount(row.PeriodCredit), Amount(row.ClosingBalance) }), ["Account", "Name", "Type", "Opening", "Debit", "Credit", "Closing"]); })).WithName("finance.report.trial-balance.export").WithTags("Finance / Reports").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.report.trial-balance.export")));
        endpoints.MapGet("/api/v1/finance/reports/general-ledger", async ([FromQuery] Guid companyId, [FromQuery] Guid? accountId, [FromQuery] Guid? fiscalPeriodId, [FromQuery] DateOnly? fromDate, [FromQuery] DateOnly? toDate, [FromQuery] Guid? costCenterId, [FromQuery] string? sourceContract, [FromQuery] string? presentationCurrencyCode, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Read(http, resolver, auth, "finance.report.general-ledger", companyId, context => persistence.QueryGeneralLedgerAsync(context, new FinanceGeneralLedgerQuery(companyId, accountId, fiscalPeriodId, fromDate, toDate, costCenterId, sourceContract, presentationCurrencyCode), http.RequestAborted))).WithName("finance.report.general-ledger").WithTags("Finance / Reports").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.report.general-ledger")));
        endpoints.MapGet("/api/v1/finance/reports/general-ledger/export", async ([FromQuery] Guid companyId, [FromQuery] Guid? accountId, [FromQuery] Guid? fiscalPeriodId, [FromQuery] DateOnly? fromDate, [FromQuery] DateOnly? toDate, [FromQuery] Guid? costCenterId, [FromQuery] string? sourceContract, [FromQuery] string? presentationCurrencyCode, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Export(http, resolver, auth, "finance.report.general-ledger.export", companyId, async context => { var rows = await persistence.QueryGeneralLedgerAsync(context, new FinanceGeneralLedgerQuery(companyId, accountId, fiscalPeriodId, fromDate, toDate, costCenterId, sourceContract, presentationCurrencyCode), http.RequestAborted); return Csv(rows.Select(row => new[] { row.PostingDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture), row.JournalNumber, row.AccountCode, row.AccountName, Amount(row.Debit), Amount(row.Credit), Amount(row.RunningBalance), row.SourceContract }), ["Date", "Journal", "Account", "Name", "Debit", "Credit", "Running", "Source"]); })).WithName("finance.report.general-ledger.export").WithTags("Finance / Reports").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.report.general-ledger.export")));
        endpoints.MapGet("/api/v1/finance/reports/ap-aging", async ([FromQuery] Guid companyId, [FromQuery] DateOnly asOfDate, [FromQuery] Guid? partyId, [FromQuery] string? currencyCode, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Read(http, resolver, auth, "finance.report.ap-aging", companyId, context => persistence.QueryAgingAsync(context, new FinanceAgingReportQuery(companyId, asOfDate, FinanceOpenItemKind.Payable, partyId, currencyCode), http.RequestAborted))).WithName("finance.report.ap-aging").WithTags("Finance / Reports").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.report.ap-aging")));
        endpoints.MapGet("/api/v1/finance/reports/ap-aging/export", async ([FromQuery] Guid companyId, [FromQuery] DateOnly asOfDate, [FromQuery] Guid? partyId, [FromQuery] string? currencyCode, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Export(http, resolver, auth, "finance.report.ap-aging.export", companyId, async context => { var rows = await persistence.QueryAgingAsync(context, new FinanceAgingReportQuery(companyId, asOfDate, FinanceOpenItemKind.Payable, partyId, currencyCode), http.RequestAborted); return Csv(rows.Select(ToAgingRow), ["DueDate", "Reference", "Bucket", "Currency", "Original", "Allocated", "Outstanding"]); })).WithName("finance.report.ap-aging.export").WithTags("Finance / Reports").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.report.ap-aging.export")));
        endpoints.MapGet("/api/v1/finance/reports/ar-aging", async ([FromQuery] Guid companyId, [FromQuery] DateOnly asOfDate, [FromQuery] Guid? partyId, [FromQuery] string? currencyCode, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Read(http, resolver, auth, "finance.report.ar-aging", companyId, context => persistence.QueryAgingAsync(context, new FinanceAgingReportQuery(companyId, asOfDate, FinanceOpenItemKind.Receivable, partyId, currencyCode), http.RequestAborted))).WithName("finance.report.ar-aging").WithTags("Finance / Reports").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.report.ar-aging")));
        endpoints.MapGet("/api/v1/finance/reports/ar-aging/export", async ([FromQuery] Guid companyId, [FromQuery] DateOnly asOfDate, [FromQuery] Guid? partyId, [FromQuery] string? currencyCode, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Export(http, resolver, auth, "finance.report.ar-aging.export", companyId, async context => { var rows = await persistence.QueryAgingAsync(context, new FinanceAgingReportQuery(companyId, asOfDate, FinanceOpenItemKind.Receivable, partyId, currencyCode), http.RequestAborted); return Csv(rows.Select(ToAgingRow), ["DueDate", "Reference", "Bucket", "Currency", "Original", "Allocated", "Outstanding"]); })).WithName("finance.report.ar-aging.export").WithTags("Finance / Reports").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.report.ar-aging.export")));
        endpoints.MapGet("/api/v1/finance/reports/profit-loss", async ([FromQuery] Guid companyId, [FromQuery] DateOnly fromDate, [FromQuery] DateOnly toDate, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Read(http, resolver, auth, "finance.report.profit-loss", companyId, context => persistence.QueryStatementAsync(context, companyId, FinanceStatementKind.ProfitAndLoss, fromDate, toDate, http.RequestAborted))).WithName("finance.report.profit-loss").WithTags("Finance / Reports").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.report.profit-loss")));
        endpoints.MapGet("/api/v1/finance/reports/balance-sheet", async ([FromQuery] Guid companyId, [FromQuery] DateOnly fromDate, [FromQuery] DateOnly toDate, HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, IFinanceMesp135Persistence persistence) => await Read(http, resolver, auth, "finance.report.balance-sheet", companyId, context => persistence.QueryStatementAsync(context, companyId, FinanceStatementKind.BalanceSheet, fromDate, toDate, http.RequestAborted))).WithName("finance.report.balance-sheet").WithTags("Finance / Reports").WithMetadata(new FoundationOperationMetadata(FoundationOperationCatalog.GetRequired("finance.report.balance-sheet")));
        return endpoints;
    }

    private static async Task<IResult> Read<T>(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, string operation, Guid? companyId, Func<FinanceRequestContext, Task<T>> action)
    { var resolved = await Resolve(http, resolver, auth, operation, companyId); if (resolved.Error is not null) return resolved.Error; try { return Results.Ok(await action(resolved.Context!)); } catch (Exception exception) when (IsConflict(exception)) { return Problem(409, "finance_conflict", "The Finance operation conflicted with another committed change."); } catch { return Problem(503, "finance_unavailable", "Finance data is temporarily unavailable."); } }

    private static async Task<IResult> ExecuteMutationAsync<T>(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, string operation, Guid? companyId, Func<FinanceRequestContext, string, Task<FinanceOperationResult<T>>> action)
    { if (!await ValidateAntiforgery(http)) return Problem(403, "antiforgery_failed", "The request could not be validated."); var key = http.Request.Headers["Idempotency-Key"].FirstOrDefault(); if (!FoundationCorrelation.IsValid(key)) return Problem(400, "idempotency_key_invalid", "A valid Idempotency-Key is required."); var resolved = await Resolve(http, resolver, auth, operation, companyId); if (resolved.Error is not null) return resolved.Error; try { return Result(http, await action(resolved.Context!, key!)); } catch (Exception exception) when (IsConflict(exception)) { return Problem(409, "finance_conflict", "The Finance operation conflicted with another committed change."); } catch { return Problem(503, "finance_unavailable", "Finance is temporarily unavailable."); } }

    private static async Task<IResult> ExecuteMutationAsync<T>(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, string operation, Guid? companyId, Func<FinanceRequestContext, string, byte[], Task<FinanceOperationResult<T>>> action, bool versionRequired = true)
    { if (!versionRequired) return await ExecuteMutationAsync(http, resolver, auth, operation, companyId, (context, key) => action(context, key, [])); if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, operation, companyId, (context, key) => action(context, key, version)); }

    private static async Task<IResult> ExecuteMutationAsync(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, string operation, Guid? companyId, FinanceCloseWriteRequest? request, Guid periodId, IFinanceMesp135Persistence persistence, bool reopen)
    { if (request is null || request.CompanyId == Guid.Empty) return Problem(400, "company_required", "CompanyId is required."); if (!TryIfMatch(http, out var version)) return Problem(400, "if_match_required", "A valid If-Match version is required."); return await ExecuteMutationAsync(http, resolver, auth, operation, request.CompanyId, (context, key) => reopen ? persistence.ReopenPeriodAsync(context, new FinancePeriodReopenCommand(request.CompanyId, periodId, version, request.Reason ?? string.Empty, Guid.NewGuid(), key, Fingerprint(request) + Convert.ToBase64String(version)), http.RequestAborted) : persistence.ClosePeriodAsync(context, new FinancePeriodCloseCommand(request.CompanyId, periodId, version, request.Reason ?? string.Empty, Guid.NewGuid(), key, Fingerprint(request) + Convert.ToBase64String(version)), http.RequestAborted)); }

    private static async Task<IResult> Export(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, string operation, Guid companyId, Func<FinanceRequestContext, Task<string>> action)
    { var resolved = await Resolve(http, resolver, auth, operation, companyId); if (resolved.Error is not null) return resolved.Error; try { return Results.File(Encoding.UTF8.GetBytes(await action(resolved.Context!)), "text/csv", $"{operation.Replace('.', '-')}.csv"); } catch { return Problem(503, "finance_unavailable", "Finance data is temporarily unavailable."); } }

    private static async Task<(FinanceRequestContext? Context, IResult? Error)> Resolve(HttpContext http, ITrustedRequestContextResolver resolver, FinanceAuthorizationService auth, string operation, Guid? companyId)
    { var foundation = await resolver.ResolveAsync(http, http.RequestAborted); if (!FinanceRequestContext.TryCreate(foundation, out var context) || context is null) return (null, Problem(foundation.SecurityProfile == FoundationSecurityProfile.Anonymous ? 401 : 403, "access_denied", "The operation is not available for this security context.")); var decision = auth.Authorize(context, operation, companyId); return decision.Allowed ? (context, null) : (null, Problem(403, decision.Code, "The requested Finance scope is not authorized.")); }
    private static async Task<bool> ValidateAntiforgery(HttpContext http) { try { await http.RequestServices.GetRequiredService<IAntiforgery>().ValidateRequestAsync(http); return true; } catch (AntiforgeryValidationException) { return false; } }
    private static IResult Result<T>(HttpContext http, FinanceOperationResult<T> result) { if (!result.Succeeded || result.Value is null) return Problem(StatusFor(result.Code), result.Code, "The Finance operation was not completed."); if (typeof(T).GetProperty("Version")?.GetValue(result.Value) is byte[] version) http.Response.Headers.ETag = $"\"{Convert.ToBase64String(version)}\""; return Results.Ok(result.Value); }
    private static bool TryIfMatch(HttpContext http, out byte[] version) { version = []; var value = http.Request.Headers.IfMatch.FirstOrDefault()?.Trim('"'); if (string.IsNullOrWhiteSpace(value)) return false; try { version = Convert.FromBase64String(value); return version.Length > 0; } catch (FormatException) { return false; } }
    private static string Fingerprint<T>(T value) => FinanceFingerprint.For(typeof(T).Name, JsonSerializer.Serialize(value));
    private static int StatusFor(string code) => code is "company_scope_denied" or "permission_denied" ? 403 : code.Contains("not_found", StringComparison.OrdinalIgnoreCase) ? 404 : code is "concurrency_conflict" or "idempotency_conflict" ? 409 : 422;
    private static bool IsConflict(Exception exception) => exception.GetType().Name is "DbUpdateException" or "DbUpdateConcurrencyException" || exception.InnerException is not null && IsConflict(exception.InnerException);
    private static IResult Problem(int status, string code, string detail) => Results.Problem(detail, statusCode: status, title: code, extensions: new Dictionary<string, object?> { ["code"] = code });
    private static string Csv(IEnumerable<string[]> rows, string[] header) { var builder = new StringBuilder(); foreach (var row in rows.Prepend(header)) builder.AppendLine(string.Join(',', row.Select(Escape))); return builder.ToString(); }
    private static string[] ToAgingRow(FinanceAgingReportRow row) => [row.DueDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture), row.SourceReference ?? string.Empty, row.AgingBucket, row.CurrencyCode, Amount(row.OriginalAmount), Amount(row.AllocatedAmount), Amount(row.OutstandingAmount)];
    private static string Amount(decimal value) => value.ToString("0.########", CultureInfo.InvariantCulture);
    private static string Escape(string value) => $"\"{value.Replace("\"", "\"\"", StringComparison.Ordinal)}\"";

    public sealed record FinanceCloseWriteRequest(Guid CompanyId, string? Reason);
    public sealed record FinanceYearEndWriteRequest(Guid CompanyId, Guid FiscalYearId, DateOnly AsOfDate, string? Reason);
    public sealed record FinanceActionWriteRequest(Guid CompanyId, string? Reason);
    public sealed record FinanceCorrectionWriteRequest(Guid CompanyId, DateOnly PostingDate, string? Reason);
}

#pragma warning restore CS1591
