// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniErp.Infrastructure.Persistence.Modules.Finance;

#nullable disable

namespace MiniErp.Infrastructure.Persistence.Migrations.Finance
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260825232242_MESP134EvidenceSnapshots")]
    partial class MESP134EvidenceSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniErp.App.BuildingBlocks.Tenancy.TenantOwnedRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RelatedTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RelationshipKind")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BusinessKey")
                        .IsUnique();

                    b.ToTable("TenantOwnedRecords", "tenancy");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrencyBehavior")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsPostingAccount")
                        .HasColumnType("bit");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "ParentAccountId");

                    b.ToTable("Accounts", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceAllocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AllocationDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("FunctionalAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("HistoricalFunctionalAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OpenItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RealizedFxAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("RealizedFxDirection")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("RealizedFxJournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RealizedFxRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RealizedFxRuleVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("ReversalOfAllocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SettlementDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SettlementFunctionalAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "OpenItemId");

                    b.HasIndex("TenantId", "CompanyId", "ReversalOfAllocationId")
                        .IsUnique()
                        .HasFilter("[ReversalOfAllocationId] IS NOT NULL");

                    b.HasIndex("TenantId", "CompanyId", "SettlementDocumentId", "Id")
                        .IsUnique();

                    b.ToTable("Allocations", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Reason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceCashAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BankReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("int");

                    b.Property<string>("LinkedAccountCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("LinkedAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "LinkedAccountId");

                    b.ToTable("CashAccounts", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceCostCenterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("CostCenters", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceFiscalCalendarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FunctionalCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "Lifecycle")
                        .IsUnique()
                        .HasFilter("Lifecycle = 1");

                    b.ToTable("FiscalCalendars", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceFiscalPeriodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FiscalYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "FiscalYearId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "FiscalYearId", "Sequence")
                        .IsUnique();

                    b.ToTable("FiscalPeriods", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceFiscalYearEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("YearNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CalendarId", "YearNumber")
                        .IsUnique();

                    b.ToTable("FiscalYears", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceIdempotencyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ActorId", "OperationId", "Key")
                        .IsUnique();

                    b.ToTable("IdempotencyEntries", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceJournalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountAuthority")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalRequirement")
                        .HasColumnType("int");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<decimal?>("ExchangeRate")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<Guid?>("ExchangeRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExchangeRateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ExchangeRateVersionNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("FiscalPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FiscalYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FunctionalCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateOnly>("JournalDate")
                        .HasColumnType("date");

                    b.Property<string>("JournalNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("JournalSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PostedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("PostingRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PostingRuleVersionNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReversalJournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReversalOfJournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReversedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceContract")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceEvent")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("SourceEvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SourceEvidenceVersion")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubmittedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionCurrencyCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "JournalSequence")
                        .IsUnique();

                    b.HasIndex("TenantId", "SourceContract", "SourceEvidenceId", "SourceEvidenceVersion")
                        .IsUnique()
                        .HasFilter("[SourceEvidenceId] IS NOT NULL");

                    b.ToTable("Journals", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceJournalLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Credit")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("Debit")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<decimal>("FunctionalCredit")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("FunctionalDebit")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TransactionAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("TransactionCurrencyCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "JournalId", "LineNumber")
                        .IsUnique();

                    b.ToTable("JournalLines", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceMonetaryPolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("FunctionalCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ReportingCurrencyCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("ReportingCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RevaluationEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("RoundingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("RoundingScale")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "EffectiveFrom");

                    b.HasIndex("TenantId", "CompanyId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("MonetaryPolicies", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceOpenItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("ExchangeRate")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<Guid?>("ExchangeRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExchangeRateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ExchangeRateVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("FunctionalCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid?>("MatchEvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MatchEvidenceVersion")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("OriginalFunctionalAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("PaymentTermArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PaymentTermCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly?>("PaymentTermEffectiveOn")
                        .HasColumnType("date");

                    b.Property<string>("PaymentTermEnglishName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("PaymentTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaymentTermVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PaymentTermVersionNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("RecognitionJournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecognitionState")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceContract")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SourceDocumentVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceEvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SourceEvidenceVersion")
                        .HasColumnType("int");

                    b.Property<string>("SourceSnapshot")
                        .HasMaxLength(262144)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "Kind", "DueDate");

                    b.HasIndex("TenantId", "CompanyId", "SourceContract", "SourceEvidenceId", "SourceEvidenceVersion")
                        .IsUnique();

                    b.ToTable("OpenItems", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinancePaymentMethodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsManual")
                        .HasColumnType("bit");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresReference")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("PaymentMethods", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinancePostingRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CostCenterRequired")
                        .HasColumnType("bit");

                    b.Property<string>("CreditAccountCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CreditAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DebitAccountCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("DebitAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("int");

                    b.Property<string>("SourceContract")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceEvent")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "SourceContract", "SourceEvent", "VersionNumber")
                        .IsUnique();

                    b.ToTable("PostingRules", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceRevaluationBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PostedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReversedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReversedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "AsOfDate", "Status");

                    b.ToTable("RevaluationBatches", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceRevaluationLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Difference")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExchangeEffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExchangeEffectiveOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExchangeEffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("ExchangeProvenance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<Guid>("ExchangeRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExchangeRateScale")
                        .HasColumnType("int");

                    b.Property<Guid>("ExchangeRateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExchangeRateVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("ExchangeSourceCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ExchangeSourceNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ExchangeTargetCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("HistoricalFunctionalAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("OutstandingTransactionAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("RevaluedFunctionalAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid?>("ReversalJournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BatchId", "SourceId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "SourceId", "Status");

                    b.ToTable("RevaluationLines", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceSettlementDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CashAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("ExchangeRate")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<Guid?>("ExchangeRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExchangeRateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ExchangeRateVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("FunctionalAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("FunctionalCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PostedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PostedJournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReversalJournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReversedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubmittedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "CashAccountId");

                    b.HasIndex("TenantId", "CompanyId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "PaymentMethodId");

                    b.HasIndex("TenantId", "CompanyId", "Direction", "DocumentDate");

                    b.ToTable("SettlementDocuments", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceSourceEffectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceContract")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("SourceEvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SourceEvidenceVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "SourceContract", "SourceEvidenceId", "SourceEvidenceVersion")
                        .IsUnique();

                    b.ToTable("SourceEffects", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceTaxAccountingEffectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FunctionalAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("FunctionalCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("FunctionalRoundingDifference")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid?>("FunctionalToReportingRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FunctionalToReportingRateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FunctionalToReportingRateVersionNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("MonetaryEvidenceJson")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OpenItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostingRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PostingRuleVersionNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReportingAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("ReportingCurrencyCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("ReportingEvidenceStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReportingRoundingDifference")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid?>("ReversalJournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoundingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("RoundingScale")
                        .HasColumnType("int");

                    b.Property<decimal>("SourceUnroundedFunctionalAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("SourceUnroundedReportingAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly>("TaxEffectiveOn")
                        .HasColumnType("date");

                    b.Property<Guid>("TaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TaxRatePercentage")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid>("TaxRateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TaxRateVersionNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxableBase")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("TransactionToFunctionalRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransactionToFunctionalRateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TransactionToFunctionalRateVersionNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId", "JournalId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "OpenItemId");

                    b.ToTable("TaxAccountingEffects", "finance");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceAccountEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "ParentAccountId")
                        .HasPrincipalKey("TenantId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceAllocationEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceOpenItemEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "OpenItemId")
                        .HasPrincipalKey("TenantId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceSettlementDocumentEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "SettlementDocumentId")
                        .HasPrincipalKey("TenantId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceCashAccountEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "LinkedAccountId")
                        .HasPrincipalKey("TenantId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceFiscalPeriodEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceFiscalYearEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "FiscalYearId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceFiscalYearEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceFiscalCalendarEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CalendarId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceJournalLineEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceJournalEntity", null)
                        .WithMany("Lines")
                        .HasForeignKey("TenantId", "JournalId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceRevaluationLineEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceRevaluationBatchEntity", null)
                        .WithMany("Lines")
                        .HasForeignKey("TenantId", "BatchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceSettlementDocumentEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceCashAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "CashAccountId")
                        .HasPrincipalKey("TenantId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Finance.FinancePaymentMethodEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "PaymentMethodId")
                        .HasPrincipalKey("TenantId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceJournalEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Finance.FinanceRevaluationBatchEntity", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
