// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MiniErp.Infrastructure.Persistence.Modules.Inventory;

#nullable disable

namespace MiniErp.Infrastructure.Persistence.Migrations.Inventory
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260823211902_MESP131SolFinalValuationIntegrity")]
    partial class MESP131SolFinalValuationIntegrity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
