#pragma warning disable CS1591

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MiniErp.App.BuildingBlocks.Tenancy;

namespace MiniErp.Infrastructure.Persistence.Modules.Inventory;

internal static class InventoryStockControlModelBuilder
{
    internal static void Configure(ModelBuilder modelBuilder, string? providerName)
    {
        ConfigureBase(modelBuilder.Entity<InventoryReasonCodeEntity>(), "ReasonCodes", providerName);
        var reason = modelBuilder.Entity<InventoryReasonCodeEntity>();
        reason.Property(item => item.Code).HasMaxLength(128).IsRequired(); reason.Property(item => item.EnglishName).HasMaxLength(256).IsRequired(); reason.Property(item => item.ArabicName).HasMaxLength(256).IsRequired(); reason.Property(item => item.Category).IsRequired(); reason.Property(item => item.IsActive).IsRequired(); reason.Property(item => item.CreatedByActorId).IsRequired(); reason.Property(item => item.CreatedAt).IsRequired(); reason.Property(item => item.UpdatedAt).IsRequired(); reason.HasIndex(item => new { item.TenantId, item.Code }).IsUnique();

        ConfigureBase(modelBuilder.Entity<InventoryAdjustmentEntity>(), "Adjustments", providerName);
        var adjustment = modelBuilder.Entity<InventoryAdjustmentEntity>();
        adjustment.Property(item => item.CompanyId).IsRequired(); adjustment.Property(item => item.BranchId).IsRequired(false); adjustment.Property(item => item.WarehouseId).IsRequired(); adjustment.Property(item => item.WarehouseCode).HasMaxLength(128).IsRequired(); adjustment.Property(item => item.WarehouseName).HasMaxLength(256).IsRequired(); adjustment.Property(item => item.RequesterId).IsRequired(); adjustment.Property(item => item.Status).IsRequired(); adjustment.Property(item => item.EvidenceReference).HasMaxLength(512).IsRequired(false); adjustment.Property(item => item.ApprovalPolicySnapshotJson).HasMaxLength(32768).IsRequired(false); adjustment.Property(item => item.CurrentStageApproverIdsJson).HasMaxLength(32768).IsRequired(false); adjustment.Property(item => item.CurrentApprovalStageIndex).IsRequired(); adjustment.Property(item => item.CurrentStageApprovalCount).IsRequired(); adjustment.Property(item => item.LastApproverId).IsRequired(false); adjustment.Property(item => item.LastDelegatedFromActorId).IsRequired(false); adjustment.Property(item => item.CreatedAt).IsRequired(); adjustment.Property(item => item.UpdatedAt).IsRequired(); adjustment.Property(item => item.SubmittedAt).IsRequired(false); adjustment.Property(item => item.ApprovedAt).IsRequired(false); adjustment.Property(item => item.PostedAt).IsRequired(false); adjustment.HasIndex(item => new { item.TenantId, item.CompanyId, item.BranchId, item.WarehouseId, item.Status, item.CreatedAt });

        ConfigureBase(modelBuilder.Entity<InventoryAdjustmentLineEntity>(), "AdjustmentLines", providerName);
        var adjustmentLine = modelBuilder.Entity<InventoryAdjustmentLineEntity>();
        adjustmentLine.Property(item => item.AdjustmentId).IsRequired(); adjustmentLine.Property(item => item.ProductId).IsRequired(); adjustmentLine.Property(item => item.ProductSku).HasMaxLength(128).IsRequired(); adjustmentLine.Property(item => item.ProductName).HasMaxLength(256).IsRequired(); adjustmentLine.Property(item => item.UnitOfMeasureId).IsRequired(); adjustmentLine.Property(item => item.UnitOfMeasureCode).HasMaxLength(128).IsRequired(); adjustmentLine.Property(item => item.Direction).IsRequired(); adjustmentLine.Property(item => item.Quantity).HasPrecision(28, 8).IsRequired(); adjustmentLine.Property(item => item.TrackingIdentity).HasMaxLength(256).IsRequired(); adjustmentLine.Property(item => item.ReasonCodeId).IsRequired(); adjustmentLine.Property(item => item.ReasonCode).HasMaxLength(128).IsRequired(); adjustmentLine.Property(item => item.ReasonEnglishName).HasMaxLength(256).IsRequired(); adjustmentLine.Property(item => item.ReasonArabicName).HasMaxLength(256).IsRequired(); adjustmentLine.Property(item => item.EvidenceReference).HasMaxLength(512).IsRequired(false); adjustmentLine.Property(item => item.MovementId).IsRequired(false); adjustmentLine.HasIndex(item => new { item.TenantId, item.AdjustmentId }); adjustmentLine.HasIndex(item => new { item.TenantId, item.AdjustmentId, item.Id }).IsUnique(); adjustmentLine.HasOne(item => item.Adjustment).WithMany(item => item.Lines).HasForeignKey(item => new { item.TenantId, item.AdjustmentId }).HasPrincipalKey(item => new { item.TenantId, item.Id }).OnDelete(DeleteBehavior.Cascade);

        ConfigureBase(modelBuilder.Entity<InventoryCountEntity>(), "Counts", providerName);
        var count = modelBuilder.Entity<InventoryCountEntity>();
        count.Property(item => item.CompanyId).IsRequired(); count.Property(item => item.BranchId).IsRequired(false); count.Property(item => item.WarehouseId).IsRequired(); count.Property(item => item.WarehouseCode).HasMaxLength(128).IsRequired(); count.Property(item => item.WarehouseName).HasMaxLength(256).IsRequired(); count.Property(item => item.CountType).IsRequired(); count.Property(item => item.AssignedCounterId).IsRequired(); count.Property(item => item.ReviewerId).IsRequired(false); count.Property(item => item.ApproverId).IsRequired(false); count.Property(item => item.PosterId).IsRequired(false); count.Property(item => item.Status).IsRequired(); count.Property(item => item.ApprovalPolicySnapshotJson).HasMaxLength(32768).IsRequired(false); count.Property(item => item.CurrentStageApproverIdsJson).HasMaxLength(32768).IsRequired(false); count.Property(item => item.CurrentApprovalStageIndex).IsRequired(); count.Property(item => item.CurrentStageApprovalCount).IsRequired(); count.Property(item => item.LastApproverId).IsRequired(false); count.Property(item => item.LastDelegatedFromActorId).IsRequired(false); count.Property(item => item.CurrentRoundGeneration).IsRequired(); count.Property(item => item.SnapshotCutoff).IsRequired(); count.Property(item => item.CreatedByActorId).IsRequired(); count.Property(item => item.CreatedAt).IsRequired(); count.Property(item => item.UpdatedAt).IsRequired(); count.Property(item => item.SubmittedAt).IsRequired(false); count.Property(item => item.ApprovedAt).IsRequired(false); count.Property(item => item.PostedAt).IsRequired(false); count.HasIndex(item => new { item.TenantId, item.CompanyId, item.BranchId, item.WarehouseId, item.Status, item.CreatedAt });

        ConfigureBase(modelBuilder.Entity<InventoryCountLineEntity>(), "CountLines", providerName);
        var countLine = modelBuilder.Entity<InventoryCountLineEntity>();
        countLine.Property(item => item.CountId).IsRequired(); countLine.Property(item => item.PriorLineId).IsRequired(false); countLine.Property(item => item.RoundGeneration).IsRequired(); countLine.Property(item => item.ProductId).IsRequired(); countLine.Property(item => item.ProductSku).HasMaxLength(128).IsRequired(); countLine.Property(item => item.ProductName).HasMaxLength(256).IsRequired(); countLine.Property(item => item.UnitOfMeasureId).IsRequired(); countLine.Property(item => item.UnitOfMeasureCode).HasMaxLength(128).IsRequired(); countLine.Property(item => item.TrackingIdentity).HasMaxLength(256).IsRequired(); countLine.Property(item => item.ExpectedQuantity).HasPrecision(28, 8).IsRequired(); countLine.Property(item => item.CountedQuantity).HasPrecision(28, 8).IsRequired(false); countLine.Property(item => item.Variance).HasPrecision(28, 8).IsRequired(false); countLine.Property(item => item.VarianceReasonCodeId).IsRequired(false); countLine.Property(item => item.VarianceReasonCode).HasMaxLength(128).IsRequired(false); countLine.Property(item => item.VarianceReasonEnglishName).HasMaxLength(256).IsRequired(false); countLine.Property(item => item.VarianceReasonArabicName).HasMaxLength(256).IsRequired(false); countLine.Property(item => item.CountedAt).IsRequired(false); countLine.Property(item => item.MovementId).IsRequired(false); countLine.HasIndex(item => new { item.TenantId, item.CountId, item.RoundGeneration }); countLine.HasIndex(item => new { item.TenantId, item.CountId, item.Id }).IsUnique(); countLine.HasOne(item => item.Count).WithMany(item => item.Lines).HasForeignKey(item => new { item.TenantId, item.CountId }).HasPrincipalKey(item => new { item.TenantId, item.Id }).OnDelete(DeleteBehavior.Cascade);

        ConfigureBase(modelBuilder.Entity<InventoryStockIssueEntity>(), "StockIssues", providerName);
        var issue = modelBuilder.Entity<InventoryStockIssueEntity>();
        issue.Property(item => item.CompanyId).IsRequired(); issue.Property(item => item.BranchId).IsRequired(false); issue.Property(item => item.WarehouseId).IsRequired(); issue.Property(item => item.WarehouseCode).HasMaxLength(128).IsRequired(); issue.Property(item => item.WarehouseName).HasMaxLength(256).IsRequired(); issue.Property(item => item.DestinationUseDescription).HasMaxLength(2048).IsRequired(); issue.Property(item => item.RequesterId).IsRequired(); issue.Property(item => item.Status).IsRequired(); issue.Property(item => item.ApprovalPolicySnapshotJson).HasMaxLength(32768).IsRequired(false); issue.Property(item => item.CurrentStageApproverIdsJson).HasMaxLength(32768).IsRequired(false); issue.Property(item => item.CurrentApprovalStageIndex).IsRequired(); issue.Property(item => item.CurrentStageApprovalCount).IsRequired(); issue.Property(item => item.LastApproverId).IsRequired(false); issue.Property(item => item.LastDelegatedFromActorId).IsRequired(false); issue.Property(item => item.CreatedAt).IsRequired(); issue.Property(item => item.UpdatedAt).IsRequired(); issue.Property(item => item.SubmittedAt).IsRequired(false); issue.Property(item => item.ApprovedAt).IsRequired(false); issue.Property(item => item.PostedAt).IsRequired(false); issue.HasIndex(item => new { item.TenantId, item.CompanyId, item.BranchId, item.WarehouseId, item.Status, item.CreatedAt });

        ConfigureBase(modelBuilder.Entity<InventoryStockIssueLineEntity>(), "StockIssueLines", providerName);
        var issueLine = modelBuilder.Entity<InventoryStockIssueLineEntity>();
        issueLine.Property(item => item.StockIssueId).IsRequired(); issueLine.Property(item => item.ProductId).IsRequired(); issueLine.Property(item => item.ProductSku).HasMaxLength(128).IsRequired(); issueLine.Property(item => item.ProductName).HasMaxLength(256).IsRequired(); issueLine.Property(item => item.UnitOfMeasureId).IsRequired(); issueLine.Property(item => item.UnitOfMeasureCode).HasMaxLength(128).IsRequired(); issueLine.Property(item => item.Quantity).HasPrecision(28, 8).IsRequired(); issueLine.Property(item => item.TrackingIdentity).HasMaxLength(256).IsRequired(); issueLine.Property(item => item.ReasonCodeId).IsRequired(); issueLine.Property(item => item.ReasonCode).HasMaxLength(128).IsRequired(); issueLine.Property(item => item.ReasonEnglishName).HasMaxLength(256).IsRequired(); issueLine.Property(item => item.ReasonArabicName).HasMaxLength(256).IsRequired(); issueLine.Property(item => item.EvidenceReference).HasMaxLength(512).IsRequired(false); issueLine.Property(item => item.MovementId).IsRequired(false); issueLine.HasIndex(item => new { item.TenantId, item.StockIssueId }); issueLine.HasIndex(item => new { item.TenantId, item.StockIssueId, item.Id }).IsUnique(); issueLine.HasOne(item => item.StockIssue).WithMany(item => item.Lines).HasForeignKey(item => new { item.TenantId, item.StockIssueId }).HasPrincipalKey(item => new { item.TenantId, item.Id }).OnDelete(DeleteBehavior.Cascade);

        ConfigureBase(modelBuilder.Entity<InventoryControlHistoryEntity>(), "ControlHistory", providerName);
        var history = modelBuilder.Entity<InventoryControlHistoryEntity>();
        history.Property(item => item.ResourceType).HasMaxLength(64).IsRequired(); history.Property(item => item.ResourceId).IsRequired(); history.Property(item => item.LineId).IsRequired(false); history.Property(item => item.Action).IsRequired(); history.Property(item => item.FromStatus).IsRequired(); history.Property(item => item.ToStatus).IsRequired(); history.Property(item => item.ActorId).IsRequired(); history.Property(item => item.DelegatedFromActorId).IsRequired(false); history.Property(item => item.Reason).HasMaxLength(2048).IsRequired(false); history.Property(item => item.CorrelationId).HasMaxLength(128).IsRequired(); history.Property(item => item.RoundGeneration).IsRequired(); history.Property(item => item.OccurredAt).IsRequired(); history.HasIndex(item => new { item.TenantId, item.ResourceType, item.ResourceId, item.OccurredAt });
    }

    private static void ConfigureBase<TEntity>(EntityTypeBuilder<TEntity> entity, string tableName, string? providerName) where TEntity : class, ITenantOwned
    {
        if (providerName == "Microsoft.EntityFrameworkCore.SqlServer") entity.ToTable(tableName, "inventory"); else entity.ToTable(tableName);
        entity.HasKey("Id"); entity.Property("Id").ValueGeneratedNever(); entity.Property(item => item.TenantId).HasConversion(item => item.Value, value => new TenantId(value)).IsRequired();
        var version = entity.Property<byte[]>("Version").IsRequired().IsConcurrencyToken(); if (providerName == "Microsoft.EntityFrameworkCore.SqlServer") version.IsRowVersion(); else version.ValueGeneratedNever();
        entity.HasIndex("TenantId", "Id").IsUnique();
    }
}

#pragma warning restore CS1591
