import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../../core/auth/auth.service';
import { MasterDataService } from '../master-data/master-data.service';
import { ProductRecord } from '../master-data/master-data.models';
import { InventoryService } from './inventory.service';
import { InventoryAdjustment, InventoryControlHistory, InventoryCount, InventoryCountLine, InventoryMovement, InventoryReasonCategory, InventoryReasonCode, InventoryStockIssue, InventoryWarehouseOption } from './inventory.model';

@Component({
  selector: 'app-inventory-stock-control',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <section class="ui-surface stock-control" data-testid="inventory-stock-control">
      <header class="stock-control__header"><div><p class="eyebrow">CONTROLLED OPERATIONS</p><h2>Stock control and corrections</h2><p class="lede">Posted effects become immutable ledger evidence. Finance valuation remains pending until MWA.</p></div><span class="status-badge status-badge--active">Server-authorized</span></header>
      <div class="stock-control__toolbar">
        <label><span>Warehouse</span><select [(ngModel)]="warehouseId" (ngModelChange)="refresh()"><option value="">Choose warehouse</option>@for (warehouse of warehouses(); track warehouse.warehouseId) {<option [value]="warehouse.warehouseId">{{ warehouse.displayName }}</option>}</select></label>
        <label><span>Product</span><select [(ngModel)]="productId"><option value="">Choose product</option>@for (product of products(); track product.id) {<option [value]="product.id">{{ product.sku }} — {{ product.englishName || product.arabicName }}</option>}</select></label>
        <button class="button button--quiet" type="button" (click)="refresh()">Refresh</button>
      </div>
      @if (error()) { <p class="stock-control__error" role="alert">{{ error() }}</p> }

      <section class="reason-panel">
        <div class="list-heading"><div><h3>Reason catalogue</h3><p class="form-note">Tenant-owned bilingual codes. Inactive codes remain visible for historical evidence but are unavailable for new documents.</p></div><span>{{ reasonCatalogue().length }}</span></div>
        <form class="reason-form" (ngSubmit)="createReasonCode()"><input name="reasonCode" placeholder="Code" [(ngModel)]="newReason.code" required /><input name="reasonEnglish" placeholder="English name" [(ngModel)]="newReason.englishName" required /><input name="reasonArabic" placeholder="Arabic name" [(ngModel)]="newReason.arabicName" required /><select name="reasonCategory" [(ngModel)]="newReason.category"><option value="Adjustment">Adjustment</option><option value="CountVariance">Count variance</option><option value="StockIssue">Stock issue</option></select><button class="button button--primary" type="submit" [disabled]="!canWrite() || !newReason.code.trim() || !newReason.englishName.trim() || !newReason.arabicName.trim()">Create reason</button></form>
        <div class="reason-list">@for (reason of reasonCatalogue(); track reason.id) {<article class="reason-row"><strong>{{ reason.code }}</strong><select [name]="'reason-category-' + reason.id" [(ngModel)]="reasonDrafts[reason.id].category"><option value="Adjustment">Adjustment</option><option value="CountVariance">Count variance</option><option value="StockIssue">Stock issue</option></select><input [name]="'reason-en-' + reason.id" [(ngModel)]="reasonDrafts[reason.id].englishName" /><input [name]="'reason-ar-' + reason.id" [(ngModel)]="reasonDrafts[reason.id].arabicName" /><span class="status-badge">{{ reason.isActive ? 'Active' : 'Inactive' }}</span><button type="button" (click)="updateReasonCode(reason)">Save</button><button type="button" (click)="toggleReasonCode(reason)">{{ reason.isActive ? 'Deactivate' : 'Activate' }}</button></article>} @empty {<p class="empty-copy">No reason codes configured.</p>}</div>
      </section>

      <div class="stock-control__grid">
        <form class="control-form" (ngSubmit)="createAdjustment()"><h3>Stock adjustment</h3><label><span>Direction</span><select name="direction" [(ngModel)]="adjustment.direction"><option value="Increase">Increase</option><option value="Decrease">Decrease</option></select></label><label><span>Quantity</span><input name="quantity" type="number" min="0.00000001" step="any" [(ngModel)]="adjustment.quantity" required /></label><label><span>Reason</span><select name="reason" [(ngModel)]="adjustment.reasonCode" required><option value="">Choose reason</option>@for (reason of adjustmentReasons(); track reason.id) {<option [value]="reason.code">{{ reason.code }} — {{ reason.englishName }}</option>}</select></label><label><span>Tracking identity (if required)</span><input name="tracking" [(ngModel)]="adjustment.trackingIdentity" /></label><button class="button button--primary" type="submit" [disabled]="!canWrite() || adjustment.quantity <= 0">Create draft</button></form>
        <form class="control-form" (ngSubmit)="createCount()"><h3>Inventory count</h3><label><span>Count type</span><select name="countType" [(ngModel)]="countType"><option value="Cycle">Cycle count</option><option value="Full">Full warehouse snapshot</option></select></label><label><span>Counter</span><input name="counter" [value]="actorId" readonly /></label><label><span>Reviewer (optional)</span><input name="reviewer" [(ngModel)]="reviewerId" placeholder="Server-authorized reviewer ID" /></label><p class="form-note">The server records the cutoff and expected quantity. The counter records physical observations only.</p><button class="button button--primary" type="submit" [disabled]="!canWrite() || !productId || !actorId">Open count</button></form>
        <form class="control-form" (ngSubmit)="createIssue()"><h3>Stock issue</h3><label><span>Destination/use</span><input name="destination" maxlength="2048" [(ngModel)]="issue.destinationUseDescription" required /></label><label><span>Quantity</span><input name="issueQuantity" type="number" min="0.00000001" step="any" [(ngModel)]="issue.quantity" required /></label><label><span>Reason</span><select name="issueReason" [(ngModel)]="issue.reasonCode" required><option value="">Choose reason</option>@for (reason of issueReasons(); track reason.id) {<option [value]="reason.code">{{ reason.code }} — {{ reason.englishName }}</option>}</select></label><label><span>Tracking identity (if required)</span><input name="issueTracking" [(ngModel)]="issue.trackingIdentity" /></label><button class="button button--primary" type="submit" [disabled]="!canWrite() || issue.quantity <= 0">Create draft</button></form>
      </div>

      <div class="stock-control__lists">
        <section><div class="list-heading"><h3>Adjustments</h3><span>{{ adjustments().length }}</span></div>@for (record of adjustments(); track record.id) {<article class="control-row"><div><strong>{{ record.lines[0]?.productSku }}</strong><small>{{ record.lines[0]?.direction }} · {{ record.lines[0]?.quantity }} · {{ record.lines[0]?.reasonCode }}</small></div><span class="status-badge">{{ record.status }}</span><div class="control-actions">@if (record.status === 'Draft') {<button type="button" (click)="submitAdjustment(record)">Submit</button>} @if (record.status === 'PendingApproval') {<button type="button" (click)="approveAdjustment(record)">Approve</button><button type="button" (click)="rejectAdjustment(record)">Reject</button>} @if (record.status === 'Approved') {<button type="button" (click)="postAdjustment(record)">Post</button>}<button type="button" (click)="loadAdjustmentHistory(record.id)">History</button></div>@if (historyFor(record.id).length) {<ol class="history-list">@for (event of historyFor(record.id); track event.id) {<li>{{ event.action }} · {{ event.fromStatus }} → {{ event.toStatus }} · {{ event.occurredAt | date:'short' }}</li>}</ol>}</article>} @empty {<p class="empty-copy">No adjustments in this context.</p>}</section>
        <section><div class="list-heading"><h3>Counts</h3><span>{{ counts().length }}</span></div>@for (record of counts(); track record.id) {<article class="control-row count-row"><div><strong>{{ record.countType }} · round {{ record.currentRoundGeneration }}</strong><small>{{ record.lines.length }} lines · {{ record.snapshotCutoff | date:'short' }}</small></div><span class="status-badge">{{ record.status }}</span>
          @if (record.status === 'Draft' && record.assignedCounterId === actorId) {<div class="count-observations"><p class="form-note">Enter the physical quantity. Expected stock is intentionally not shown.</p>@for (line of currentLines(record); track line.id) {<label class="count-line"><span>{{ line.productSku }} · {{ line.unitOfMeasureCode }}@if (line.trackingIdentity) { · {{ line.trackingIdentity }}}</span><input type="number" min="0" step="any" [name]="'count-' + line.id" [(ngModel)]="countedQuantities[line.id]" required /></label>}<button type="button" (click)="submitCount(record)">Submit observations</button></div>}
          @if (record.status !== 'Draft' || record.assignedCounterId !== actorId) {<div class="count-review">@for (line of currentLines(record); track line.id) {<div class="count-line"><span>{{ line.productSku }} · {{ line.unitOfMeasureCode }}</span><small>Expected: {{ line.expectedQuantity ?? '—' }} · Counted: {{ line.countedQuantity ?? '—' }} · Variance: {{ line.variance ?? '—' }}</small>@if (record.status === 'PendingApproval' && line.variance !== null && line.variance !== 0 && !line.varianceReasonCode) {<select [name]="'variance-' + line.id" [(ngModel)]="varianceReasonCodes[line.id]"><option value="">Choose variance reason</option>@for (reason of varianceReasons(); track reason.id) {<option [value]="reason.code">{{ reason.code }} — {{ reason.englishName }}</option>}</select><button type="button" (click)="recordVarianceReason(record, line)">Record reason</button>}</div>}</div>}
          <div class="control-actions">@if (record.status === 'PendingApproval') {<button type="button" (click)="approveCount(record)">Approve</button><button type="button" (click)="rejectCount(record)">Reject</button>} @if (record.status === 'Submitted') {<button type="button" (click)="postCount(record)">Finalize</button>} @if (record.status === 'Approved') {<button type="button" (click)="postCount(record)">Post</button>} @if (record.status === 'PendingApproval' || record.status === 'Approved') {<button type="button" (click)="recount(record)">Request recount</button>} @if (record.status === 'ResnapshotRequired') {<button type="button" (click)="resnapshot(record)">Resnapshot</button>}<button type="button" (click)="loadCountHistory(record.id)">History</button></div>@if (historyFor(record.id).length) {<ol class="history-list">@for (event of historyFor(record.id); track event.id) {<li>{{ event.action }} · {{ event.fromStatus }} → {{ event.toStatus }} · {{ event.occurredAt | date:'short' }}</li>}</ol>}</article>} @empty {<p class="empty-copy">No counts in this context.</p>}</section>
        <section><div class="list-heading"><h3>Stock issues</h3><span>{{ issues().length }}</span></div>@for (record of issues(); track record.id) {<article class="control-row"><div><strong>{{ record.destinationUseDescription }}</strong><small>{{ record.lines[0]?.productSku }} · {{ record.lines[0]?.quantity }} · {{ record.lines[0]?.reasonCode }}</small></div><span class="status-badge">{{ record.status }}</span><div class="control-actions">@if (record.status === 'Draft') {<button type="button" (click)="submitIssue(record)">Submit</button>} @if (record.status === 'PendingApproval') {<button type="button" (click)="approveIssue(record)">Approve</button><button type="button" (click)="rejectIssue(record)">Reject</button>} @if (record.status === 'Approved') {<button type="button" (click)="postIssue(record)">Post</button>}<button type="button" (click)="loadIssueHistory(record.id)">History</button></div>@if (historyFor(record.id).length) {<ol class="history-list">@for (event of historyFor(record.id); track event.id) {<li>{{ event.action }} · {{ event.fromStatus }} → {{ event.toStatus }} · {{ event.occurredAt | date:'short' }}</li>}</ol>}</article>} @empty {<p class="empty-copy">No stock issues in this context.</p>}</section>
      </div>

      <section class="ledger-panel"><div class="list-heading"><div><h3>Eligible corrections</h3><p class="form-note">Only posted MESP-130 Stock Adjustment, Count Variance, and Stock Issue movements are offered. Unsupported physical sources never appear as correctable.</p></div><span>{{ ledgerMovements().length }}</span></div>@for (movement of ledgerMovements(); track movement.id) {<article class="control-row"><div><strong>{{ movement.productSku }} · {{ movement.sourceType }}</strong><small>{{ movement.direction }} · {{ movement.quantity }} · movement {{ movement.id }}</small></div>@if (movement.correctionOfMovementId) {<span class="status-badge">Correction of {{ movement.correctionOfMovementId }}</span>} @else if (isEligibleCorrection(movement) && !hasCorrection(movement)) {<select [name]="'correction-reason-' + movement.id" [(ngModel)]="correctionReasonCodes[movement.id]"><option value="">Choose correction reason</option>@for (reason of correctionReasons(movement); track reason.id) {<option [value]="reason.code">{{ reason.code }} — {{ reason.englishName }}</option>}</select><input [name]="'correction-note-' + movement.id" [(ngModel)]="correctionNotes[movement.id]" placeholder="Optional explanation" /><button type="button" (click)="correctMovement(movement)">Correct movement</button>} @else if (hasCorrection(movement)) {<span class="status-badge">Already corrected</span>}</article>} @empty {<p class="empty-copy">No ledger movements in this warehouse.</p>}</section>
    </section>
  `,
  styles: [`.stock-control{padding:1.35rem;margin-top:1rem}.stock-control__header,.stock-control__toolbar,.list-heading,.control-row{display:flex;align-items:center;justify-content:space-between;gap:1rem}.stock-control__toolbar{border-top:1px solid #e8efec;border-bottom:1px solid #e8efec;padding:1rem 0;margin:1rem 0}.stock-control__toolbar label,.control-form label{display:grid;gap:.3rem;color:var(--muted);font-size:.76rem;font-weight:700;flex:1}.stock-control select,.stock-control input{width:100%;border:1px solid #d7e0dd;border-radius:.55rem;padding:.6rem;background:#fff}.stock-control__grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.control-form{display:grid;gap:.65rem;background:#f5f9f7;border-radius:.7rem;padding:1rem}.control-form h3{margin:0}.form-note{font-size:.76rem;color:var(--muted);line-height:1.45}.stock-control__lists{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-top:1.2rem}.stock-control__lists>section{border-top:2px solid #dce9e4;padding-top:.7rem}.list-heading h3{margin:.2rem 0}.list-heading span{color:var(--muted);font-weight:800}.control-row{border-top:1px solid #e8efec;padding:.7rem 0;align-items:flex-start;flex-wrap:wrap}.control-row>div:first-child{min-width:0;flex:1}.control-row small{display:block;color:var(--muted);margin-top:.2rem}.control-actions{display:flex;gap:.3rem;flex-wrap:wrap}.control-actions button,.count-observations button,.count-review button,.reason-row button,.ledger-panel button{border:0;background:transparent;color:#2e7263;font-weight:800;cursor:pointer}.count-observations,.count-review{display:grid;gap:.45rem;width:100%;background:#f5f9f7;padding:.7rem;border-radius:.5rem}.count-line{display:grid;grid-template-columns:1fr minmax(7rem,10rem);align-items:center;gap:.5rem;color:#29433b;font-size:.8rem}.count-line small{grid-column:1 / -1}.count-review select,.reason-row select,.reason-row input,.reason-form input,.reason-form select,.ledger-panel select,.ledger-panel input{padding:.45rem;border:1px solid #d7e0dd;border-radius:.45rem}.stock-control__error{color:#a33b34;background:#fff0ee;padding:.7rem;border-radius:.5rem}.empty-copy{color:var(--muted);font-size:.8rem}.reason-panel,.ledger-panel{margin-top:1.2rem;border-top:2px solid #dce9e4;padding-top:.7rem}.reason-form{display:grid;grid-template-columns:1fr 1.4fr 1.4fr 1fr auto;gap:.5rem;margin:.7rem 0}.reason-list{display:grid;gap:.35rem}.reason-row{display:grid;grid-template-columns:1fr 1fr 1.4fr 1.4fr auto auto auto;align-items:center;gap:.45rem;border-top:1px solid #e8efec;padding:.55rem 0}.history-list{width:100%;margin:.2rem 0 0;padding-left:1.2rem;color:var(--muted);font-size:.75rem}.ledger-panel .control-row{align-items:center}@media(max-width:1050px){.stock-control__grid,.stock-control__lists{grid-template-columns:1fr}.stock-control__toolbar{flex-wrap:wrap}.stock-control__toolbar label{min-width:14rem}.reason-form,.reason-row{grid-template-columns:1fr}.reason-row strong{margin-top:.4rem}}`],
})
export class InventoryStockControlComponent implements OnInit {
  private readonly inventory = inject(InventoryService);
  private readonly masterData = inject(MasterDataService);
  private readonly auth = inject(AuthService);
  readonly warehouses = signal<InventoryWarehouseOption[]>([]);
  readonly products = signal<ProductRecord[]>([]);
  readonly reasonCatalogue = signal<InventoryReasonCode[]>([]);
  readonly adjustmentReasons = signal<InventoryReasonCode[]>([]);
  readonly issueReasons = signal<InventoryReasonCode[]>([]);
  readonly varianceReasons = signal<InventoryReasonCode[]>([]);
  readonly adjustments = signal<InventoryAdjustment[]>([]);
  readonly counts = signal<InventoryCount[]>([]);
  readonly issues = signal<InventoryStockIssue[]>([]);
  readonly ledgerMovements = signal<InventoryMovement[]>([]);
  readonly histories = signal<Record<string, InventoryControlHistory[]>>({});
  readonly error = signal('');
  countedQuantities: Record<string, number | null> = {};
  varianceReasonCodes: Record<string, string> = {};
  correctionReasonCodes: Record<string, string> = {};
  correctionNotes: Record<string, string> = {};
  reasonDrafts: Record<string, { englishName: string; arabicName: string; category: InventoryReasonCategory }> = {};
  warehouseId = '';
  productId = '';
  countType: 'Cycle' | 'Full' = 'Cycle';
  actorId = '';
  reviewerId = '';
  newReason = { code: '', englishName: '', arabicName: '', category: 'Adjustment' as InventoryReasonCategory };
  adjustment = { direction: 'Increase' as 'Increase' | 'Decrease', quantity: 0, reasonCode: '', trackingIdentity: '' };
  issue = { destinationUseDescription: '', quantity: 0, reasonCode: '', trackingIdentity: '' };

  ngOnInit(): void { this.actorId = this.auth.session()?.actorId ?? ''; void this.load(); }
  private selectedWarehouse(): InventoryWarehouseOption | undefined { return this.warehouses().find(item => item.warehouseId === this.warehouseId); }
  private selectedProduct(): ProductRecord | undefined { return this.products().find(item => item.id === this.productId); }
  canWrite(): boolean { return !!this.selectedWarehouse() && !!this.selectedProduct(); }
  currentLines(record: InventoryCount): InventoryCountLine[] { return record.lines.filter(line => line.isCurrentRound); }
  historyFor(id: string): InventoryControlHistory[] { return this.histories()[id] ?? []; }
  private setReasonDrafts(reasons: InventoryReasonCode[]): void { for (const reason of reasons) this.reasonDrafts[reason.id] = { englishName: reason.englishName, arabicName: reason.arabicName, category: reason.category }; }
  private async load(): Promise<void> { try { const [warehouses, products] = await Promise.all([firstValueFrom(this.inventory.warehouses()), firstValueFrom(this.masterData.list('products'))]); this.warehouses.set(warehouses); this.products.set(products.filter((item): item is ProductRecord => 'sku' in item && item.isInventoryRelevant)); if (warehouses[0]) { this.warehouseId = warehouses[0].warehouseId; this.productId = this.products()[0]?.id ?? ''; await this.refresh(); } } catch { this.error.set('Unable to load stock-control data.'); } }
  async refresh(): Promise<void> { const warehouse = this.selectedWarehouse(); if (!warehouse) return; try { const filters = { warehouseId: warehouse.warehouseId, companyId: warehouse.companyId, branchId: warehouse.branchId || undefined }; const [adjustments, counts, issues, allReasons, ledger] = await Promise.all([firstValueFrom(this.inventory.adjustments(filters)), firstValueFrom(this.inventory.counts(filters)), firstValueFrom(this.inventory.stockIssues(filters)), firstValueFrom(this.inventory.reasonCodes(undefined, true)), firstValueFrom(this.inventory.ledger(filters))]); this.adjustments.set(adjustments); this.counts.set(counts); this.issues.set(issues); this.reasonCatalogue.set(allReasons); this.setReasonDrafts(allReasons); this.adjustmentReasons.set(allReasons.filter(item => item.category === 'Adjustment' && item.isActive)); this.issueReasons.set(allReasons.filter(item => item.category === 'StockIssue' && item.isActive)); this.varianceReasons.set(allReasons.filter(item => item.category === 'CountVariance' && item.isActive)); this.ledgerMovements.set(ledger); } catch { this.error.set('The server rejected this operation or the context is unavailable.'); } }
  async createReasonCode(): Promise<void> { if (!this.canWrite() || !this.newReason.code.trim() || !this.newReason.englishName.trim() || !this.newReason.arabicName.trim()) return; try { await this.inventory.createReasonCode({ code: this.newReason.code.trim(), englishName: this.newReason.englishName.trim(), arabicName: this.newReason.arabicName.trim(), category: this.newReason.category }); this.newReason = { code: '', englishName: '', arabicName: '', category: 'Adjustment' }; await this.refresh(); } catch { this.error.set('Reason code was not created.'); } }
  async updateReasonCode(reason: InventoryReasonCode): Promise<void> { const draft = this.reasonDrafts[reason.id]; if (!draft || !draft.englishName.trim() || !draft.arabicName.trim()) return; try { await this.inventory.updateReasonCode(reason.id, reason.version, { englishName: draft.englishName.trim(), arabicName: draft.arabicName.trim(), category: draft.category, isActive: reason.isActive }); await this.refresh(); } catch { this.error.set('Reason code update was rejected.'); } }
  async toggleReasonCode(reason: InventoryReasonCode): Promise<void> { const draft = this.reasonDrafts[reason.id]; if (!draft) return; try { await this.inventory.updateReasonCode(reason.id, reason.version, { englishName: draft.englishName, arabicName: draft.arabicName, category: draft.category, isActive: !reason.isActive }); await this.refresh(); } catch { this.error.set('Reason code activation change was rejected.'); } }
  async createAdjustment(): Promise<void> { const warehouse = this.selectedWarehouse(); const product = this.selectedProduct(); if (!warehouse || !product || !this.adjustment.reasonCode || this.adjustment.quantity <= 0) return; try { await this.inventory.createAdjustment({ companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, evidenceReference: null, lines: [{ productId: product.id, unitOfMeasureId: product.baseUnitOfMeasureId, direction: this.adjustment.direction, quantity: this.adjustment.quantity, reasonCode: this.adjustment.reasonCode, trackingIdentity: this.adjustment.trackingIdentity || null, evidenceReference: null }] }); this.adjustment.quantity = 0; await this.refresh(); } catch { this.error.set('Adjustment was not created.'); } }
  async submitAdjustment(record: InventoryAdjustment): Promise<void> { try { await this.inventory.submitAdjustment(record.id, record.version); await this.refresh(); } catch { this.error.set('Adjustment submit failed.'); } }
  async approveAdjustment(record: InventoryAdjustment): Promise<void> { try { await this.inventory.approveAdjustment(record.id, record.version); await this.refresh(); } catch { this.error.set('Approval failed or separation of duties blocked it.'); } }
  async rejectAdjustment(record: InventoryAdjustment): Promise<void> { try { await this.inventory.rejectAdjustment(record.id, record.version, { reason: 'Rejected during reviewer control' }); await this.refresh(); } catch { this.error.set('Adjustment rejection failed.'); } }
  async postAdjustment(record: InventoryAdjustment): Promise<void> { try { await this.inventory.postAdjustment(record.id, record.version); await this.refresh(); } catch { this.error.set('Posting failed; stock and reservation rules remain authoritative.'); } }
  async createCount(): Promise<void> { const warehouse = this.selectedWarehouse(); const product = this.selectedProduct(); if (!warehouse || !product || !this.actorId) return; try { await this.inventory.createCount({ companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, countType: this.countType, assignedCounterId: this.actorId, reviewerId: this.reviewerId.trim() || null, lines: this.countType === 'Cycle' ? [{ productId: product.id, unitOfMeasureId: product.baseUnitOfMeasureId, trackingIdentity: null }] : [] }); await this.refresh(); } catch { this.error.set('Count could not be opened.'); } }
  async submitCount(record: InventoryCount): Promise<void> { const current = this.currentLines(record); const observations = current.map(line => ({ countLineId: line.id, countedQuantity: Number(this.countedQuantities[line.id]) })).filter(item => Number.isFinite(item.countedQuantity) && item.countedQuantity >= 0); if (observations.length !== current.length) { this.error.set('Enter a physical quantity for every current count line.'); return; } try { await this.inventory.submitCount(record.id, record.version, { observations }); await this.refresh(); } catch { this.error.set('Count observations were not accepted.'); } }
  async recordVarianceReason(record: InventoryCount, line: InventoryCountLine): Promise<void> { const reasonCode = this.varianceReasonCodes[line.id]; if (!reasonCode) return; try { await this.inventory.recordCountVarianceReason(record.id, record.version, line.id, reasonCode); await this.refresh(); } catch { this.error.set('Variance reason was not recorded.'); } }
  async approveCount(record: InventoryCount): Promise<void> { try { await this.inventory.approveCount(record.id, record.version); await this.refresh(); } catch { this.error.set('Count approval failed.'); } }
  async rejectCount(record: InventoryCount): Promise<void> { try { await this.inventory.rejectCount(record.id, record.version, { reason: 'Rejected during reviewer control' }); await this.refresh(); } catch { this.error.set('Count rejection failed.'); } }
  async postCount(record: InventoryCount): Promise<void> { try { await this.inventory.postCount(record.id, record.version); await this.refresh(); } catch { this.error.set('Count finalization failed or requires a fresh snapshot.'); } }
  async recount(record: InventoryCount): Promise<void> { try { await this.inventory.recountCount(record.id, record.version, { reason: 'Reviewer requested recount' }); await this.refresh(); } catch { this.error.set('Recount request failed.'); } }
  async resnapshot(record: InventoryCount): Promise<void> { try { await this.inventory.resnapshotCount(record.id, record.version); await this.refresh(); } catch { this.error.set('Resnapshot failed.'); } }
  async createIssue(): Promise<void> { const warehouse = this.selectedWarehouse(); const product = this.selectedProduct(); if (!warehouse || !product || !this.issue.reasonCode || this.issue.quantity <= 0 || !this.issue.destinationUseDescription.trim()) return; try { await this.inventory.createStockIssue({ companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, destinationUseDescription: this.issue.destinationUseDescription.trim(), lines: [{ productId: product.id, unitOfMeasureId: product.baseUnitOfMeasureId, quantity: this.issue.quantity, reasonCode: this.issue.reasonCode, trackingIdentity: this.issue.trackingIdentity || null, evidenceReference: null }] }); this.issue.quantity = 0; await this.refresh(); } catch { this.error.set('Stock issue was not created.'); } }
  async submitIssue(record: InventoryStockIssue): Promise<void> { try { await this.inventory.submitStockIssue(record.id, record.version); await this.refresh(); } catch { this.error.set('Stock issue submit failed.'); } }
  async approveIssue(record: InventoryStockIssue): Promise<void> { try { await this.inventory.approveStockIssue(record.id, record.version); await this.refresh(); } catch { this.error.set('Stock issue approval failed.'); } }
  async rejectIssue(record: InventoryStockIssue): Promise<void> { try { await this.inventory.rejectStockIssue(record.id, record.version, { reason: 'Rejected during reviewer control' }); await this.refresh(); } catch { this.error.set('Stock issue rejection failed.'); } }
  async postIssue(record: InventoryStockIssue): Promise<void> { try { await this.inventory.postStockIssue(record.id, record.version); await this.refresh(); } catch { this.error.set('Stock issue posting failed; available stock is authoritative.'); } }
  async loadAdjustmentHistory(id: string): Promise<void> { await this.loadHistory(id, () => this.inventory.adjustmentHistory(id)); }
  async loadCountHistory(id: string): Promise<void> { await this.loadHistory(id, () => this.inventory.countHistory(id)); }
  async loadIssueHistory(id: string): Promise<void> { await this.loadHistory(id, () => this.inventory.stockIssueHistory(id)); }
  private async loadHistory(id: string, loader: () => ReturnType<InventoryService['adjustmentHistory']>): Promise<void> { try { const history = await firstValueFrom(loader()); this.histories.update(current => ({ ...current, [id]: history })); } catch { this.error.set('Lifecycle history is unavailable.'); } }
  isEligibleCorrection(movement: InventoryMovement): boolean { return movement.sourceType === 'StockAdjustment' || movement.sourceType === 'InventoryCountVariance' || movement.sourceType === 'StockIssue'; }
  hasCorrection(movement: InventoryMovement): boolean { return this.ledgerMovements().some(item => item.correctionOfMovementId === movement.id); }
  correctionReasons(movement: InventoryMovement): InventoryReasonCode[] { const category: InventoryReasonCategory = movement.sourceType === 'StockIssue' ? 'StockIssue' : movement.sourceType === 'InventoryCountVariance' ? 'CountVariance' : 'Adjustment'; return this.reasonCatalogue().filter(item => item.category === category && item.isActive); }
  async correctMovement(movement: InventoryMovement): Promise<void> { const reasonCode = this.correctionReasonCodes[movement.id]; if (!reasonCode) { this.error.set('Choose a controlled correction reason.'); return; } try { await this.inventory.correctMovement(movement.id, movement.version, reasonCode, this.correctionNotes[movement.id]?.trim() || undefined); await this.refresh(); } catch { this.error.set('Movement correction was rejected or already exists.'); } }
}
