import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../../core/auth/auth.service';
import { MasterDataService } from '../master-data/master-data.service';
import { ProductRecord } from '../master-data/master-data.models';
import { InventoryService } from './inventory.service';
import { InventoryAdjustment, InventoryCount, InventoryReasonCode, InventoryStockIssue, InventoryWarehouseOption } from './inventory.model';

@Component({
  selector: 'app-inventory-stock-control',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <section class="ui-surface stock-control" data-testid="inventory-stock-control">
      <header class="stock-control__header"><div><p class="eyebrow">{{ label('CONTROLLED OPERATIONS', 'عمليات مضبوطة') }}</p><h2>{{ label('Stock control and corrections', 'ضبط المخزون والتصحيحات') }}</h2><p class="lede">{{ label('Every posted effect becomes immutable ledger evidence. Finance valuation remains pending until MWA.', 'كل أثر مرحّل يصبح دليلاً غير قابل للتعديل. تبقى التقييمات معلقة حتى MWA.') }}</p></div><span class="status-badge status-badge--active">{{ label('Server-authorized', 'مصرح من الخادم') }}</span></header>
      <div class="stock-control__toolbar">
        <label><span>{{ label('Warehouse', 'المستودع') }}</span><select [(ngModel)]="warehouseId" (ngModelChange)="refresh()"><option value="">{{ label('Choose warehouse', 'اختر المستودع') }}</option>@for (warehouse of warehouses(); track warehouse.warehouseId) {<option [value]="warehouse.warehouseId">{{ warehouse.displayName }}</option>}</select></label>
        <label><span>{{ label('Product', 'الصنف') }}</span><select [(ngModel)]="productId"><option value="">{{ label('Choose product', 'اختر الصنف') }}</option>@for (product of products(); track product.id) {<option [value]="product.id">{{ product.sku }} — {{ product.englishName || product.arabicName }}</option>}</select></label>
        <button class="button button--quiet" type="button" (click)="refresh()">{{ label('Refresh', 'تحديث') }}</button>
      </div>
      @if (error()) { <p class="stock-control__error" role="alert">{{ error() }}</p> }
      <div class="stock-control__grid">
        <form class="control-form" (ngSubmit)="createAdjustment()"><h3>{{ label('Stock adjustment', 'تسوية مخزنية') }}</h3><label><span>{{ label('Direction', 'الاتجاه') }}</span><select name="direction" [(ngModel)]="adjustment.direction"><option value="Increase">{{ label('Increase', 'زيادة') }}</option><option value="Decrease">{{ label('Decrease', 'نقص') }}</option></select></label><label><span>{{ label('Quantity', 'الكمية') }}</span><input name="quantity" type="number" min="0.00000001" step="any" [(ngModel)]="adjustment.quantity" required /></label><label><span>{{ label('Reason', 'السبب') }}</span><select name="reason" [(ngModel)]="adjustment.reasonCode" required><option value="">{{ label('Choose reason', 'اختر السبب') }}</option>@for (reason of adjustmentReasons(); track reason.id) {<option [value]="reason.code">{{ reason.code }} — {{ reason.englishName }}</option>}</select></label><label><span>{{ label('Tracking identity (if required)', 'هوية التتبع عند الحاجة') }}</span><input name="tracking" [(ngModel)]="adjustment.trackingIdentity" /></label><button class="button button--primary" type="submit" [disabled]="!canWrite() || adjustment.quantity <= 0">{{ label('Create draft', 'إنشاء مسودة') }}</button></form>
        <form class="control-form" (ngSubmit)="createCount()"><h3>{{ label('Inventory count', 'جرد المخزون') }}</h3><label><span>{{ label('Count type', 'نوع الجرد') }}</span><select name="countType" [(ngModel)]="countType"><option value="Cycle">{{ label('Cycle count', 'جرد دوري') }}</option><option value="Full">{{ label('Full warehouse snapshot', 'لقطة كاملة للمستودع') }}</option></select></label><p class="form-note">{{ label('The server records the cutoff and expected quantity; the counter records only observations.', 'يسجل الخادم وقت القطع والكمية المتوقعة؛ ويسجل العداد الملاحظات فقط.') }}</p><button class="button button--primary" type="submit" [disabled]="!canWrite() || !productId || !actorId">{{ label('Open count', 'فتح الجرد') }}</button></form>
        <form class="control-form" (ngSubmit)="createIssue()"><h3>{{ label('Stock issue', 'صرف مخزني') }}</h3><label><span>{{ label('Destination/use', 'الجهة/الاستخدام') }}</span><input name="destination" maxlength="2048" [(ngModel)]="issue.destinationUseDescription" required /></label><label><span>{{ label('Quantity', 'الكمية') }}</span><input name="issueQuantity" type="number" min="0.00000001" step="any" [(ngModel)]="issue.quantity" required /></label><label><span>{{ label('Reason', 'السبب') }}</span><select name="issueReason" [(ngModel)]="issue.reasonCode" required><option value="">{{ label('Choose reason', 'اختر السبب') }}</option>@for (reason of issueReasons(); track reason.id) {<option [value]="reason.code">{{ reason.code }} — {{ reason.englishName }}</option>}</select></label><button class="button button--primary" type="submit" [disabled]="!canWrite() || issue.quantity <= 0">{{ label('Create draft', 'إنشاء مسودة') }}</button></form>
      </div>
      <div class="stock-control__lists">
        <section><div class="list-heading"><h3>{{ label('Adjustments', 'التسويات') }}</h3><span>{{ adjustments().length }}</span></div>@for (record of adjustments(); track record.id) {<article class="control-row"><div><strong>{{ record.lines[0]?.productSku }}</strong><small>{{ record.lines[0]?.direction }} · {{ record.lines[0]?.quantity }} · {{ record.lines[0]?.reasonCode }}</small></div><span class="status-badge">{{ record.status }}</span><div class="control-actions">@if (record.status === 'Draft') {<button type="button" (click)="submitAdjustment(record)">{{ label('Submit', 'إرسال') }}</button>} @if (record.status === 'PendingApproval') {<button type="button" (click)="approveAdjustment(record)">{{ label('Approve', 'اعتماد') }}</button>} @if (record.status === 'Approved') {<button type="button" (click)="postAdjustment(record)">{{ label('Post', 'ترحيل') }}</button>}</div></article>} @empty {<p class="empty-copy">{{ label('No adjustments in this context.', 'لا توجد تسويات في هذا السياق.') }}</p>}</section>
        <section><div class="list-heading"><h3>{{ label('Counts', 'الجرد') }}</h3><span>{{ counts().length }}</span></div>@for (record of counts(); track record.id) {<article class="control-row"><div><strong>{{ record.countType }}</strong><small>{{ record.lines.length }} {{ label('lines', 'بنود') }} · {{ record.snapshotCutoff | date:'short' }}</small></div><span class="status-badge">{{ record.status }}</span><div class="control-actions">@if (record.status === 'Draft' && record.assignedCounterId === actorId) {<button type="button" (click)="submitCount(record)">{{ label('Submit zero-variance', 'إرسال دون فرق') }}</button>} @if (record.status === 'PendingApproval') {<button type="button" (click)="approveCount(record)">{{ label('Approve', 'اعتماد') }}</button>} @if (record.status === 'Approved') {<button type="button" (click)="postCount(record)">{{ label('Post', 'ترحيل') }}</button>} @if (record.status === 'ResnapshotRequired') {<button type="button" (click)="resnapshot(record)">{{ label('Resnapshot', 'إعادة اللقطة') }}</button>}</div></article>} @empty {<p class="empty-copy">{{ label('No counts in this context.', 'لا يوجد جرد في هذا السياق.') }}</p>}</section>
        <section><div class="list-heading"><h3>{{ label('Stock issues', 'الصرف المخزني') }}</h3><span>{{ issues().length }}</span></div>@for (record of issues(); track record.id) {<article class="control-row"><div><strong>{{ record.destinationUseDescription }}</strong><small>{{ record.lines[0]?.productSku }} · {{ record.lines[0]?.quantity }} · {{ record.lines[0]?.reasonCode }}</small></div><span class="status-badge">{{ record.status }}</span><div class="control-actions">@if (record.status === 'Draft') {<button type="button" (click)="submitIssue(record)">{{ label('Submit', 'إرسال') }}</button>} @if (record.status === 'PendingApproval') {<button type="button" (click)="approveIssue(record)">{{ label('Approve', 'اعتماد') }}</button>} @if (record.status === 'Approved') {<button type="button" (click)="postIssue(record)">{{ label('Post', 'ترحيل') }}</button>}</div></article>} @empty {<p class="empty-copy">{{ label('No stock issues in this context.', 'لا يوجد صرف في هذا السياق.') }}</p>}</section>
      </div>
    </section>
  `,
  styles: [`.stock-control{padding:1.35rem;margin-top:1rem}.stock-control__header,.stock-control__toolbar,.list-heading,.control-row{display:flex;align-items:center;justify-content:space-between;gap:1rem}.stock-control__toolbar{border-top:1px solid #e8efec;border-bottom:1px solid #e8efec;padding:1rem 0;margin:1rem 0}.stock-control__toolbar label,.control-form label{display:grid;gap:.3rem;color:var(--muted);font-size:.76rem;font-weight:700;flex:1}.stock-control select,.stock-control input{width:100%;border:1px solid #d7e0dd;border-radius:.55rem;padding:.6rem;background:#fff}.stock-control__grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.control-form{display:grid;gap:.65rem;background:#f5f9f7;border-radius:.7rem;padding:1rem}.control-form h3{margin:0}.form-note{font-size:.76rem;color:var(--muted);line-height:1.45}.stock-control__lists{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-top:1.2rem}.stock-control__lists>section{border-top:2px solid #dce9e4;padding-top:.7rem}.list-heading h3{margin:.2rem 0}.list-heading span{color:var(--muted);font-weight:800}.control-row{border-top:1px solid #e8efec;padding:.7rem 0;align-items:flex-start}.control-row>div:first-child{min-width:0;flex:1}.control-row small{display:block;color:var(--muted);margin-top:.2rem}.control-actions{display:flex;gap:.3rem;flex-wrap:wrap}.control-actions button{border:0;background:transparent;color:#2e7263;font-weight:800;cursor:pointer}.stock-control__error{color:#a33b34;background:#fff0ee;padding:.7rem;border-radius:.5rem}.empty-copy{color:var(--muted);font-size:.8rem}@media(max-width:1050px){.stock-control__grid,.stock-control__lists{grid-template-columns:1fr}.stock-control__toolbar{flex-wrap:wrap}.stock-control__toolbar label{min-width:14rem}}`],
})
export class InventoryStockControlComponent implements OnInit {
  private readonly inventory = inject(InventoryService);
  private readonly masterData = inject(MasterDataService);
  private readonly auth = inject(AuthService);
  readonly warehouses = signal<InventoryWarehouseOption[]>([]); readonly products = signal<ProductRecord[]>([]); readonly adjustmentReasons = signal<InventoryReasonCode[]>([]); readonly issueReasons = signal<InventoryReasonCode[]>([]); readonly adjustments = signal<InventoryAdjustment[]>([]); readonly counts = signal<InventoryCount[]>([]); readonly issues = signal<InventoryStockIssue[]>([]); readonly error = signal('');
  warehouseId = ''; productId = ''; countType: 'Cycle' | 'Full' = 'Cycle'; actorId = ''; adjustment = { direction: 'Increase' as 'Increase' | 'Decrease', quantity: 0, reasonCode: '', trackingIdentity: '' }; issue = { destinationUseDescription: '', quantity: 0, reasonCode: '', trackingIdentity: '' };
  ngOnInit(): void { this.actorId = this.auth.session()?.actorId ?? ''; void this.load(); }
  label(en: string, ar: string): string { return document.documentElement.dir === 'rtl' ? ar : en; }
  private selectedWarehouse(): InventoryWarehouseOption | undefined { return this.warehouses().find(item => item.warehouseId === this.warehouseId); }
  private selectedProduct(): ProductRecord | undefined { return this.products().find(item => item.id === this.productId); }
  canWrite(): boolean { return !!this.selectedWarehouse() && !!this.selectedProduct(); }
  private async load(): Promise<void> { try { const [warehouses, products] = await Promise.all([firstValueFrom(this.inventory.warehouses()), firstValueFrom(this.masterData.list('products'))]); this.warehouses.set(warehouses); this.products.set(products.filter((item): item is ProductRecord => 'sku' in item && item.isInventoryRelevant)); if (warehouses[0]) { this.warehouseId = warehouses[0].warehouseId; this.productId = this.products()[0]?.id ?? ''; await this.refresh(); } } catch { this.error.set(this.label('Unable to load stock-control data.', 'تعذر تحميل بيانات ضبط المخزون.')); } }
  async refresh(): Promise<void> { const warehouse = this.selectedWarehouse(); if (!warehouse) return; try { const filters = { warehouseId: warehouse.warehouseId, companyId: warehouse.companyId, branchId: warehouse.branchId || undefined }; const [adjustments, counts, issues, adjustmentReasons, issueReasons] = await Promise.all([firstValueFrom(this.inventory.adjustments(filters)), firstValueFrom(this.inventory.counts(filters)), firstValueFrom(this.inventory.stockIssues(filters)), firstValueFrom(this.inventory.reasonCodes('Adjustment')), firstValueFrom(this.inventory.reasonCodes('StockIssue'))]); this.adjustments.set(adjustments); this.counts.set(counts); this.issues.set(issues); this.adjustmentReasons.set(adjustmentReasons); this.issueReasons.set(issueReasons); } catch { this.error.set(this.label('The server rejected this operation or the context is unavailable.', 'رفض الخادم العملية أو أن السياق غير متاح.')); } }
  async createAdjustment(): Promise<void> { const warehouse = this.selectedWarehouse(); const product = this.selectedProduct(); if (!warehouse || !product || !this.adjustment.reasonCode || this.adjustment.quantity <= 0) return; try { await this.inventory.createAdjustment({ companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, evidenceReference: null, lines: [{ productId: product.id, unitOfMeasureId: product.baseUnitOfMeasureId, direction: this.adjustment.direction, quantity: this.adjustment.quantity, reasonCode: this.adjustment.reasonCode, trackingIdentity: this.adjustment.trackingIdentity || null, evidenceReference: null }] }); this.adjustment.quantity = 0; await this.refresh(); } catch { this.error.set(this.label('Adjustment was not created.', 'لم يتم إنشاء التسوية.')); } }
  async submitAdjustment(record: InventoryAdjustment): Promise<void> { try { await this.inventory.submitAdjustment(record.id, record.version); await this.refresh(); } catch { this.error.set(this.label('Adjustment submit failed.', 'فشل إرسال التسوية.')); } }
  async approveAdjustment(record: InventoryAdjustment): Promise<void> { try { await this.inventory.approveAdjustment(record.id, record.version); await this.refresh(); } catch { this.error.set(this.label('Approval failed or separation of duties blocked it.', 'فشل الاعتماد أو تم حظر فصل الصلاحيات.')); } }
  async postAdjustment(record: InventoryAdjustment): Promise<void> { try { await this.inventory.postAdjustment(record.id, record.version); await this.refresh(); } catch { this.error.set(this.label('Posting failed; stock and reservation rules remain authoritative.', 'فشل الترحيل؛ تبقى قواعد المخزون والحجز هي المرجع.')); } }
  async createCount(): Promise<void> { const warehouse = this.selectedWarehouse(); const product = this.selectedProduct(); if (!warehouse || !product || !this.actorId) return; try { await this.inventory.createCount({ companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, countType: this.countType, assignedCounterId: this.actorId, reviewerId: null, lines: this.countType === 'Cycle' ? [{ productId: product.id, unitOfMeasureId: product.baseUnitOfMeasureId, trackingIdentity: null }] : [] }); await this.refresh(); } catch { this.error.set(this.label('Count could not be opened.', 'تعذر فتح الجرد.')); } }
  async submitCount(record: InventoryCount): Promise<void> { const observations = record.lines.filter(line => line.isCurrentRound && line.expectedQuantity !== null).map(line => ({ countLineId: line.id, countedQuantity: line.expectedQuantity ?? 0 })); try { await this.inventory.submitCount(record.id, record.version, { observations }); await this.refresh(); } catch { this.error.set(this.label('Count observations were not accepted.', 'لم تقبل ملاحظات الجرد.')); } }
  async approveCount(record: InventoryCount): Promise<void> { try { await this.inventory.approveCount(record.id, record.version); await this.refresh(); } catch { this.error.set(this.label('Count approval failed.', 'فشل اعتماد الجرد.')); } }
  async postCount(record: InventoryCount): Promise<void> { try { await this.inventory.postCount(record.id, record.version); await this.refresh(); } catch { this.error.set(this.label('Count posting failed or requires a fresh snapshot.', 'فشل ترحيل الجرد أو تتطلب العملية لقطة جديدة.')); } }
  async resnapshot(record: InventoryCount): Promise<void> { try { await this.inventory.resnapshotCount(record.id, record.version); await this.refresh(); } catch { this.error.set(this.label('Resnapshot failed.', 'فشلت إعادة اللقطة.')); } }
  async createIssue(): Promise<void> { const warehouse = this.selectedWarehouse(); const product = this.selectedProduct(); if (!warehouse || !product || !this.issue.reasonCode || this.issue.quantity <= 0 || !this.issue.destinationUseDescription.trim()) return; try { await this.inventory.createStockIssue({ companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, destinationUseDescription: this.issue.destinationUseDescription.trim(), lines: [{ productId: product.id, unitOfMeasureId: product.baseUnitOfMeasureId, quantity: this.issue.quantity, reasonCode: this.issue.reasonCode, trackingIdentity: this.issue.trackingIdentity || null, evidenceReference: null }] }); this.issue.quantity = 0; await this.refresh(); } catch { this.error.set(this.label('Stock issue was not created.', 'لم يتم إنشاء الصرف المخزني.')); } }
  async submitIssue(record: InventoryStockIssue): Promise<void> { try { await this.inventory.submitStockIssue(record.id, record.version); await this.refresh(); } catch { this.error.set(this.label('Stock issue submit failed.', 'فشل إرسال الصرف.')); } }
  async approveIssue(record: InventoryStockIssue): Promise<void> { try { await this.inventory.approveStockIssue(record.id, record.version); await this.refresh(); } catch { this.error.set(this.label('Stock issue approval failed.', 'فشل اعتماد الصرف.')); } }
  async postIssue(record: InventoryStockIssue): Promise<void> { try { await this.inventory.postStockIssue(record.id, record.version); await this.refresh(); } catch { this.error.set(this.label('Stock issue posting failed; available stock is authoritative.', 'فشل ترحيل الصرف؛ الرصيد المتاح هو المرجع.')); } }
}
