import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../../core/auth/auth.service';
import { LanguageService, TranslationKey } from '../../core/i18n/language.service';
import { MasterDataService } from '../master-data/master-data.service';
import { ProductRecord } from '../master-data/master-data.models';
import { InventoryService } from './inventory.service';
import { InventoryAdjustment, InventoryControlHistory, InventoryCount, InventoryCountLine, InventoryMovement, InventoryReasonCategory, InventoryReasonCode, InventoryStockIssue, InventoryWarehouseOption } from './inventory.model';

type StockControlLanguage = 'en' | 'ar';
const stockControlTranslations: Record<StockControlLanguage, Record<string, string>> = {
  en: {
    stockControlKicker: 'Controlled operations', stockControlTitle: 'Stock Control and Corrections', stockControlLead: 'Posted movements become immutable ledger evidence. Financial valuation remains pending until MWA.', stockControlServerAuthorized: 'Server-authorized', stockControlProduct: 'Product', stockControlReasonCatalogue: 'Reason catalogue', stockControlReasonCatalogueLead: 'Tenant-owned bilingual codes. Inactive codes remain visible in history but are unavailable to new documents.', stockControlCreateReason: 'Create reason', stockControlCountVariance: 'Count variance', stockControlStockIssue: 'Stock issue', stockControlSave: 'Save', stockControlActivate: 'Activate', stockControlDeactivate: 'Deactivate', stockControlNoReasonCodes: 'No reason codes configured.',
    stockControlAdjustment: 'Stock adjustment', stockControlDirection: 'Direction', stockControlIncrease: 'Increase', stockControlDecrease: 'Decrease', stockControlChooseReason: 'Choose reason', stockControlTrackingOptional: 'Tracking identity (optional)', stockControlCreateDraft: 'Create draft', stockControlCount: 'Stock count', stockControlCountType: 'Count type', stockControlCycleCount: 'Cycle count', stockControlFullSnapshot: 'Full warehouse snapshot', stockControlCounter: 'Counter', stockControlReviewerOptional: 'Reviewer (optional)', stockControlReviewerHint: 'Server-approved reviewer identifier', stockControlCountInstruction: 'The server records the snapshot boundary and expected quantity. The counter records physical observations only.', stockControlOpenCount: 'Open count', stockControlAdjustments: 'Adjustments', stockControlCounts: 'Counts', stockControlIssues: 'Stock issues', stockControlSubmit: 'Submit', stockControlApprove: 'Approve', stockControlReject: 'Reject', stockControlPost: 'Post', stockControlFinalize: 'Finalize', stockControlRequestRecount: 'Request recount',
    stockControlHistory: 'History', stockControlExpected: 'Expected', stockControlCounted: 'Counted', stockControlVariance: 'Variance', stockControlPhysicalQuantity: 'Enter the physical quantity. Expected quantity is intentionally hidden.', stockControlRecordReason: 'Record reason', stockControlNoAdjustments: 'No adjustments in this context.', stockControlNoCounts: 'No counts in this context.', stockControlNoIssues: 'No stock issues in this context.', stockControlEligibleCorrections: 'Eligible corrections', stockControlEligibleCorrectionsLead: 'Only posted stock adjustments, count variances, and stock issues within MESP-130 are shown. Unsupported source movements are not offered for correction.', stockControlCorrectionOf: 'Correction of', stockControlAlreadyCorrected: 'Already corrected', stockControlOptionalExplanation: 'Optional explanation', stockControlCorrectMovement: 'Correct movement', stockControlReason: 'Reason', stockControlResnapshot: 'Re-snapshot', stockControlNoLedgerMovements: 'No ledger movements in this warehouse.', stockControlWarehouse: 'Warehouse', stockControlChooseWarehouse: 'Choose warehouse', stockControlChooseProduct: 'Choose product', stockControlDestinationUse: 'Destination / use', stockControlLines: 'lines', stockControlRound: 'round', stockControlMovement: 'movement', stockControlMovementStockAdjustment: 'Stock adjustment', stockControlMovementCountVariance: 'Count variance', stockControlMovementStockIssue: 'Stock issue', stockControlSubmitObservations: 'Submit observations', stockControlPhysicalQuantityRequired: 'Enter the physical quantity for every current count line.', stockControlReviewerRejectionReason: 'Rejected during reviewer control', stockControlReviewerRecountReason: 'Reviewer requested a recount',
    stockControlLoadFailed: 'Stock Control data could not be loaded.', stockControlContextUnavailable: 'The server rejected the operation or the context is unavailable.', stockControlReasonCreateFailed: 'The reason code was not created.', stockControlReasonUpdateFailed: 'The reason code update was rejected.', stockControlReasonToggleFailed: 'The reason code activation change was rejected.', stockControlAdjustmentCreateFailed: 'The adjustment was not created.', stockControlAdjustmentSubmitFailed: 'The adjustment could not be submitted.', stockControlApprovalFailed: 'Approval failed or segregation of duties blocked it.', stockControlAdjustmentRejectFailed: 'The adjustment rejection failed.', stockControlAdjustmentPostFailed: 'Posting failed; stock and reservation rules remain authoritative.', stockControlCountCreateFailed: 'The count could not be opened.', stockControlCountObservationFailed: 'The count observations were not accepted.', stockControlVarianceReasonFailed: 'The variance reason was not recorded.', stockControlCountApprovalFailed: 'Count approval failed.', stockControlCountRejectFailed: 'Count rejection failed.', stockControlCountPostFailed: 'Count finalization failed or requires a new snapshot.', stockControlRecountFailed: 'The recount request failed.', stockControlResnapshotFailed: 'The re-snapshot failed.', stockControlIssueCreateFailed: 'The stock issue was not created.', stockControlIssueSubmitFailed: 'The stock issue could not be submitted.', stockControlIssueApprovalFailed: 'Stock issue approval failed.', stockControlIssueRejectFailed: 'Stock issue rejection failed.', stockControlIssuePostFailed: 'Stock issue posting failed; available quantity is authoritative.', stockControlHistoryUnavailable: 'Operational history is unavailable.', stockControlCorrectionReasonRequired: 'Choose a controlled correction reason.', stockControlCorrectionRejected: 'The movement correction was rejected or already exists.',
    stockControlStatusDraft: 'Draft', stockControlStatusSubmitted: 'Submitted', stockControlStatusPendingApproval: 'Pending approval', stockControlStatusApproved: 'Approved', stockControlStatusRejected: 'Rejected', stockControlStatusReturnedForChange: 'Returned for change', stockControlStatusPosted: 'Posted', stockControlStatusCorrected: 'Corrected', stockControlStatusRecountRequired: 'Recount required', stockControlStatusResnapshotRequired: 'Re-snapshot required', stockControlStatusBlocked: 'Blocked', stockControlHistoryCreated: 'Created', stockControlHistorySubmitted: 'Submitted', stockControlHistoryApproved: 'Approved', stockControlHistoryRejected: 'Rejected', stockControlHistoryReturnedForChange: 'Returned for change', stockControlHistoryPosted: 'Posted', stockControlHistoryPostBlocked: 'Posting blocked', stockControlHistoryCorrected: 'Corrected', stockControlHistorySnapshot: 'Snapshot', stockControlHistoryCountSubmitted: 'Count submitted', stockControlHistoryRecountRequested: 'Recount requested', stockControlHistoryResnapshot: 'Re-snapshot', stockControlHistoryVarianceReasonRecorded: 'Variance reason recorded', stockControlHistoryAuthorizationDenied: 'Authorization denied', stockControlHistoryTrackingRejected: 'Tracking rejected', stockControlHistoryIdempotencyConflict: 'Idempotency conflict', stockControlHistoryConcurrencyConflict: 'Concurrency conflict'
  },
  ar: {
    stockControlKicker: 'عمليات مضبوطة', stockControlTitle: 'التحكم في المخزون والتصحيحات', stockControlLead: 'تصبح الحركات المرحلة أدلة دفتر أستاذ غير قابلة للتغيير. يظل التقييم المالي معلقًا حتى MWA.', stockControlServerAuthorized: 'معتمد من الخادم', stockControlProduct: 'المنتج', stockControlReasonCatalogue: 'دليل الأسباب', stockControlReasonCatalogueLead: 'رموز ثنائية اللغة مملوكة للمستأجر. تظل الرموز غير النشطة ظاهرة في السجل لكنها غير متاحة للمستندات الجديدة.', stockControlCreateReason: 'إنشاء سبب', stockControlCountVariance: 'فرق الجرد', stockControlStockIssue: 'صرف مخزني', stockControlSave: 'حفظ', stockControlActivate: 'تنشيط', stockControlDeactivate: 'إلغاء التنشيط', stockControlNoReasonCodes: 'لا توجد رموز أسباب مهيأة.',
    stockControlAdjustment: 'تسوية مخزنية', stockControlDirection: 'الاتجاه', stockControlIncrease: 'زيادة', stockControlDecrease: 'نقص', stockControlChooseReason: 'اختر السبب', stockControlTrackingOptional: 'هوية التتبع (اختياري)', stockControlCreateDraft: 'إنشاء مسودة', stockControlCount: 'جرد المخزون', stockControlCountType: 'نوع الجرد', stockControlCycleCount: 'جرد دوري', stockControlFullSnapshot: 'لقطة كاملة للمستودع', stockControlCounter: 'العداد', stockControlReviewerOptional: 'المراجع (اختياري)', stockControlReviewerHint: 'معرّف مراجع معتمد من الخادم', stockControlCountInstruction: 'يسجل الخادم حد اللقطة والكمية المتوقعة. يسجل العداد الملاحظات الفعلية فقط.', stockControlOpenCount: 'فتح الجرد', stockControlAdjustments: 'التسويات', stockControlCounts: 'الجرد', stockControlIssues: 'الصرف المخزني', stockControlSubmit: 'إرسال', stockControlApprove: 'موافقة', stockControlReject: 'رفض', stockControlPost: 'ترحيل', stockControlFinalize: 'إنهاء', stockControlRequestRecount: 'طلب إعادة الجرد',
    stockControlHistory: 'السجل التاريخي', stockControlExpected: 'المتوقع', stockControlCounted: 'المعدود', stockControlVariance: 'الفرق', stockControlPhysicalQuantity: 'أدخل الكمية الفعلية. لا تظهر الكمية المتوقعة عمدًا.', stockControlRecordReason: 'تسجيل السبب', stockControlNoAdjustments: 'لا توجد تسويات في هذا السياق.', stockControlNoCounts: 'لا توجد عمليات جرد في هذا السياق.', stockControlNoIssues: 'لا توجد عمليات صرف مخزني في هذا السياق.', stockControlEligibleCorrections: 'التصحيحات المؤهلة', stockControlEligibleCorrectionsLead: 'تظهر فقط حركات التسوية المخزنية وفروقات الجرد والصرف المخزني المرحلة ضمن MESP-130. لا تظهر المصادر غير المدعومة للتصحيح.', stockControlCorrectionOf: 'تصحيح لـ', stockControlAlreadyCorrected: 'تم تصحيحه بالفعل', stockControlOptionalExplanation: 'شرح اختياري', stockControlCorrectMovement: 'تصحيح الحركة', stockControlReason: 'السبب', stockControlResnapshot: 'إعادة لقطة', stockControlNoLedgerMovements: 'لا توجد حركات دفتر أستاذ في هذا المستودع.', stockControlWarehouse: 'المستودع', stockControlChooseWarehouse: 'اختر المستودع', stockControlChooseProduct: 'اختر المنتج', stockControlDestinationUse: 'الجهة / الاستخدام', stockControlLines: 'أسطر', stockControlRound: 'جولة', stockControlMovement: 'حركة', stockControlMovementStockAdjustment: 'تسوية مخزنية', stockControlMovementCountVariance: 'فرق جرد', stockControlMovementStockIssue: 'صرف مخزني', stockControlSubmitObservations: 'إرسال الملاحظات', stockControlPhysicalQuantityRequired: 'أدخل الكمية الفعلية لكل سطر جرد حالي.', stockControlReviewerRejectionReason: 'رُفض أثناء ضابط المراجعة', stockControlReviewerRecountReason: 'طلب المراجع إعادة الجرد',
    stockControlLoadFailed: 'تعذر تحميل بيانات التحكم في المخزون.', stockControlContextUnavailable: 'رفض الخادم العملية أو أن السياق غير متاح.', stockControlReasonCreateFailed: 'لم يتم إنشاء رمز السبب.', stockControlReasonUpdateFailed: 'رُفض تحديث رمز السبب.', stockControlReasonToggleFailed: 'رُفض تغيير تنشيط رمز السبب.', stockControlAdjustmentCreateFailed: 'لم يتم إنشاء التسوية.', stockControlAdjustmentSubmitFailed: 'فشل إرسال التسوية.', stockControlApprovalFailed: 'فشلت الموافقة أو منعها فصل الصلاحيات.', stockControlAdjustmentRejectFailed: 'فشل رفض التسوية.', stockControlAdjustmentPostFailed: 'فشل الترحيل؛ تظل قواعد المخزون والحجز هي المرجع.', stockControlCountCreateFailed: 'تعذر فتح الجرد.', stockControlCountObservationFailed: 'لم تُقبل ملاحظات الجرد.', stockControlVarianceReasonFailed: 'لم يتم تسجيل سبب الفرق.', stockControlCountApprovalFailed: 'فشلت الموافقة على الجرد.', stockControlCountRejectFailed: 'فشل رفض الجرد.', stockControlCountPostFailed: 'فشل إنهاء الجرد أو يتطلب لقطة جديدة.', stockControlRecountFailed: 'فشل طلب إعادة الجرد.', stockControlResnapshotFailed: 'فشلت إعادة اللقطة.', stockControlIssueCreateFailed: 'لم يتم إنشاء الصرف المخزني.', stockControlIssueSubmitFailed: 'فشل إرسال الصرف المخزني.', stockControlIssueApprovalFailed: 'فشلت الموافقة على الصرف المخزني.', stockControlIssueRejectFailed: 'فشل رفض الصرف المخزني.', stockControlIssuePostFailed: 'فشل ترحيل الصرف المخزني؛ الكمية المتاحة هي المرجع.', stockControlHistoryUnavailable: 'السجل التشغيلي غير متاح.', stockControlCorrectionReasonRequired: 'اختر سبب تصحيح مضبوطًا.', stockControlCorrectionRejected: 'رُفض تصحيح الحركة أو أنه موجود بالفعل.',
    stockControlStatusDraft: 'مسودة', stockControlStatusSubmitted: 'مرسل', stockControlStatusPendingApproval: 'بانتظار الموافقة', stockControlStatusApproved: 'موافق عليه', stockControlStatusRejected: 'مرفوض', stockControlStatusReturnedForChange: 'معاد للتعديل', stockControlStatusPosted: 'مرحّل', stockControlStatusCorrected: 'مصحح', stockControlStatusRecountRequired: 'تتطلب إعادة الجرد', stockControlStatusResnapshotRequired: 'تتطلب لقطة جديدة', stockControlStatusBlocked: 'محظور', stockControlHistoryCreated: 'تم الإنشاء', stockControlHistorySubmitted: 'تم الإرسال', stockControlHistoryApproved: 'تمت الموافقة', stockControlHistoryRejected: 'تم الرفض', stockControlHistoryReturnedForChange: 'أعيد للتعديل', stockControlHistoryPosted: 'تم الترحيل', stockControlHistoryPostBlocked: 'حُظر الترحيل', stockControlHistoryCorrected: 'تم التصحيح', stockControlHistorySnapshot: 'لقطة', stockControlHistoryCountSubmitted: 'تم إرسال الجرد', stockControlHistoryRecountRequested: 'طُلبت إعادة الجرد', stockControlHistoryResnapshot: 'إعادة لقطة', stockControlHistoryVarianceReasonRecorded: 'تم تسجيل سبب الفرق', stockControlHistoryAuthorizationDenied: 'رُفض التفويض', stockControlHistoryTrackingRejected: 'رُفض التتبع', stockControlHistoryIdempotencyConflict: 'تعارض منع التكرار', stockControlHistoryConcurrencyConflict: 'تعارض التزامن'
  }
};

@Component({
  selector: 'app-inventory-stock-control',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <section class="ui-surface stock-control" data-testid="inventory-stock-control">
      <header class="stock-control__header"><div><p class="eyebrow">{{ language.text('stockControlKicker') }}</p><h2>{{ language.text('stockControlTitle') }}</h2><p class="lede">{{ language.text('stockControlLead') }}</p></div><span class="status-badge status-badge--active">{{ language.text('stockControlServerAuthorized') }}</span></header>
      <div class="stock-control__toolbar">
        <label><span>{{ language.text('stockControlWarehouse') }}</span><select [(ngModel)]="warehouseId" (ngModelChange)="refresh()"><option value="">{{ language.text('stockControlChooseWarehouse') }}</option>@for (warehouse of warehouses(); track warehouse.warehouseId) {<option [value]="warehouse.warehouseId">{{ warehouse.displayName }}</option>}</select></label>
        <label><span>{{ language.text('stockControlProduct') }}</span><select [(ngModel)]="productId"><option value="">{{ language.text('stockControlChooseProduct') }}</option>@for (product of products(); track product.id) {<option [value]="product.id">{{ product.sku }} — {{ productName(product) }}</option>}</select></label>
        <button class="button button--quiet" type="button" (click)="refresh()">{{ language.text('refresh') }}</button>
      </div>
      @if (error()) { <p class="stock-control__error" role="alert">{{ error() }}</p> }

      <section class="reason-panel">
        <div class="list-heading"><div><h3>{{ language.text('stockControlReasonCatalogue') }}</h3><p class="form-note">{{ language.text('stockControlReasonCatalogueLead') }}</p></div><span>{{ reasonCatalogue().length }}</span></div>
        <form class="reason-form" (ngSubmit)="createReasonCode()"><input name="reasonCode" [placeholder]="language.text('code')" [(ngModel)]="newReason.code" required /><input name="reasonEnglish" [placeholder]="language.text('englishName')" [(ngModel)]="newReason.englishName" required /><input name="reasonArabic" dir="rtl" [placeholder]="language.text('arabicName')" [(ngModel)]="newReason.arabicName" required /><select name="reasonCategory" [(ngModel)]="newReason.category"><option value="Adjustment">{{ language.text('stockControlAdjustment') }}</option><option value="CountVariance">{{ language.text('stockControlCountVariance') }}</option><option value="StockIssue">{{ language.text('stockControlStockIssue') }}</option></select><button class="button button--primary" type="submit" [disabled]="!canWrite() || !newReason.code.trim() || !newReason.englishName.trim() || !newReason.arabicName.trim()">{{ language.text('stockControlCreateReason') }}</button></form>
        <div class="reason-list">@for (reason of reasonCatalogue(); track reason.id) {<article class="reason-row"><strong>{{ reason.code }}</strong><select [name]="'reason-category-' + reason.id" [(ngModel)]="reasonDrafts[reason.id].category"><option value="Adjustment">{{ language.text('stockControlAdjustment') }}</option><option value="CountVariance">{{ language.text('stockControlCountVariance') }}</option><option value="StockIssue">{{ language.text('stockControlStockIssue') }}</option></select><input [name]="'reason-en-' + reason.id" [(ngModel)]="reasonDrafts[reason.id].englishName" /><input dir="rtl" [name]="'reason-ar-' + reason.id" [(ngModel)]="reasonDrafts[reason.id].arabicName" /><span class="status-badge">{{ language.text(reason.isActive ? 'active' : 'inactiveStatus') }}</span><button type="button" (click)="updateReasonCode(reason)">{{ language.text('stockControlSave') }}</button><button type="button" (click)="toggleReasonCode(reason)">{{ language.text(reason.isActive ? 'stockControlDeactivate' : 'stockControlActivate') }}</button></article>} @empty {<p class="empty-copy">{{ language.text('stockControlNoReasonCodes') }}</p>}</div>
      </section>

      <div class="stock-control__grid">
        <form class="control-form" (ngSubmit)="createAdjustment()"><h3>{{ language.text('stockControlAdjustment') }}</h3><label><span>{{ language.text('stockControlDirection') }}</span><select name="direction" [(ngModel)]="adjustment.direction"><option value="Increase">{{ language.text('stockControlIncrease') }}</option><option value="Decrease">{{ language.text('stockControlDecrease') }}</option></select></label><label><span>{{ language.text('quantity') }}</span><input name="quantity" type="number" min="0.00000001" step="any" [(ngModel)]="adjustment.quantity" required /></label><label><span>{{ language.text('stockControlReason') }}</span><select name="reason" [(ngModel)]="adjustment.reasonCode" required><option value="">{{ language.text('stockControlChooseReason') }}</option>@for (reason of adjustmentReasons(); track reason.id) {<option [value]="reason.code">{{ reason.code }} — {{ reasonName(reason) }}</option>}</select></label><label><span>{{ language.text('stockControlTrackingOptional') }}</span><input name="tracking" [(ngModel)]="adjustment.trackingIdentity" /></label><button class="button button--primary" type="submit" [disabled]="!canWrite() || adjustment.quantity <= 0">{{ language.text('stockControlCreateDraft') }}</button></form>
        <form class="control-form" (ngSubmit)="createCount()"><h3>{{ language.text('stockControlCount') }}</h3><label><span>{{ language.text('stockControlCountType') }}</span><select name="countType" [(ngModel)]="countType"><option value="Cycle">{{ language.text('stockControlCycleCount') }}</option><option value="Full">{{ language.text('stockControlFullSnapshot') }}</option></select></label><label><span>{{ language.text('stockControlCounter') }}</span><input name="counter" [value]="actorId" readonly /></label><label><span>{{ language.text('stockControlReviewerOptional') }}</span><input name="reviewer" [(ngModel)]="reviewerId" [placeholder]="language.text('stockControlReviewerHint')" /></label><p class="form-note">{{ language.text('stockControlCountInstruction') }}</p><button class="button button--primary" type="submit" [disabled]="!canWrite() || !productId || !actorId">{{ language.text('stockControlOpenCount') }}</button></form>
        <form class="control-form" (ngSubmit)="createIssue()"><h3>{{ language.text('stockControlStockIssue') }}</h3><label><span>{{ language.text('stockControlDestinationUse') }}</span><input name="destination" maxlength="2048" [(ngModel)]="issue.destinationUseDescription" required /></label><label><span>{{ language.text('quantity') }}</span><input name="issueQuantity" type="number" min="0.00000001" step="any" [(ngModel)]="issue.quantity" required /></label><label><span>{{ language.text('stockControlReason') }}</span><select name="issueReason" [(ngModel)]="issue.reasonCode" required><option value="">{{ language.text('stockControlChooseReason') }}</option>@for (reason of issueReasons(); track reason.id) {<option [value]="reason.code">{{ reason.code }} — {{ reasonName(reason) }}</option>}</select></label><label><span>{{ language.text('stockControlTrackingOptional') }}</span><input name="issueTracking" [(ngModel)]="issue.trackingIdentity" /></label><button class="button button--primary" type="submit" [disabled]="!canWrite() || issue.quantity <= 0">{{ language.text('stockControlCreateDraft') }}</button></form>
      </div>

      <div class="stock-control__lists">
        <section><div class="list-heading"><h3>{{ language.text('stockControlAdjustments') }}</h3><span>{{ adjustments().length }}</span></div>@for (record of adjustments(); track record.id) {<article class="control-row"><div><strong>{{ record.lines[0]?.productSku }}</strong><small>{{ directionLabel(record.lines[0]?.direction) }} · {{ record.lines[0]?.quantity }} · {{ record.lines[0]?.reasonCode }}</small></div><span class="status-badge">{{ statusLabel(record.status) }}</span><div class="control-actions">@if (record.status === 'Draft') {<button type="button" (click)="submitAdjustment(record)">{{ language.text('stockControlSubmit') }}</button>} @if (record.status === 'PendingApproval') {<button type="button" (click)="approveAdjustment(record)">{{ language.text('stockControlApprove') }}</button><button type="button" (click)="rejectAdjustment(record)">{{ language.text('stockControlReject') }}</button>} @if (record.status === 'Approved') {<button type="button" (click)="postAdjustment(record)">{{ language.text('stockControlPost') }}</button>}<button type="button" (click)="loadAdjustmentHistory(record.id)">{{ language.text('stockControlHistory') }}</button></div>@if (historyFor(record.id).length) {<ol class="history-list">@for (event of historyFor(record.id); track event.id) {<li>{{ historyActionLabel(event.action) }} · {{ statusLabel(event.fromStatus) }} → {{ statusLabel(event.toStatus) }} · {{ event.occurredAt | date:'short' }}</li>}</ol>}</article>} @empty {<p class="empty-copy">{{ language.text('stockControlNoAdjustments') }}</p>}</section>
        <section><div class="list-heading"><h3>{{ language.text('stockControlCounts') }}</h3><span>{{ counts().length }}</span></div>@for (record of counts(); track record.id) {<article class="control-row count-row"><div><strong>{{ countTypeLabel(record.countType) }} · {{ language.text('stockControlRound') }} {{ record.currentRoundGeneration }}</strong><small>{{ record.lines.length }} {{ language.text('stockControlLines') }} · {{ record.snapshotCutoff | date:'short' }}</small></div><span class="status-badge">{{ statusLabel(record.status) }}</span>
          @if (record.status === 'Draft' && record.assignedCounterId === actorId) {<div class="count-observations"><p class="form-note">{{ language.text('stockControlPhysicalQuantity') }}</p>@for (line of currentLines(record); track line.id) {<label class="count-line"><span>{{ line.productSku }} · {{ line.unitOfMeasureCode }}@if (line.trackingIdentity) { · {{ line.trackingIdentity }}}</span><input type="number" min="0" step="any" [name]="'count-' + line.id" [(ngModel)]="countedQuantities[line.id]" required /></label>}<button type="button" (click)="submitCount(record)">{{ language.text('stockControlSubmitObservations') }}</button></div>}
          @if (record.status !== 'Draft' || record.assignedCounterId !== actorId) {<div class="count-review">@for (line of currentLines(record); track line.id) {<div class="count-line"><span>{{ line.productSku }} · {{ line.unitOfMeasureCode }}</span><small>{{ language.text('stockControlExpected') }}: {{ line.expectedQuantity ?? '—' }} · {{ language.text('stockControlCounted') }}: {{ line.countedQuantity ?? '—' }} · {{ language.text('stockControlVariance') }}: {{ line.variance ?? '—' }}</small>@if (record.status === 'PendingApproval' && line.variance !== null && line.variance !== 0 && !line.varianceReasonCode) {<select [name]="'variance-' + line.id" [(ngModel)]="varianceReasonCodes[line.id]"><option value="">{{ language.text('stockControlChooseReason') }}</option>@for (reason of varianceReasons(); track reason.id) {<option [value]="reason.code">{{ reason.code }} — {{ reasonName(reason) }}</option>}</select><button type="button" (click)="recordVarianceReason(record, line)">{{ language.text('stockControlRecordReason') }}</button>}</div>}</div>}
          <div class="control-actions">@if (record.status === 'PendingApproval') {<button type="button" (click)="approveCount(record)">{{ language.text('stockControlApprove') }}</button><button type="button" (click)="rejectCount(record)">{{ language.text('stockControlReject') }}</button>} @if (record.status === 'Submitted') {<button type="button" (click)="postCount(record)">{{ language.text('stockControlFinalize') }}</button>} @if (record.status === 'Approved') {<button type="button" (click)="postCount(record)">{{ language.text('stockControlPost') }}</button>} @if (record.status === 'PendingApproval' || record.status === 'Approved') {<button type="button" (click)="recount(record)">{{ language.text('stockControlRequestRecount') }}</button>} @if (record.status === 'ResnapshotRequired') {<button type="button" (click)="resnapshot(record)">{{ language.text('stockControlResnapshot') }}</button>}<button type="button" (click)="loadCountHistory(record.id)">{{ language.text('stockControlHistory') }}</button></div>@if (historyFor(record.id).length) {<ol class="history-list">@for (event of historyFor(record.id); track event.id) {<li>{{ historyActionLabel(event.action) }} · {{ statusLabel(event.fromStatus) }} → {{ statusLabel(event.toStatus) }} · {{ event.occurredAt | date:'short' }}</li>}</ol>}</article>} @empty {<p class="empty-copy">{{ language.text('stockControlNoCounts') }}</p>}</section>
        <section><div class="list-heading"><h3>{{ language.text('stockControlIssues') }}</h3><span>{{ issues().length }}</span></div>@for (record of issues(); track record.id) {<article class="control-row"><div><strong>{{ record.destinationUseDescription }}</strong><small>{{ record.lines[0]?.productSku }} · {{ record.lines[0]?.quantity }} · {{ record.lines[0]?.reasonCode }}</small></div><span class="status-badge">{{ statusLabel(record.status) }}</span><div class="control-actions">@if (record.status === 'Draft') {<button type="button" (click)="submitIssue(record)">{{ language.text('stockControlSubmit') }}</button>} @if (record.status === 'PendingApproval') {<button type="button" (click)="approveIssue(record)">{{ language.text('stockControlApprove') }}</button><button type="button" (click)="rejectIssue(record)">{{ language.text('stockControlReject') }}</button>} @if (record.status === 'Approved') {<button type="button" (click)="postIssue(record)">{{ language.text('stockControlPost') }}</button>}<button type="button" (click)="loadIssueHistory(record.id)">{{ language.text('stockControlHistory') }}</button></div>@if (historyFor(record.id).length) {<ol class="history-list">@for (event of historyFor(record.id); track event.id) {<li>{{ historyActionLabel(event.action) }} · {{ statusLabel(event.fromStatus) }} → {{ statusLabel(event.toStatus) }} · {{ event.occurredAt | date:'short' }}</li>}</ol>}</article>} @empty {<p class="empty-copy">{{ language.text('stockControlNoIssues') }}</p>}</section>
      </div>

      <section class="ledger-panel"><div class="list-heading"><div><h3>{{ language.text('stockControlEligibleCorrections') }}</h3><p class="form-note">{{ language.text('stockControlEligibleCorrectionsLead') }}</p></div><span>{{ ledgerMovements().length }}</span></div>@for (movement of ledgerMovements(); track movement.id) {<article class="control-row"><div><strong>{{ movement.productSku }} · {{ sourceTypeLabel(movement.sourceType) }}</strong><small>{{ directionLabel(movement.direction) }} · {{ movement.quantity }} · {{ language.text('stockControlMovement') }} {{ movement.id }}</small></div>@if (movement.correctionOfMovementId) {<span class="status-badge">{{ language.text('stockControlCorrectionOf') }} {{ movement.correctionOfMovementId }}</span>} @else if (isEligibleCorrection(movement) && !hasCorrection(movement)) {<select [name]="'correction-reason-' + movement.id" [(ngModel)]="correctionReasonCodes[movement.id]"><option value="">{{ language.text('stockControlChooseReason') }}</option>@for (reason of correctionReasons(movement); track reason.id) {<option [value]="reason.code">{{ reason.code }} — {{ reasonName(reason) }}</option>}</select><input [name]="'correction-note-' + movement.id" [(ngModel)]="correctionNotes[movement.id]" [placeholder]="language.text('stockControlOptionalExplanation')" /><button type="button" (click)="correctMovement(movement)">{{ language.text('stockControlCorrectMovement') }}</button>} @else if (hasCorrection(movement)) {<span class="status-badge">{{ language.text('stockControlAlreadyCorrected') }}</span>}</article>} @empty {<p class="empty-copy">{{ language.text('stockControlNoLedgerMovements') }}</p>}</section>
    </section>
  `,
  styles: [`.stock-control{padding:1.35rem;margin-top:1rem}.stock-control__header,.stock-control__toolbar,.list-heading,.control-row{display:flex;align-items:center;justify-content:space-between;gap:1rem}.stock-control__toolbar{border-top:1px solid #e8efec;border-bottom:1px solid #e8efec;padding:1rem 0;margin:1rem 0}.stock-control__toolbar label,.control-form label{display:grid;gap:.3rem;color:var(--muted);font-size:.76rem;font-weight:700;flex:1}.stock-control select,.stock-control input{width:100%;border:1px solid #d7e0dd;border-radius:.55rem;padding:.6rem;background:#fff}.stock-control__grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.control-form{display:grid;gap:.65rem;background:#f5f9f7;border-radius:.7rem;padding:1rem}.control-form h3{margin:0}.form-note{font-size:.76rem;color:var(--muted);line-height:1.45}.stock-control__lists{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-top:1.2rem}.stock-control__lists>section{border-top:2px solid #dce9e4;padding-top:.7rem}.list-heading h3{margin:.2rem 0}.list-heading span{color:var(--muted);font-weight:800}.control-row{border-top:1px solid #e8efec;padding:.7rem 0;align-items:flex-start;flex-wrap:wrap}.control-row>div:first-child{min-width:0;flex:1}.control-row small{display:block;color:var(--muted);margin-top:.2rem}.control-actions{display:flex;gap:.3rem;flex-wrap:wrap}.control-actions button,.count-observations button,.count-review button,.reason-row button,.ledger-panel button{border:0;background:transparent;color:#2e7263;font-weight:800;cursor:pointer}.count-observations,.count-review{display:grid;gap:.45rem;width:100%;background:#f5f9f7;padding:.7rem;border-radius:.5rem}.count-line{display:grid;grid-template-columns:1fr minmax(7rem,10rem);align-items:center;gap:.5rem;color:#29433b;font-size:.8rem}.count-line small{grid-column:1 / -1}.count-review select,.reason-row select,.reason-row input,.reason-form input,.reason-form select,.ledger-panel select,.ledger-panel input{padding:.45rem;border:1px solid #d7e0dd;border-radius:.45rem}.stock-control__error{color:#a33b34;background:#fff0ee;padding:.7rem;border-radius:.5rem}.empty-copy{color:var(--muted);font-size:.8rem}.reason-panel,.ledger-panel{margin-top:1.2rem;border-top:2px solid #dce9e4;padding-top:.7rem}.reason-form{display:grid;grid-template-columns:1fr 1.4fr 1.4fr 1fr auto;gap:.5rem;margin:.7rem 0}.reason-list{display:grid;gap:.35rem}.reason-row{display:grid;grid-template-columns:1fr 1fr 1.4fr 1.4fr auto auto auto;align-items:center;gap:.45rem;border-top:1px solid #e8efec;padding:.55rem 0}.history-list{width:100%;margin:.2rem 0 0;padding-left:1.2rem;color:var(--muted);font-size:.75rem}.ledger-panel .control-row{align-items:center}@media(max-width:1050px){.stock-control__grid,.stock-control__lists{grid-template-columns:1fr}.stock-control__toolbar{flex-wrap:wrap}.stock-control__toolbar label{min-width:14rem}.reason-form,.reason-row{grid-template-columns:1fr}.reason-row strong{margin-top:.4rem}}`],
})
export class InventoryStockControlComponent implements OnInit {
  private readonly inventory = inject(InventoryService);
  private readonly masterData = inject(MasterDataService);
  private readonly auth = inject(AuthService);
  private readonly languageService = inject(LanguageService);
  readonly language = {
    language: (): StockControlLanguage => this.languageService.language(),
    text: (key: string): string => key.startsWith('stockControl') ? this.stockText(key) : this.languageService.text(key as TranslationKey),
  };
  readonly warehouses = signal<InventoryWarehouseOption[]>([]);
  readonly products = signal<ProductRecord[]>([]);
  readonly reasonCatalogue = signal<InventoryReasonCode[]>([]);
  readonly adjustmentReasons = signal<InventoryReasonCode[]>([]);
  readonly issueReasons = signal<InventoryReasonCode[]>([]);
  readonly varianceReasons = signal<InventoryReasonCode[]>([]);
  readonly adjustments = signal<InventoryAdjustment[]>([]);
  readonly counts = signal<InventoryCount[]>([]);
  readonly issues = signal<InventoryStockIssue[]>([]);
  readonly ledgerMovements = signal<InventoryMovement[]>([]);
  readonly histories = signal<Record<string, InventoryControlHistory[]>>({});
  readonly error = signal('');
  countedQuantities: Record<string, number | null> = {};
  varianceReasonCodes: Record<string, string> = {};
  correctionReasonCodes: Record<string, string> = {};
  correctionNotes: Record<string, string> = {};
  reasonDrafts: Record<string, { englishName: string; arabicName: string; category: InventoryReasonCategory }> = {};
  warehouseId = '';
  productId = '';
  countType: 'Cycle' | 'Full' = 'Cycle';
  actorId = '';
  reviewerId = '';
  newReason = { code: '', englishName: '', arabicName: '', category: 'Adjustment' as InventoryReasonCategory };
  adjustment = { direction: 'Increase' as 'Increase' | 'Decrease', quantity: 0, reasonCode: '', trackingIdentity: '' };
  issue = { destinationUseDescription: '', quantity: 0, reasonCode: '', trackingIdentity: '' };

  stockText(key: string): string {
    const locale = this.languageService.language();
    return stockControlTranslations[locale][key] ?? stockControlTranslations.en[key] ?? key;
  }

  ngOnInit(): void { this.actorId = this.auth.session()?.actorId ?? ''; void this.load(); }
  private selectedWarehouse(): InventoryWarehouseOption | undefined { return this.warehouses().find(item => item.warehouseId === this.warehouseId); }
  private selectedProduct(): ProductRecord | undefined { return this.products().find(item => item.id === this.productId); }
  canWrite(): boolean { return !!this.selectedWarehouse() && !!this.selectedProduct(); }
  currentLines(record: InventoryCount): InventoryCountLine[] { return record.lines.filter(line => line.isCurrentRound); }
  historyFor(id: string): InventoryControlHistory[] { return this.histories()[id] ?? []; }
  productName(product: ProductRecord): string { return this.language.language() === 'ar' ? product.arabicName || product.englishName || '' : product.englishName || product.arabicName || ''; }
  reasonName(reason: InventoryReasonCode): string { return this.language.language() === 'ar' ? reason.arabicName || reason.englishName : reason.englishName || reason.arabicName; }
  statusLabel(status: string): string { const keys: Record<string, string> = { Draft: 'stockControlStatusDraft', Submitted: 'stockControlStatusSubmitted', PendingApproval: 'stockControlStatusPendingApproval', Approved: 'stockControlStatusApproved', Rejected: 'stockControlStatusRejected', ReturnedForChange: 'stockControlStatusReturnedForChange', Posted: 'stockControlStatusPosted', Corrected: 'stockControlStatusCorrected', RecountRequired: 'stockControlStatusRecountRequired', ResnapshotRequired: 'stockControlStatusResnapshotRequired', Blocked: 'stockControlStatusBlocked' }; return this.language.text(keys[status] ?? 'stockControlStatusBlocked'); }
  historyActionLabel(action: string): string { const keys: Record<string, string> = { Created: 'stockControlHistoryCreated', Submitted: 'stockControlHistorySubmitted', Approved: 'stockControlHistoryApproved', Rejected: 'stockControlHistoryRejected', ReturnedForChange: 'stockControlHistoryReturnedForChange', Posted: 'stockControlHistoryPosted', PostBlocked: 'stockControlHistoryPostBlocked', Corrected: 'stockControlHistoryCorrected', Snapshot: 'stockControlHistorySnapshot', CountSubmitted: 'stockControlHistoryCountSubmitted', RecountRequested: 'stockControlHistoryRecountRequested', Resnapshot: 'stockControlHistoryResnapshot', VarianceReasonRecorded: 'stockControlHistoryVarianceReasonRecorded', AuthorizationDenied: 'stockControlHistoryAuthorizationDenied', TrackingRejected: 'stockControlHistoryTrackingRejected', IdempotencyConflict: 'stockControlHistoryIdempotencyConflict', ConcurrencyConflict: 'stockControlHistoryConcurrencyConflict' }; return this.language.text(keys[action] ?? 'stockControlHistory'); }
  directionLabel(direction: string | undefined): string { return this.language.text(direction === 'Decrease' || direction === 'Outbound' ? 'stockControlDecrease' : 'stockControlIncrease'); }
  countTypeLabel(countType: string): string { return this.language.text(countType === 'Full' ? 'stockControlFullSnapshot' : 'stockControlCycleCount'); }
  sourceTypeLabel(sourceType: string): string { const keys: Record<string, string> = { StockAdjustment: 'stockControlMovementStockAdjustment', InventoryCountVariance: 'stockControlMovementCountVariance', StockIssue: 'stockControlMovementStockIssue' }; return this.language.text(keys[sourceType] ?? 'stockControlMovement'); }
  private setReasonDrafts(reasons: InventoryReasonCode[]): void { for (const reason of reasons) this.reasonDrafts[reason.id] = { englishName: reason.englishName, arabicName: reason.arabicName, category: reason.category }; }
  private async load(): Promise<void> { try { const [warehouses, products] = await Promise.all([firstValueFrom(this.inventory.warehouses()), firstValueFrom(this.masterData.list('products'))]); this.warehouses.set(warehouses); this.products.set(products.filter((item): item is ProductRecord => 'sku' in item && item.isInventoryRelevant)); if (warehouses[0]) { this.warehouseId = warehouses[0].warehouseId; this.productId = this.products()[0]?.id ?? ''; await this.refresh(); } } catch { this.error.set(this.language.text('stockControlLoadFailed')); } }
  async refresh(): Promise<void> { const warehouse = this.selectedWarehouse(); if (!warehouse) return; try { const filters = { warehouseId: warehouse.warehouseId, companyId: warehouse.companyId, branchId: warehouse.branchId || undefined }; const [adjustments, counts, issues, allReasons, ledger] = await Promise.all([firstValueFrom(this.inventory.adjustments(filters)), firstValueFrom(this.inventory.counts(filters)), firstValueFrom(this.inventory.stockIssues(filters)), firstValueFrom(this.inventory.reasonCodes(undefined, true)), firstValueFrom(this.inventory.ledger(filters))]); this.adjustments.set(adjustments); this.counts.set(counts); this.issues.set(issues); this.reasonCatalogue.set(allReasons); this.setReasonDrafts(allReasons); this.adjustmentReasons.set(allReasons.filter(item => item.category === 'Adjustment' && item.isActive)); this.issueReasons.set(allReasons.filter(item => item.category === 'StockIssue' && item.isActive)); this.varianceReasons.set(allReasons.filter(item => item.category === 'CountVariance' && item.isActive)); this.ledgerMovements.set(ledger); } catch { this.error.set(this.language.text('stockControlContextUnavailable')); } }
  async createReasonCode(): Promise<void> { if (!this.canWrite() || !this.newReason.code.trim() || !this.newReason.englishName.trim() || !this.newReason.arabicName.trim()) return; try { await this.inventory.createReasonCode({ code: this.newReason.code.trim(), englishName: this.newReason.englishName.trim(), arabicName: this.newReason.arabicName.trim(), category: this.newReason.category }); this.newReason = { code: '', englishName: '', arabicName: '', category: 'Adjustment' }; await this.refresh(); } catch { this.error.set(this.language.text('stockControlReasonCreateFailed')); } }
  async updateReasonCode(reason: InventoryReasonCode): Promise<void> { const draft = this.reasonDrafts[reason.id]; if (!draft || !draft.englishName.trim() || !draft.arabicName.trim()) return; try { await this.inventory.updateReasonCode(reason.id, reason.version, { englishName: draft.englishName.trim(), arabicName: draft.arabicName.trim(), category: draft.category, isActive: reason.isActive }); await this.refresh(); } catch { this.error.set(this.language.text('stockControlReasonUpdateFailed')); } }
  async toggleReasonCode(reason: InventoryReasonCode): Promise<void> { const draft = this.reasonDrafts[reason.id]; if (!draft) return; try { await this.inventory.updateReasonCode(reason.id, reason.version, { englishName: draft.englishName, arabicName: draft.arabicName, category: draft.category, isActive: !reason.isActive }); await this.refresh(); } catch { this.error.set(this.language.text('stockControlReasonToggleFailed')); } }
  async createAdjustment(): Promise<void> { const warehouse = this.selectedWarehouse(); const product = this.selectedProduct(); if (!warehouse || !product || !this.adjustment.reasonCode || this.adjustment.quantity <= 0) return; try { await this.inventory.createAdjustment({ companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, evidenceReference: null, lines: [{ productId: product.id, unitOfMeasureId: product.baseUnitOfMeasureId, direction: this.adjustment.direction, quantity: this.adjustment.quantity, reasonCode: this.adjustment.reasonCode, trackingIdentity: this.adjustment.trackingIdentity || null, evidenceReference: null }] }); this.adjustment.quantity = 0; await this.refresh(); } catch { this.error.set(this.language.text('stockControlAdjustmentCreateFailed')); } }
  async submitAdjustment(record: InventoryAdjustment): Promise<void> { try { await this.inventory.submitAdjustment(record.id, record.version); await this.refresh(); } catch { this.error.set(this.language.text('stockControlAdjustmentSubmitFailed')); } }
  async approveAdjustment(record: InventoryAdjustment): Promise<void> { try { await this.inventory.approveAdjustment(record.id, record.version); await this.refresh(); } catch { this.error.set(this.language.text('stockControlApprovalFailed')); } }
  async rejectAdjustment(record: InventoryAdjustment): Promise<void> { try { await this.inventory.rejectAdjustment(record.id, record.version, { reason: this.language.text('stockControlReviewerRejectionReason') }); await this.refresh(); } catch { this.error.set(this.language.text('stockControlAdjustmentRejectFailed')); } }
  async postAdjustment(record: InventoryAdjustment): Promise<void> { try { await this.inventory.postAdjustment(record.id, record.version); await this.refresh(); } catch { this.error.set(this.language.text('stockControlAdjustmentPostFailed')); } }
  async createCount(): Promise<void> { const warehouse = this.selectedWarehouse(); const product = this.selectedProduct(); if (!warehouse || !product || !this.actorId) return; try { await this.inventory.createCount({ companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, countType: this.countType, assignedCounterId: this.actorId, reviewerId: this.reviewerId.trim() || null, lines: this.countType === 'Cycle' ? [{ productId: product.id, unitOfMeasureId: product.baseUnitOfMeasureId, trackingIdentity: null }] : [] }); await this.refresh(); } catch { this.error.set(this.language.text('stockControlCountCreateFailed')); } }
  async submitCount(record: InventoryCount): Promise<void> { const current = this.currentLines(record); const observations = current.map(line => ({ countLineId: line.id, countedQuantity: Number(this.countedQuantities[line.id]) })).filter(item => Number.isFinite(item.countedQuantity) && item.countedQuantity >= 0); if (observations.length !== current.length) { this.error.set(this.language.text('stockControlPhysicalQuantityRequired')); return; } try { await this.inventory.submitCount(record.id, record.version, { observations }); await this.refresh(); } catch { this.error.set(this.language.text('stockControlCountObservationFailed')); } }
  async recordVarianceReason(record: InventoryCount, line: InventoryCountLine): Promise<void> { const reasonCode = this.varianceReasonCodes[line.id]; if (!reasonCode) return; try { await this.inventory.recordCountVarianceReason(record.id, record.version, line.id, reasonCode); await this.refresh(); } catch { this.error.set(this.language.text('stockControlVarianceReasonFailed')); } }
  async approveCount(record: InventoryCount): Promise<void> { try { await this.inventory.approveCount(record.id, record.version); await this.refresh(); } catch { this.error.set(this.language.text('stockControlCountApprovalFailed')); } }
  async rejectCount(record: InventoryCount): Promise<void> { try { await this.inventory.rejectCount(record.id, record.version, { reason: this.language.text('stockControlReviewerRejectionReason') }); await this.refresh(); } catch { this.error.set(this.language.text('stockControlCountRejectFailed')); } }
  async postCount(record: InventoryCount): Promise<void> { try { await this.inventory.postCount(record.id, record.version); await this.refresh(); } catch { this.error.set(this.language.text('stockControlCountPostFailed')); } }
  async recount(record: InventoryCount): Promise<void> { try { await this.inventory.recountCount(record.id, record.version, { reason: this.language.text('stockControlReviewerRecountReason') }); await this.refresh(); } catch { this.error.set(this.language.text('stockControlRecountFailed')); } }
  async resnapshot(record: InventoryCount): Promise<void> { try { await this.inventory.resnapshotCount(record.id, record.version); await this.refresh(); } catch { this.error.set(this.language.text('stockControlResnapshotFailed')); } }
  async createIssue(): Promise<void> { const warehouse = this.selectedWarehouse(); const product = this.selectedProduct(); if (!warehouse || !product || !this.issue.reasonCode || this.issue.quantity <= 0 || !this.issue.destinationUseDescription.trim()) return; try { await this.inventory.createStockIssue({ companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, destinationUseDescription: this.issue.destinationUseDescription.trim(), lines: [{ productId: product.id, unitOfMeasureId: product.baseUnitOfMeasureId, quantity: this.issue.quantity, reasonCode: this.issue.reasonCode, trackingIdentity: this.issue.trackingIdentity || null, evidenceReference: null }] }); this.issue.quantity = 0; await this.refresh(); } catch { this.error.set(this.language.text('stockControlIssueCreateFailed')); } }
  async submitIssue(record: InventoryStockIssue): Promise<void> { try { await this.inventory.submitStockIssue(record.id, record.version); await this.refresh(); } catch { this.error.set(this.language.text('stockControlIssueSubmitFailed')); } }
  async approveIssue(record: InventoryStockIssue): Promise<void> { try { await this.inventory.approveStockIssue(record.id, record.version); await this.refresh(); } catch { this.error.set(this.language.text('stockControlIssueApprovalFailed')); } }
  async rejectIssue(record: InventoryStockIssue): Promise<void> { try { await this.inventory.rejectStockIssue(record.id, record.version, { reason: this.language.text('stockControlReviewerRejectionReason') }); await this.refresh(); } catch { this.error.set(this.language.text('stockControlIssueRejectFailed')); } }
  async postIssue(record: InventoryStockIssue): Promise<void> { try { await this.inventory.postStockIssue(record.id, record.version); await this.refresh(); } catch { this.error.set(this.language.text('stockControlIssuePostFailed')); } }
  async loadAdjustmentHistory(id: string): Promise<void> { await this.loadHistory(id, () => this.inventory.adjustmentHistory(id)); }
  async loadCountHistory(id: string): Promise<void> { await this.loadHistory(id, () => this.inventory.countHistory(id)); }
  async loadIssueHistory(id: string): Promise<void> { await this.loadHistory(id, () => this.inventory.stockIssueHistory(id)); }
  private async loadHistory(id: string, loader: () => ReturnType<InventoryService['adjustmentHistory']>): Promise<void> { try { const history = await firstValueFrom(loader()); this.histories.update(current => ({ ...current, [id]: history })); } catch { this.error.set(this.language.text('stockControlHistoryUnavailable')); } }
  isEligibleCorrection(movement: InventoryMovement): boolean { return movement.sourceType === 'StockAdjustment' || movement.sourceType === 'InventoryCountVariance' || movement.sourceType === 'StockIssue'; }
  hasCorrection(movement: InventoryMovement): boolean { return this.ledgerMovements().some(item => item.correctionOfMovementId === movement.id); }
  correctionReasons(movement: InventoryMovement): InventoryReasonCode[] { const category: InventoryReasonCategory = movement.sourceType === 'StockIssue' ? 'StockIssue' : movement.sourceType === 'InventoryCountVariance' ? 'CountVariance' : 'Adjustment'; return this.reasonCatalogue().filter(item => item.category === category && item.isActive); }
  async correctMovement(movement: InventoryMovement): Promise<void> { const reasonCode = this.correctionReasonCodes[movement.id]; if (!reasonCode) { this.error.set(this.language.text('stockControlCorrectionReasonRequired')); return; } try { await this.inventory.correctMovement(movement.id, movement.version, reasonCode, this.correctionNotes[movement.id]?.trim() || undefined); await this.refresh(); } catch { this.error.set(this.language.text('stockControlCorrectionRejected')); } }
}
