import { CommonModule } from '@angular/common';
import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { LanguageService } from '../../core/i18n/language.service';
import { MasterDataService } from '../master-data/master-data.service';
import { ProductRecord, UnitOfMeasureRecord } from '../master-data/master-data.models';
import { InventoryService } from './inventory.service';
import { InventoryAvailability, InventoryMovement, InventoryOpeningBalance, InventoryOpeningCreateRequest, InventoryReservation, InventoryReservationCreateRequest, InventoryWarehouseOption } from './inventory.model';

@Component({
  selector: 'app-inventory-workspace',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <section class="ui-page inventory-page" data-testid="inventory-workspace">
      <header class="ui-page-header ui-page-header--compact page-header">
        <div><p class="eyebrow">{{ text('inventoryNavLabel') }}</p><h1>{{ text('inventoryTitle') }}</h1><p class="lede">{{ text('inventoryLead') }}</p></div>
        <a class="button button--secondary" routerLink="/app">{{ language.text('overview') }}</a>
      </header>
      <div class="boundary-note" role="note">{{ text('inventoryBoundary') }}</div>
      @if (error()) { <section class="ui-surface state-card state-card--error" role="alert"><strong>{{ text('inventoryErrorTitle') }}</strong><p>{{ error() }}</p></section> }
      <section class="ui-surface inventory-controls">
        <div class="section-heading"><div><p class="eyebrow">{{ text('scope') }}</p><h2>{{ text('operationalContext') }}</h2></div><span class="status-badge status-badge--active">{{ text('serverAuthority') }}</span></div>
        <div class="form-grid">
          <label><span>{{ text('selectWarehouse') }}</span><select [(ngModel)]="selectedWarehouseId" (ngModelChange)="onWarehouseChanged()"><option value="">{{ text('selectWarehouse') }}</option>@for (warehouse of warehouses(); track warehouse.warehouseId) {<option [value]="warehouse.warehouseId">{{ warehouse.displayName }}</option>}</select></label>
          <label><span>{{ text('product') }}</span><select [(ngModel)]="selectedProductId" (ngModelChange)="loadAvailability()"><option value="">{{ text('selectProduct') }}</option>@for (product of products(); track product.id) {<option [value]="product.id">{{ product.sku }} — {{ product.englishName || product.arabicName }}</option>}</select></label>
          <label><span>{{ text('unitOfMeasure') }}</span><select [(ngModel)]="selectedUnitId"><option value="">{{ text('selectUnit') }}</option>@for (unit of units(); track unit.id) {<option [value]="unit.id">{{ unit.code }} — {{ unit.englishName || unit.arabicName }}</option>}</select></label>
        </div>
      </section>

      <div class="inventory-grid">
        <section class="ui-surface availability-card">
          <div class="section-heading"><div><p class="eyebrow">{{ text('inventoryNavLabel') }}</p><h2>{{ text('onHand') }}</h2></div><span class="metric-icon">◈</span></div>
          @if (availability(); as stock) {<div class="metric-grid"><div><small>{{ text('onHand') }}</small><strong>{{ stock.onHandQuantity | number:'1.0-4' }}</strong><span>{{ stock.unitOfMeasureCode || text('baseUnit') }}</span></div><div><small>{{ text('reserved') }}</small><strong>{{ stock.reservedQuantity | number:'1.0-4' }}</strong><span>{{ text('reserved') }}</span></div><div class="metric-grid__accent"><small>{{ text('available') }}</small><strong>{{ stock.availableQuantity | number:'1.0-4' }}</strong><span>{{ text('available') }}</span></div><div><small>{{ text('expected') }}</small><strong>{{ stock.expectedQuantity | number:'1.0-4' }}</strong></div><div><small>{{ text('damaged') }}</small><strong>{{ stock.damagedQuantity | number:'1.0-4' }}</strong></div><div><small>{{ text('inTransit') }}</small><strong>{{ stock.inTransitQuantity | number:'1.0-4' }}</strong></div></div>} @else {<p class="empty-copy">{{ text('noRecordsLead') }}</p>}
        </section>
        <section class="ui-surface ledger-card"><div class="section-heading"><div><p class="eyebrow">{{ text('inventoryNavLabel') }}</p><h2>{{ text('inventoryTitle') }}</h2></div><span class="status-badge status-badge--active">{{ text('serverAuthority') }}</span></div><div class="table-wrap"><table class="ui-grid"><thead><tr><th>{{ text('dateColumn') }}</th><th>{{ text('product') }}</th><th>{{ text('sourceType') }}</th><th class="numeric">{{ text('quantity') }}</th><th>{{ text('sourceReference') }}</th></tr></thead><tbody>@for (movement of movements(); track movement.id) {<tr><td>{{ movement.effectiveDate }}</td><td><strong>{{ movement.productSku }}</strong><small>{{ movement.productName }}</small></td><td><span class="status-badge" [class.status-badge--active]="movement.direction === 'Inbound'">{{ movement.direction }}</span></td><td class="numeric">{{ movement.quantity | number:'1.0-4' }}</td><td>{{ movement.sourceType }}</td></tr>} @empty {<tr><td colspan="5" class="empty-copy">{{ text('noRecordsLead') }}</td></tr>}</tbody></table></div></section>
      </div>

      <div class="inventory-grid inventory-grid--lower">
        <section class="ui-surface workflow-card"><div class="section-heading"><div><p class="eyebrow">{{ text('inventoryNavLabel') }}</p><h2>{{ text('inventoryTitle') }}</h2></div></div><form (ngSubmit)="createOpening()" class="form-grid"><label><span>{{ text('sourceLineage') }}</span><input name="sourceOwner" [(ngModel)]="opening.sourceOwner" required /></label><label><span>{{ text('sourceSystem') }}</span><input name="sourceSystem" [(ngModel)]="opening.sourceSystem" required /></label><label><span>{{ text('dateColumn') }}</span><input name="asOfDate" type="date" [(ngModel)]="opening.asOfDate" required /></label><label><span>{{ text('quantity') }}</span><input name="quantity" type="number" min="0.00000001" step="any" [(ngModel)]="opening.quantity" required /></label><label><span>{{ text('unitCost') }}</span><input name="unitCost" type="number" min="0" step="any" [(ngModel)]="opening.unitCost" required /></label><label><span>{{ text('currency') }}</span><input name="currency" maxlength="16" [(ngModel)]="opening.currencyCode" required /></label><label class="form-grid__wide"><span>{{ text('sourceReference') }}</span><input name="sourceReference" [(ngModel)]="opening.sourceReference" /></label><button class="button button--primary" type="submit" [disabled]="!canCreate()">{{ text('createRecord') }}</button></form><div class="record-list">@for (record of openings(); track record.id) {<article class="record-row"><div><strong>{{ record.sourceSystem }}</strong><small>{{ record.warehouseCode }} · {{ record.asOfDate }} · {{ record.validQuantityTotal | number:'1.0-4' }}</small></div><span class="status-badge">{{ record.status }}</span><div class="record-actions">@if (record.status === 'Draft') {<button class="button button--quiet" (click)="validateOpening(record)">{{ text('validate') }}</button>} @if (record.status === 'Validated') {<button class="button button--quiet" (click)="postOpening(record)">{{ text('post') }}</button>} @if (record.status === 'Posted') {<button class="button button--quiet" (click)="correctOpening(record)">{{ text('correct') }}</button>}</div></article>} @empty {<p class="empty-copy">{{ text('noRecords') }}</p>}</div></section>
        <section class="ui-surface workflow-card"><div class="section-heading"><div><p class="eyebrow">{{ text('inventoryNavLabel') }}</p><h2>{{ text('inventoryTitle') }}</h2></div><span class="status-badge status-badge--active">{{ text('doesNotReduceStock') }}</span></div><form (ngSubmit)="createReservation()" class="form-grid"><label><span>{{ text('quantity') }}</span><input name="requestedQuantity" type="number" min="0.00000001" step="any" [(ngModel)]="reservation.requestedQuantity" required /></label><label><span>{{ text('sourceType') }}</span><input name="sourceType" [(ngModel)]="reservation.sourceType" required /></label><label><span>{{ text('sourceReference') }}</span><input name="sourceReference" [(ngModel)]="reservation.sourceReference" required /></label><label class="checkbox-label"><input name="partial" type="checkbox" [(ngModel)]="reservation.allowPartialAllocation" /><span>{{ text('allowPartial') }}</span></label>@if (trackingEnabled()) {<label class="form-grid__wide"><span>{{ text('trackingIdentity') }}</span><input name="trackingIdentity" [(ngModel)]="reservation.trackingIdentity" required /></label>}<button class="button button--primary" type="submit" [disabled]="!canReserve()">{{ text('createRecord') }}</button></form><div class="record-list">@for (record of reservations(); track record.id) {<article class="record-row"><div><strong>{{ record.sourceReference }}</strong><small>{{ record.productSku }} · {{ text('reserved') }} {{ record.reservedQuantity | number:'1.0-4' }} · {{ text('unallocated') }} {{ record.unallocatedQuantity | number:'1.0-4' }}</small></div><span class="status-badge">{{ record.status }}</span><div class="record-actions">@if (record.status === 'Active') {<label class="inline-action"><span class="sr-only">{{ text('quantity') }}</span><input [name]="'reduce-' + record.id" type="number" min="0.00000001" step="any" [max]="record.reservedQuantity" [(ngModel)]="reductionQuantities[record.id]" [ngModelOptions]="{standalone: true}" [attr.aria-label]="text('quantity')" /><button class="button button--quiet" type="button" (click)="reduceReservation(record)">{{ text('reduce') }}</button><button class="button button--quiet" type="button" (click)="releaseReservation(record)">{{ text('release') }}</button></label>}</div></article>} @empty {<p class="empty-copy">{{ text('noRecords') }}</p>}</div></section>
      </div>
    </section>
  `,
  styles: [`.inventory-page{--inventory-ink:#18312d}.inventory-controls,.availability-card,.ledger-card,.workflow-card{padding:1.35rem}.inventory-grid{display:grid;grid-template-columns:minmax(0,.85fr) minmax(0,1.4fr);gap:1rem;margin-top:1rem}.inventory-grid--lower{grid-template-columns:repeat(2,minmax(0,1fr))}.section-heading{display:flex;justify-content:space-between;align-items:start;gap:1rem;margin-bottom:1rem}.section-heading h2{margin:.2rem 0}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem}.form-grid label{display:grid;gap:.3rem;color:var(--muted);font-size:.78rem;font-weight:700}.form-grid input,.form-grid select{width:100%;border:1px solid #d7e0dd;border-radius:.55rem;padding:.65rem;background:#fff;color:var(--inventory-ink)}.form-grid__wide{grid-column:1/-1}.checkbox-label{display:flex!important;align-items:center;grid-template-columns:auto 1fr;gap:.5rem}.checkbox-label input{width:auto}.metric-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.6rem}.metric-grid>div{padding:1rem;background:#f4f8f6;border-radius:.7rem}.metric-grid small,.metric-grid span{display:block;color:var(--muted);font-size:.72rem}.metric-grid strong{display:block;font-size:1.65rem;color:var(--inventory-ink);margin:.25rem 0}.metric-grid__accent{background:#e4f2ed!important}.table-wrap{overflow:auto}.ui-grid{width:100%;border-collapse:collapse}.ui-grid th,.ui-grid td{padding:.7rem;border-bottom:1px solid #e8efec;text-align:start;font-size:.78rem;white-space:nowrap}.ui-grid th{color:var(--muted);font-size:.7rem;text-transform:uppercase;letter-spacing:.04em}.ui-grid small,.record-row small{display:block;color:var(--muted);margin-top:.2rem}.numeric{text-align:end!important}.record-list{display:grid;gap:.55rem;margin-top:1rem}.record-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:.7rem;align-items:center;border-top:1px solid #e8efec;padding-top:.7rem}.record-actions{display:flex;gap:.4rem}.inline-action{display:flex!important;align-items:center;gap:.35rem}.inline-action input{width:5.5rem!important;padding:.45rem!important}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.button--quiet{border:0;background:transparent;color:#2e7263;font-weight:800;cursor:pointer}.empty-copy{color:var(--muted);font-size:.85rem}@media(max-width:1050px){.inventory-grid,.inventory-grid--lower{grid-template-columns:1fr}}@media(max-width:640px){.form-grid,.metric-grid{grid-template-columns:1fr}.record-row{grid-template-columns:1fr}.form-grid__wide{grid-column:auto}}`],
})
export class InventoryWorkspaceComponent implements OnInit {
  readonly language = inject(LanguageService); private readonly inventory = inject(InventoryService); private readonly masterData = inject(MasterDataService);
  readonly warehouses = signal<InventoryWarehouseOption[]>([]); readonly products = signal<ProductRecord[]>([]); readonly units = signal<UnitOfMeasureRecord[]>([]); readonly movements = signal<InventoryMovement[]>([]); readonly openings = signal<InventoryOpeningBalance[]>([]); readonly reservations = signal<InventoryReservation[]>([]); readonly availability = signal<InventoryAvailability | null>(null); readonly error = signal('');
  selectedWarehouseId = ''; selectedProductId = ''; selectedUnitId = ''; opening = { sourceOwner: 'Inventory Operations', sourceSystem: 'Opening Balance Import', asOfDate: new Date().toISOString().slice(0, 10), quantity: 0, unitCost: 0, currencyCode: 'SAR', sourceReference: '' }; reservation = { requestedQuantity: 0, sourceType: 'Demand', sourceReference: '', allowPartialAllocation: true, trackingIdentity: '' }; reductionQuantities: Record<string, number | null> = {};
  private selectedWarehouse = computed(() => this.warehouses().find(item => item.warehouseId === this.selectedWarehouseId));
  ngOnInit(): void { void this.load(); }
  text(key: Parameters<LanguageService['text']>[0]): string { return this.language.text(key); }
  trackingEnabled(): boolean { return this.products().find(item => item.id === this.selectedProductId)?.trackingEnabled ?? false; }
  canCreate(): boolean { return !!this.selectedWarehouse() && !!this.selectedProductId && !!this.selectedUnitId && this.opening.quantity > 0 && this.opening.unitCost >= 0; }
  canReserve(): boolean { return !!this.selectedWarehouse() && !!this.selectedProductId && !!this.selectedUnitId && this.reservation.requestedQuantity > 0 && !!this.reservation.sourceReference; }
  async load(): Promise<void> { try { const [warehouses, products, units] = await Promise.all([firstValueFrom(this.inventory.warehouses()), firstValueFrom(this.masterData.list('products')), firstValueFrom(this.masterData.list('units'))]); this.warehouses.set(warehouses); this.products.set(products.filter((item): item is ProductRecord => 'sku' in item && item.isInventoryRelevant)); this.units.set(units.filter((item): item is UnitOfMeasureRecord => 'code' in item)); if (warehouses[0]) { this.selectedWarehouseId = warehouses[0].warehouseId; const product = this.products()[0]; if (product) { this.selectedProductId = product.id; this.selectedUnitId = product.baseUnitOfMeasureId; } await this.onWarehouseChanged(); } } catch { this.error.set(this.text('networkError')); } }
  async onWarehouseChanged(): Promise<void> { const warehouse = this.selectedWarehouse(); if (!warehouse) return; try { const filters = { warehouseId: warehouse.warehouseId, companyId: warehouse.companyId, branchId: warehouse.branchId || undefined }; const [movements, openings, reservations] = await Promise.all([firstValueFrom(this.inventory.ledger(filters)), firstValueFrom(this.inventory.openings(filters)), firstValueFrom(this.inventory.reservations(filters))]); this.movements.set(movements); this.openings.set(openings); this.reservations.set(reservations); await this.loadAvailability(); } catch { this.error.set(this.text('networkError')); } }
  async loadAvailability(): Promise<void> { const warehouse = this.selectedWarehouse(); const product = this.products().find(item => item.id === this.selectedProductId); if (!warehouse || !product || !this.selectedUnitId) { this.availability.set(null); return; } try { this.availability.set(await firstValueFrom(this.inventory.availability({ warehouseId: warehouse.warehouseId, companyId: warehouse.companyId, branchId: warehouse.branchId, productId: product.id, unitOfMeasureId: this.selectedUnitId, trackingIdentity: this.trackingEnabled() ? this.reservation.trackingIdentity || undefined : undefined }))); } catch { this.availability.set(null); } }
  async createOpening(): Promise<void> { const warehouse = this.selectedWarehouse(); if (!warehouse || !this.canCreate()) return; const payload: InventoryOpeningCreateRequest = { companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, asOfDate: this.opening.asOfDate, sourceOwner: this.opening.sourceOwner, sourceSystem: this.opening.sourceSystem, extractedAt: new Date().toISOString(), sourceReference: this.opening.sourceReference || null, rows: [{ productId: this.selectedProductId, unitOfMeasureId: this.selectedUnitId, quantity: this.opening.quantity, unitCost: this.opening.unitCost, currencyCode: this.opening.currencyCode, trackingIdentity: this.trackingEnabled() ? this.reservation.trackingIdentity || null : null, sourceLineReference: null }] }; try { await this.inventory.createOpening(payload); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async validateOpening(record: InventoryOpeningBalance): Promise<void> { try { await this.inventory.validateOpening(record.id, record.version); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async postOpening(record: InventoryOpeningBalance): Promise<void> { try { await this.inventory.postOpening(record.id, record.version); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async correctOpening(record: InventoryOpeningBalance): Promise<void> { try { await this.inventory.correctOpening(record.id, record.version, 'Controlled opening-balance correction'); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async createReservation(): Promise<void> { const warehouse = this.selectedWarehouse(); if (!warehouse || !this.canReserve()) return; const payload: InventoryReservationCreateRequest = { companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, productId: this.selectedProductId, unitOfMeasureId: this.selectedUnitId, requestedQuantity: this.reservation.requestedQuantity, sourceType: this.reservation.sourceType, sourceReference: this.reservation.sourceReference, allowPartialAllocation: this.reservation.allowPartialAllocation, trackingIdentity: this.trackingEnabled() ? this.reservation.trackingIdentity || null : null }; try { await this.inventory.createReservation(payload); await this.onWarehouseChanged(); await this.loadAvailability(); } catch { this.error.set(this.text('requestError')); } }
  async reduceReservation(record: InventoryReservation): Promise<void> { const quantity = this.reductionQuantities[record.id] ?? 0; if (quantity <= 0 || quantity > record.reservedQuantity) return; try { await this.inventory.reduceReservation(record.id, record.version, quantity); delete this.reductionQuantities[record.id]; await this.onWarehouseChanged(); await this.loadAvailability(); } catch { this.error.set(this.text('requestError')); } }
  async releaseReservation(record: InventoryReservation): Promise<void> { try { await this.inventory.releaseReservation(record.id, record.version); await this.onWarehouseChanged(); await this.loadAvailability(); } catch { this.error.set(this.text('requestError')); } }
}
