// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniErp.Infrastructure.Persistence.Modules.MasterData;

#nullable disable

namespace MiniErp.Infrastructure.Persistence.Migrations.MasterData
{
    [DbContext(typeof(MasterDataDbContext))]
    [Migration("20260815225908_InitialMasterData")]
    partial class InitialMasterData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataAuditEventEntity", b =>
                {
                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthorizationPath")
                        .HasColumnType("int");

                    b.Property<string>("BeforeSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("BusinessCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("PolicyOutcome")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ResourceKind")
                        .HasColumnType("int");

                    b.Property<Guid?>("ScopeAnchorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ScopeAnchorKind")
                        .HasColumnType("int");

                    b.Property<string>("ScopePolicyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ScopePolicyVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("EvidenceId");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.HasIndex("TenantId", "ResourceKind", "ResourceId");

                    b.ToTable("AuditEvents", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("int");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrackingDefaultEnabled")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "NameKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "ParentCategoryId");

                    b.ToTable("Categories", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataConversionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Factor")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid>("FromUnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToUnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ToUnitOfMeasureId");

                    b.HasIndex("TenantId", "FromUnitOfMeasureId", "ToUnitOfMeasureId")
                        .IsUnique();

                    b.ToTable("UnitConversions", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataCurrencyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("int");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CodeKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "NameKey")
                        .IsUnique();

                    b.ToTable("Currencies", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataExchangeRateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("int");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "TargetCurrencyId");

                    b.HasIndex("TenantId", "SourceCurrencyId", "TargetCurrencyId")
                        .IsUnique();

                    b.ToTable("ExchangeRates", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataExchangeRateVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("ExchangeRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Provenance")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<int>("RateScale")
                        .HasColumnType("int");

                    b.Property<string>("SourceCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SourceNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("TargetCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "ExchangeRateId", "EffectiveFrom")
                        .IsUnique();

                    b.HasIndex("TenantId", "ExchangeRateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ExchangeRateVersions", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataImportAuditEntity", b =>
                {
                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Detail")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("OriginalRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ResourceKind")
                        .HasColumnType("int");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("EvidenceId");

                    b.HasIndex("TenantId", "BatchId", "OccurredAt");

                    b.HasIndex("TenantId", "BatchId", "RowId");

                    b.ToTable("ImportAuditEvents", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataImportBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("int");

                    b.Property<string>("BatchReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("CommittedCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DuplicatePolicy")
                        .HasColumnType("int");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("QuarantinedCount")
                        .HasColumnType("int");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("int");

                    b.Property<int>("ResourceKind")
                        .HasColumnType("int");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceFileReference")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("SourceSystemCategory")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubmittedActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "SubmittedActorId", "ResourceKind", "IdempotencyKey");

                    b.ToTable("ImportBatches", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataImportRowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiagnosticsJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ExpectedResourceVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("HighestSeverity")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<int>("MutationDisposition")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedFieldsJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OriginalRowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OriginalRowNumber")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReplayIdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ReplayOfRowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReplaySequence")
                        .HasColumnType("int");

                    b.Property<int>("ResourceKind")
                        .HasColumnType("int");

                    b.Property<string>("ResultingResourceCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ResultingResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceFieldsJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "BatchId", "ReplayIdempotencyKey");

                    b.HasIndex("TenantId", "BatchId", "OriginalRowNumber", "ReplaySequence")
                        .IsUnique();

                    b.ToTable("ImportRows", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPaymentTermEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("int");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CodeKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "NameKey")
                        .IsUnique();

                    b.ToTable("PaymentTerms", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPaymentTermInstallmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OffsetDays")
                        .HasColumnType("int");

                    b.Property<int>("OffsetMonths")
                        .HasColumnType("int");

                    b.Property<Guid>("PaymentTermVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "PaymentTermVersionId", "Sequence")
                        .IsUnique();

                    b.ToTable("PaymentTermInstallments", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPaymentTermVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("BaseDateRule")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("DueOffsetDays")
                        .HasColumnType("int");

                    b.Property<int>("DueOffsetMonths")
                        .HasColumnType("int");

                    b.Property<int>("EarlySettlementDiscountDays")
                        .HasColumnType("int");

                    b.Property<bool>("EarlySettlementDiscountEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("EarlySettlementDiscountMonths")
                        .HasColumnType("int");

                    b.Property<decimal?>("EarlySettlementDiscountPercentage")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("PaymentTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScheduleMode")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "PaymentTermId", "EffectiveFrom")
                        .IsUnique();

                    b.HasIndex("TenantId", "PaymentTermId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("PaymentTermVersions", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPriceListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrganizationScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("OrganizationScopeKind")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CodeKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "CurrencyId");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.ToTable("PriceLists", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPriceListPriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("OrganizationScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("OrganizationScopeKind")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PriceScale")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Provenance")
                        .HasColumnType("int");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitOfMeasureCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "ProductId");

                    b.HasIndex("TenantId", "UnitOfMeasureId");

                    b.HasIndex("TenantId", "PriceListId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "PriceListId", "ProductId", "UnitOfMeasureId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("PriceListPrices", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataProductBarcodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComparisonKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ComparisonKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "ProductId");

                    b.ToTable("ProductBarcodes", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("BaseUnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsInventoryRelevant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPurchasable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSellable")
                        .HasColumnType("bit");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SkuKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("TrackingEnabledOverride")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BaseUnitOfMeasureId");

                    b.HasIndex("TenantId", "CategoryId");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "SkuKey")
                        .IsUnique();

                    b.ToTable("Products", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataTaxEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Applicability")
                        .HasColumnType("int");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CategoryArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CategoryCodeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CategoryEnglishName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("int");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CodeKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "NameKey")
                        .IsUnique();

                    b.ToTable("Taxes", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataTaxRateVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<decimal>("RatePercentage")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("TaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "TaxId", "EffectiveFrom")
                        .IsUnique();

                    b.HasIndex("TenantId", "TaxId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("TaxRateVersions", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataUnitOfMeasureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("int");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "NameKey")
                        .IsUnique();

                    b.ToTable("UnitsOfMeasure", "masterdata");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataCategoryEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataCategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ParentCategoryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataConversionEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataUnitOfMeasureEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "FromUnitOfMeasureId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataUnitOfMeasureEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ToUnitOfMeasureId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataExchangeRateEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataCurrencyEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SourceCurrencyId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataCurrencyEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TargetCurrencyId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataExchangeRateVersionEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataExchangeRateEntity", null)
                        .WithMany("Versions")
                        .HasForeignKey("TenantId", "ExchangeRateId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataImportRowEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataImportBatchEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BatchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPaymentTermInstallmentEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPaymentTermVersionEntity", null)
                        .WithMany("Installments")
                        .HasForeignKey("TenantId", "PaymentTermVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPaymentTermVersionEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPaymentTermEntity", null)
                        .WithMany("Versions")
                        .HasForeignKey("TenantId", "PaymentTermId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPriceListEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataCurrencyEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CurrencyId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPriceListPriceEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPriceListEntity", null)
                        .WithMany("Prices")
                        .HasForeignKey("TenantId", "PriceListId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataProductEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataUnitOfMeasureEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UnitOfMeasureId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataProductBarcodeEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataProductEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataProductEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataUnitOfMeasureEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BaseUnitOfMeasureId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataCategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CategoryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataTaxRateVersionEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataTaxEntity", null)
                        .WithMany("RateVersions")
                        .HasForeignKey("TenantId", "TaxId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataExchangeRateEntity", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPaymentTermEntity", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPaymentTermVersionEntity", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataPriceListEntity", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.MasterData.MasterDataTaxEntity", b =>
                {
                    b.Navigation("RateVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
