// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniErp.Infrastructure.Persistence.Modules.BusinessParties;

#nullable disable

namespace MiniErp.Infrastructure.Persistence.Migrations.BusinessParties
{
    [DbContext(typeof(BusinessPartiesDbContext))]
    [Migration("20260816073853_SharedTenantRuntimeModel")]
    partial class SharedTenantRuntimeModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniErp.App.BuildingBlocks.Tenancy.TenantOwnedRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RelatedTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RelationshipKind")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BusinessKey")
                        .IsUnique();

                    b.ToTable("TenantOwnedRecords", "tenancy");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.BusinessParties.BusinessPartiesAuditEventEntity", b =>
                {
                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthorizationPath")
                        .HasColumnType("int");

                    b.Property<string>("BeforeSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("BusinessCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("PolicyOutcome")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ResourceKind")
                        .HasColumnType("int");

                    b.Property<Guid?>("ScopeAnchorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ScopeAnchorKind")
                        .HasColumnType("int");

                    b.Property<string>("ScopePolicyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ScopePolicyVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("EvidenceId");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.HasIndex("TenantId", "ResourceKind", "ResourceId");

                    b.ToTable("AuditEvents", "businessparties");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.BusinessParties.BusinessPartiesCustomerContactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CustomerId");

                    b.ToTable("CustomerContacts", "businessparties");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.BusinessParties.BusinessPartiesCustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicLegalName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ArabicLegalNameKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ArabicTradingName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ArabicTradingNameKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EnglishLegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EnglishLegalNameKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EnglishTradingName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EnglishTradingNameKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ArabicLegalNameKey")
                        .IsUnique()
                        .HasFilter("[ArabicLegalNameKey] IS NOT NULL");

                    b.HasIndex("TenantId", "ArabicTradingNameKey")
                        .IsUnique()
                        .HasFilter("[ArabicTradingNameKey] IS NOT NULL");

                    b.HasIndex("TenantId", "CodeKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "EnglishLegalNameKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "EnglishTradingNameKey")
                        .IsUnique()
                        .HasFilter("[EnglishTradingNameKey] IS NOT NULL");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.ToTable("Customers", "businessparties");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.BusinessParties.BusinessPartiesSupplierContactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SupplierId");

                    b.ToTable("SupplierContacts", "businessparties");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.BusinessParties.BusinessPartiesSupplierEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicLegalName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ArabicLegalNameKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ArabicTradingName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ArabicTradingNameKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EnglishLegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EnglishLegalNameKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EnglishTradingName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EnglishTradingNameKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LifecycleState")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RegistrationReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ArabicLegalNameKey")
                        .IsUnique()
                        .HasFilter("[ArabicLegalNameKey] IS NOT NULL");

                    b.HasIndex("TenantId", "ArabicTradingNameKey")
                        .IsUnique()
                        .HasFilter("[ArabicTradingNameKey] IS NOT NULL");

                    b.HasIndex("TenantId", "CodeKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "EnglishLegalNameKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "EnglishTradingNameKey")
                        .IsUnique()
                        .HasFilter("[EnglishTradingNameKey] IS NOT NULL");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "RegistrationKey")
                        .IsUnique()
                        .HasFilter("[RegistrationKey] IS NOT NULL");

                    b.ToTable("Suppliers", "businessparties");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.BusinessParties.BusinessPartiesCustomerContactEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.BusinessParties.BusinessPartiesCustomerEntity", null)
                        .WithMany("Contacts")
                        .HasForeignKey("TenantId", "CustomerId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.BusinessParties.BusinessPartiesSupplierContactEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.BusinessParties.BusinessPartiesSupplierEntity", null)
                        .WithMany("Contacts")
                        .HasForeignKey("TenantId", "SupplierId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.BusinessParties.BusinessPartiesCustomerEntity", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.BusinessParties.BusinessPartiesSupplierEntity", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
