#pragma warning disable CS1591

using Microsoft.EntityFrameworkCore;
using MiniErp.App.BuildingBlocks.Tenancy;

namespace MiniErp.Infrastructure.Persistence.Modules.Finance;

internal sealed class FinanceDbContext : TenantPersistenceDbContext
{
    internal FinanceDbContext(DbContextOptions options, TenantContext tenantContext)
        : base(options, tenantContext, TenantOwnershipVerifierRegistry.CreateFinance()) { }

    internal DbSet<FinanceAccountEntity> Accounts => Set<FinanceAccountEntity>();
    internal DbSet<FinanceFiscalCalendarEntity> Calendars => Set<FinanceFiscalCalendarEntity>();
    internal DbSet<FinanceFiscalYearEntity> FiscalYears => Set<FinanceFiscalYearEntity>();
    internal DbSet<FinanceFiscalPeriodEntity> FiscalPeriods => Set<FinanceFiscalPeriodEntity>();
    internal DbSet<FinanceCostCenterEntity> CostCenters => Set<FinanceCostCenterEntity>();
    internal DbSet<FinancePostingRuleEntity> PostingRules => Set<FinancePostingRuleEntity>();
    internal DbSet<FinanceJournalEntity> Journals => Set<FinanceJournalEntity>();
    internal DbSet<FinanceJournalLineEntity> JournalLines => Set<FinanceJournalLineEntity>();
    internal DbSet<FinanceAuditEntity> AuditEvents => Set<FinanceAuditEntity>();
    internal DbSet<FinanceIdempotencyEntity> Idempotency => Set<FinanceIdempotencyEntity>();
    internal DbSet<FinanceSourceEffectEntity> SourceEffects => Set<FinanceSourceEffectEntity>();
    internal DbSet<FinancePaymentMethodEntity> PaymentMethods => Set<FinancePaymentMethodEntity>();
    internal DbSet<FinanceCashAccountEntity> CashAccounts => Set<FinanceCashAccountEntity>();
    internal DbSet<FinanceOpenItemEntity> OpenItems => Set<FinanceOpenItemEntity>();
    internal DbSet<FinanceSettlementDocumentEntity> SettlementDocuments => Set<FinanceSettlementDocumentEntity>();
    internal DbSet<FinanceAllocationEntity> Allocations => Set<FinanceAllocationEntity>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        ConfigureBase(modelBuilder.Entity<FinanceAccountEntity>(), "Accounts");
        var account = modelBuilder.Entity<FinanceAccountEntity>();
        account.Property(item => item.CompanyId).IsRequired(); account.Property(item => item.Code).HasMaxLength(64).IsRequired(); account.Property(item => item.EnglishName).HasMaxLength(256).IsRequired(); account.Property(item => item.ArabicName).HasMaxLength(256).IsRequired(false); account.Property(item => item.ParentAccountId).IsRequired(false); account.Property(item => item.AccountType).IsRequired(); account.Property(item => item.IsPostingAccount).IsRequired(); account.Property(item => item.Lifecycle).IsRequired(); account.Property(item => item.CurrencyBehavior).IsRequired(); account.Property(item => item.EffectiveFrom).IsRequired(); account.Property(item => item.EffectiveTo).IsRequired(false); account.HasIndex(item => new { item.TenantId, item.CompanyId, item.Code }).IsUnique(); account.HasIndex(item => new { item.TenantId, item.CompanyId, item.Id }).IsUnique();
        account.HasOne<FinanceAccountEntity>().WithMany().HasForeignKey(item => new { item.TenantId, item.CompanyId, item.ParentAccountId }).HasPrincipalKey(item => new { item.TenantId, item.CompanyId, item.Id }).OnDelete(DeleteBehavior.Restrict).IsRequired(false);

        ConfigureBase(modelBuilder.Entity<FinanceFiscalCalendarEntity>(), "FiscalCalendars");
        var calendar = modelBuilder.Entity<FinanceFiscalCalendarEntity>(); calendar.Property(item => item.CompanyId).IsRequired(); calendar.Property(item => item.Name).HasMaxLength(256).IsRequired(); calendar.Property(item => item.FunctionalCurrencyCode).HasMaxLength(16).IsRequired(); calendar.Property(item => item.Lifecycle).IsRequired(); calendar.HasIndex(item => new { item.TenantId, item.CompanyId, item.Lifecycle }).IsUnique().HasFilter("Lifecycle = 1");

        ConfigureBase(modelBuilder.Entity<FinanceFiscalYearEntity>(), "FiscalYears");
        var year = modelBuilder.Entity<FinanceFiscalYearEntity>(); year.Property(item => item.CalendarId).IsRequired(); year.Property(item => item.CompanyId).IsRequired(); year.Property(item => item.YearNumber).IsRequired(); year.Property(item => item.StartDate).IsRequired(); year.Property(item => item.EndDate).IsRequired(); year.Property(item => item.State).IsRequired(); year.HasIndex(item => new { item.TenantId, item.CalendarId, item.YearNumber }).IsUnique(); year.HasOne<FinanceFiscalCalendarEntity>().WithMany().HasForeignKey(item => new { item.TenantId, item.CalendarId }).HasPrincipalKey(item => new { item.TenantId, item.Id }).OnDelete(DeleteBehavior.Restrict);

        ConfigureBase(modelBuilder.Entity<FinanceFiscalPeriodEntity>(), "FiscalPeriods");
        var period = modelBuilder.Entity<FinanceFiscalPeriodEntity>(); period.Property(item => item.FiscalYearId).IsRequired(); period.Property(item => item.CompanyId).IsRequired(); period.Property(item => item.Sequence).IsRequired(); period.Property(item => item.Code).HasMaxLength(64).IsRequired(); period.Property(item => item.EnglishName).HasMaxLength(256).IsRequired(false); period.Property(item => item.ArabicName).HasMaxLength(256).IsRequired(false); period.Property(item => item.StartDate).IsRequired(); period.Property(item => item.EndDate).IsRequired(); period.Property(item => item.State).IsRequired(); period.HasIndex(item => new { item.TenantId, item.FiscalYearId, item.Sequence }).IsUnique(); period.HasIndex(item => new { item.TenantId, item.FiscalYearId, item.Code }).IsUnique(); period.HasOne<FinanceFiscalYearEntity>().WithMany().HasForeignKey(item => new { item.TenantId, item.FiscalYearId }).HasPrincipalKey(item => new { item.TenantId, item.Id }).OnDelete(DeleteBehavior.Restrict);

        ConfigureBase(modelBuilder.Entity<FinanceCostCenterEntity>(), "CostCenters");
        var cost = modelBuilder.Entity<FinanceCostCenterEntity>(); cost.Property(item => item.CompanyId).IsRequired(); cost.Property(item => item.Code).HasMaxLength(64).IsRequired(); cost.Property(item => item.EnglishName).HasMaxLength(256).IsRequired(); cost.Property(item => item.ArabicName).HasMaxLength(256).IsRequired(false); cost.Property(item => item.Lifecycle).IsRequired(); cost.Property(item => item.EffectiveFrom).IsRequired(); cost.Property(item => item.EffectiveTo).IsRequired(false); cost.HasIndex(item => new { item.TenantId, item.CompanyId, item.Code }).IsUnique();

        ConfigureBase(modelBuilder.Entity<FinancePostingRuleEntity>(), "PostingRules");
        var rule = modelBuilder.Entity<FinancePostingRuleEntity>(); rule.Property(item => item.CompanyId).IsRequired(); rule.Property(item => item.SourceContract).HasMaxLength(128).IsRequired(); rule.Property(item => item.SourceEvent).HasMaxLength(128).IsRequired(); rule.Property(item => item.VersionNumber).IsRequired(); rule.Property(item => item.DebitAccountId).IsRequired(); rule.Property(item => item.DebitAccountCode).HasMaxLength(64).IsRequired(); rule.Property(item => item.CreditAccountId).IsRequired(); rule.Property(item => item.CreditAccountCode).HasMaxLength(64).IsRequired(); rule.Property(item => item.CostCenterRequired).IsRequired(); rule.Property(item => item.EffectiveFrom).IsRequired(); rule.Property(item => item.EffectiveTo).IsRequired(false); rule.Property(item => item.Lifecycle).IsRequired(); rule.HasIndex(item => new { item.TenantId, item.CompanyId, item.SourceContract, item.SourceEvent, item.VersionNumber }).IsUnique();

        ConfigureBase(modelBuilder.Entity<FinanceJournalEntity>(), "Journals");
        var journal = modelBuilder.Entity<FinanceJournalEntity>(); journal.Property(item => item.CompanyId).IsRequired(); journal.Property(item => item.JournalSequence).IsRequired(); journal.Property(item => item.JournalNumber).HasMaxLength(64).IsRequired(); journal.Property(item => item.JournalDate).IsRequired(); journal.Property(item => item.PostingDate).IsRequired(); journal.Property(item => item.FiscalYearId).IsRequired(false); journal.Property(item => item.FiscalPeriodId).IsRequired(false); journal.Property(item => item.FunctionalCurrencyCode).HasMaxLength(16).IsRequired(); journal.Property(item => item.TransactionCurrencyCode).HasMaxLength(16).IsRequired(false); journal.Property(item => item.ExchangeRate).HasPrecision(28, 12).IsRequired(false); journal.Property(item => item.ExchangeRateId).IsRequired(false); journal.Property(item => item.ExchangeRateVersionId).IsRequired(false); journal.Property(item => item.ExchangeRateVersionNumber).IsRequired(false); journal.Property(item => item.AmountAuthority).IsRequired(); journal.Property(item => item.ApprovalRequirement).IsRequired(); journal.Property(item => item.SourceContract).HasMaxLength(128).IsRequired(); journal.Property(item => item.SourceEvent).HasMaxLength(128).IsRequired(); journal.Property(item => item.SourceEvidenceId).IsRequired(false); journal.Property(item => item.SourceEvidenceVersion).IsRequired(false); journal.Property(item => item.PostingRuleId).IsRequired(false); journal.Property(item => item.PostingRuleVersionNumber).IsRequired(false); journal.Property(item => item.Description).HasMaxLength(2048).IsRequired(); journal.Property(item => item.Status).IsRequired(); journal.Property(item => item.CreatedBy).IsRequired(); journal.Property(item => item.SubmittedBy).IsRequired(false); journal.Property(item => item.ApprovedBy).IsRequired(false); journal.Property(item => item.PostedBy).IsRequired(false); journal.Property(item => item.ReversedBy).IsRequired(false); journal.Property(item => item.ReversalOfJournalId).IsRequired(false); journal.Property(item => item.ReversalJournalId).IsRequired(false); journal.Property(item => item.CorrelationId).HasMaxLength(128).IsRequired(); journal.Property(item => item.CreatedAt).IsRequired(); journal.Property(item => item.PostedAt).IsRequired(false); journal.HasIndex(item => new { item.TenantId, item.CompanyId, item.JournalSequence }).IsUnique(); journal.HasIndex(item => new { item.TenantId, item.SourceContract, item.SourceEvidenceId, item.SourceEvidenceVersion }).IsUnique().HasFilter(Database.ProviderName == "Microsoft.EntityFrameworkCore.SqlServer" ? "[SourceEvidenceId] IS NOT NULL" : "SourceEvidenceId IS NOT NULL");

        ConfigureBase(modelBuilder.Entity<FinanceJournalLineEntity>(), "JournalLines");
        var line = modelBuilder.Entity<FinanceJournalLineEntity>(); line.Property(item => item.JournalId).IsRequired(); line.Property(item => item.LineNumber).IsRequired(); line.Property(item => item.AccountId).IsRequired(); line.Property(item => item.AccountCode).HasMaxLength(64).IsRequired(); line.Property(item => item.AccountName).HasMaxLength(256).IsRequired(); line.Property(item => item.Debit).HasPrecision(28, 8).IsRequired(); line.Property(item => item.Credit).HasPrecision(28, 8).IsRequired(); line.Property(item => item.FunctionalDebit).HasPrecision(28, 8).IsRequired(); line.Property(item => item.FunctionalCredit).HasPrecision(28, 8).IsRequired(); line.Property(item => item.TransactionAmount).HasPrecision(28, 8).IsRequired(false); line.Property(item => item.TransactionCurrencyCode).HasMaxLength(16).IsRequired(false); line.Property(item => item.CostCenterId).IsRequired(false); line.Property(item => item.CostCenterCode).HasMaxLength(64).IsRequired(false); line.Property(item => item.Description).HasMaxLength(1024).IsRequired(false); line.HasIndex(item => new { item.TenantId, item.JournalId, item.LineNumber }).IsUnique(); line.HasOne<FinanceJournalEntity>().WithMany(item => item.Lines).HasForeignKey(item => new { item.TenantId, item.JournalId }).HasPrincipalKey(item => new { item.TenantId, item.Id }).OnDelete(DeleteBehavior.Cascade);

        ConfigureBase(modelBuilder.Entity<FinanceAuditEntity>(), "AuditEvents");
        var audit = modelBuilder.Entity<FinanceAuditEntity>(); audit.Property(item => item.OperationId).HasMaxLength(128).IsRequired(); audit.Property(item => item.ResourceType).HasMaxLength(128).IsRequired(); audit.Property(item => item.ResourceId).IsRequired(); audit.Property(item => item.ActorId).IsRequired(); audit.Property(item => item.SessionId).IsRequired(); audit.Property(item => item.Result).HasMaxLength(64).IsRequired(); audit.Property(item => item.Reason).HasMaxLength(2048).IsRequired(false); audit.Property(item => item.CorrelationId).HasMaxLength(128).IsRequired(); audit.Property(item => item.IdempotencyKey).HasMaxLength(256).IsRequired(false); audit.Property(item => item.OccurredAt).IsRequired();

        ConfigureBase(modelBuilder.Entity<FinanceIdempotencyEntity>(), "IdempotencyEntries");
        var idem = modelBuilder.Entity<FinanceIdempotencyEntity>(); idem.Property(item => item.ActorId).IsRequired(); idem.Property(item => item.OperationId).HasMaxLength(128).IsRequired(); idem.Property(item => item.Key).HasMaxLength(256).IsRequired(); idem.Property(item => item.Fingerprint).HasMaxLength(128).IsRequired(); idem.Property(item => item.ResourceType).HasMaxLength(128).IsRequired(); idem.Property(item => item.ResourceId).IsRequired(); idem.Property(item => item.SnapshotJson).HasMaxLength(262144).IsRequired(); idem.Property(item => item.CreatedAt).IsRequired(); idem.HasIndex(item => new { item.TenantId, item.ActorId, item.OperationId, item.Key }).IsUnique();

        ConfigureBase(modelBuilder.Entity<FinanceSourceEffectEntity>(), "SourceEffects");
        var effect = modelBuilder.Entity<FinanceSourceEffectEntity>(); effect.Property(item => item.CompanyId).IsRequired(); effect.Property(item => item.SourceContract).HasMaxLength(128).IsRequired(); effect.Property(item => item.SourceEvidenceId).IsRequired(); effect.Property(item => item.SourceEvidenceVersion).IsRequired(); effect.Property(item => item.JournalId).IsRequired(); effect.Property(item => item.CreatedAt).IsRequired(); effect.HasIndex(item => new { item.TenantId, item.CompanyId, item.SourceContract, item.SourceEvidenceId, item.SourceEvidenceVersion }).IsUnique();

        ConfigureBase(modelBuilder.Entity<FinancePaymentMethodEntity>(), "PaymentMethods");
        var method = modelBuilder.Entity<FinancePaymentMethodEntity>(); method.Property(item => item.CompanyId).IsRequired(); method.Property(item => item.Code).HasMaxLength(64).IsRequired(); method.Property(item => item.EnglishName).HasMaxLength(256).IsRequired(); method.Property(item => item.ArabicName).HasMaxLength(256).IsRequired(false); method.Property(item => item.Direction).IsRequired(); method.Property(item => item.Lifecycle).IsRequired(); method.Property(item => item.IsManual).IsRequired(); method.Property(item => item.RequiresReference).IsRequired(); method.Property(item => item.EffectiveFrom).IsRequired(); method.Property(item => item.EffectiveTo).IsRequired(false); method.HasIndex(item => new { item.TenantId, item.CompanyId, item.Code }).IsUnique();

        ConfigureBase(modelBuilder.Entity<FinanceCashAccountEntity>(), "CashAccounts");
        var cash = modelBuilder.Entity<FinanceCashAccountEntity>(); cash.Property(item => item.CompanyId).IsRequired(); cash.Property(item => item.Code).HasMaxLength(64).IsRequired(); cash.Property(item => item.EnglishName).HasMaxLength(256).IsRequired(); cash.Property(item => item.ArabicName).HasMaxLength(256).IsRequired(false); cash.Property(item => item.Kind).IsRequired(); cash.Property(item => item.CurrencyCode).HasMaxLength(16).IsRequired(); cash.Property(item => item.LinkedAccountId).IsRequired(); cash.Property(item => item.LinkedAccountCode).HasMaxLength(64).IsRequired(); cash.Property(item => item.BankReference).HasMaxLength(256).IsRequired(false); cash.Property(item => item.Lifecycle).IsRequired(); cash.Property(item => item.EffectiveFrom).IsRequired(); cash.Property(item => item.EffectiveTo).IsRequired(false); cash.HasIndex(item => new { item.TenantId, item.CompanyId, item.Code }).IsUnique(); cash.HasIndex(item => new { item.TenantId, item.CompanyId, item.LinkedAccountId }); cash.HasOne<FinanceAccountEntity>().WithMany().HasForeignKey(item => new { item.TenantId, item.CompanyId, item.LinkedAccountId }).HasPrincipalKey(item => new { item.TenantId, item.CompanyId, item.Id }).OnDelete(DeleteBehavior.Restrict);

        ConfigureBase(modelBuilder.Entity<FinanceOpenItemEntity>(), "OpenItems");
        var open = modelBuilder.Entity<FinanceOpenItemEntity>(); open.Property(item => item.CompanyId).IsRequired(); open.Property(item => item.Kind).IsRequired(); open.Property(item => item.SupplierId).IsRequired(false); open.Property(item => item.CustomerId).IsRequired(false); open.Property(item => item.SourceContract).HasMaxLength(128).IsRequired(); open.Property(item => item.SourceDocumentId).IsRequired(); open.Property(item => item.SourceDocumentVersion).IsRequired(); open.Property(item => item.SourceEvidenceId).IsRequired(); open.Property(item => item.SourceEvidenceVersion).IsRequired(); open.Property(item => item.Reference).HasMaxLength(256).IsRequired(false); open.Property(item => item.DocumentDate).IsRequired(); open.Property(item => item.DueDate).IsRequired(); open.Property(item => item.CurrencyCode).HasMaxLength(16).IsRequired(); open.Property(item => item.OriginalAmount).HasPrecision(28, 8).IsRequired(); open.Property(item => item.FunctionalCurrencyCode).HasMaxLength(16).IsRequired(); open.Property(item => item.OriginalFunctionalAmount).HasPrecision(28, 8).IsRequired(); open.Property(item => item.ExchangeRate).HasPrecision(28, 12).IsRequired(false); open.Property(item => item.ExchangeRateId).IsRequired(false); open.Property(item => item.ExchangeRateVersionId).IsRequired(false); open.Property(item => item.ExchangeRateVersionNumber).IsRequired(false); open.Property(item => item.PaymentTermId).IsRequired(false); open.Property(item => item.PaymentTermCode).HasMaxLength(64).IsRequired(false); open.Property(item => item.PaymentTermEnglishName).HasMaxLength(256).IsRequired(false); open.Property(item => item.PaymentTermArabicName).HasMaxLength(256).IsRequired(false); open.Property(item => item.PaymentTermVersionNumber).IsRequired(false); open.Property(item => item.PaymentTermVersionId).IsRequired(false); open.Property(item => item.PaymentTermEffectiveOn).IsRequired(false); open.Property(item => item.MatchEvidenceId).IsRequired(false); open.Property(item => item.MatchEvidenceVersion).IsRequired(false); open.Property(item => item.RecognitionState).IsRequired(); open.Property(item => item.RecognitionJournalId).IsRequired(false); open.Property(item => item.SourceSnapshot).HasMaxLength(262144).IsRequired(false); open.HasIndex(item => new { item.TenantId, item.CompanyId, item.SourceContract, item.SourceEvidenceId, item.SourceEvidenceVersion }).IsUnique(); open.HasIndex(item => new { item.TenantId, item.CompanyId, item.Kind, item.DueDate });

        ConfigureBase(modelBuilder.Entity<FinanceSettlementDocumentEntity>(), "SettlementDocuments");
        var document = modelBuilder.Entity<FinanceSettlementDocumentEntity>(); document.Property(item => item.CompanyId).IsRequired(); document.Property(item => item.Status).IsRequired(); document.Property(item => item.Direction).IsRequired(); document.Property(item => item.SupplierId).IsRequired(false); document.Property(item => item.CustomerId).IsRequired(false); document.Property(item => item.CashAccountId).IsRequired(); document.Property(item => item.PaymentMethodId).IsRequired(); document.Property(item => item.DocumentDate).IsRequired(); document.Property(item => item.CurrencyCode).HasMaxLength(16).IsRequired(); document.Property(item => item.Amount).HasPrecision(28, 8).IsRequired(); document.Property(item => item.FunctionalCurrencyCode).HasMaxLength(16).IsRequired(); document.Property(item => item.FunctionalAmount).HasPrecision(28, 8).IsRequired(); document.Property(item => item.ExchangeRate).HasPrecision(28, 12).IsRequired(false); document.Property(item => item.ExchangeRateId).IsRequired(false); document.Property(item => item.ExchangeRateVersionId).IsRequired(false); document.Property(item => item.ExchangeRateVersionNumber).IsRequired(false); document.Property(item => item.ExternalReference).HasMaxLength(256).IsRequired(false); document.Property(item => item.Description).HasMaxLength(2048).IsRequired(false); document.Property(item => item.CreatedBy).IsRequired(); document.Property(item => item.SubmittedBy).IsRequired(false); document.Property(item => item.ApprovedBy).IsRequired(false); document.Property(item => item.PostedBy).IsRequired(false); document.Property(item => item.ReversedBy).IsRequired(false); document.Property(item => item.PostedJournalId).IsRequired(false); document.Property(item => item.ReversalJournalId).IsRequired(false); document.Property(item => item.CreatedAt).IsRequired(); document.Property(item => item.PostedAt).IsRequired(false); document.HasIndex(item => new { item.TenantId, item.CompanyId, item.Id }).IsUnique(); document.HasIndex(item => new { item.TenantId, item.CompanyId, item.Direction, item.DocumentDate }); document.HasOne<FinanceCashAccountEntity>().WithMany().HasForeignKey(item => new { item.TenantId, item.CompanyId, item.CashAccountId }).HasPrincipalKey(item => new { item.TenantId, item.CompanyId, item.Id }).OnDelete(DeleteBehavior.Restrict); document.HasOne<FinancePaymentMethodEntity>().WithMany().HasForeignKey(item => new { item.TenantId, item.CompanyId, item.PaymentMethodId }).HasPrincipalKey(item => new { item.TenantId, item.CompanyId, item.Id }).OnDelete(DeleteBehavior.Restrict);

        ConfigureBase(modelBuilder.Entity<FinanceAllocationEntity>(), "Allocations");
        var allocation = modelBuilder.Entity<FinanceAllocationEntity>(); allocation.Property(item => item.CompanyId).IsRequired(); allocation.Property(item => item.SettlementDocumentId).IsRequired(); allocation.Property(item => item.OpenItemId).IsRequired(); allocation.Property(item => item.Amount).HasPrecision(28, 8).IsRequired(); allocation.Property(item => item.CurrencyCode).HasMaxLength(16).IsRequired(); allocation.Property(item => item.FunctionalAmount).HasPrecision(28, 8).IsRequired(); allocation.Property(item => item.AllocationDate).IsRequired(); allocation.Property(item => item.Status).IsRequired(); allocation.Property(item => item.ReversalOfAllocationId).IsRequired(false); allocation.Property(item => item.JournalId).IsRequired(false); allocation.Property(item => item.CreatedBy).IsRequired(); allocation.Property(item => item.Reason).HasMaxLength(2048).IsRequired(false); allocation.HasIndex(item => new { item.TenantId, item.CompanyId, item.SettlementDocumentId, item.Id }).IsUnique(); allocation.HasIndex(item => new { item.TenantId, item.CompanyId, item.ReversalOfAllocationId }).IsUnique().HasFilter(Database.ProviderName == "Microsoft.EntityFrameworkCore.SqlServer" ? "[ReversalOfAllocationId] IS NOT NULL" : "ReversalOfAllocationId IS NOT NULL"); allocation.HasOne<FinanceSettlementDocumentEntity>().WithMany().HasForeignKey(item => new { item.TenantId, item.CompanyId, item.SettlementDocumentId }).HasPrincipalKey(item => new { item.TenantId, item.CompanyId, item.Id }).OnDelete(DeleteBehavior.Restrict); allocation.HasOne<FinanceOpenItemEntity>().WithMany().HasForeignKey(item => new { item.TenantId, item.CompanyId, item.OpenItemId }).HasPrincipalKey(item => new { item.TenantId, item.CompanyId, item.Id }).OnDelete(DeleteBehavior.Restrict);
    }

    private void ConfigureBase<TEntity>(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<TEntity> entity, string tableName) where TEntity : FinanceEntity
    {
        if (Database.ProviderName == "Microsoft.EntityFrameworkCore.SqlServer") entity.ToTable(tableName, "finance"); else entity.ToTable(tableName);
        entity.HasKey("Id"); entity.Property("Id").ValueGeneratedNever(); entity.Property(item => item.TenantId).HasConversion(item => item.Value, value => new TenantId(value)).IsRequired();
        var version = entity.Property<byte[]>("Version").IsRequired().IsConcurrencyToken(); if (Database.ProviderName == "Microsoft.EntityFrameworkCore.SqlServer") version.IsRowVersion(); else version.ValueGeneratedNever();
        entity.HasQueryFilter(item => item.TenantId == TrustedTenantId);
    }
}

#pragma warning restore CS1591
